### ISSUE TITLE
Question: What is the reason for using the RG format for covariance textures?

### ISSUE THREAD

**Issue by xiasun** [mkkellogg/GaussianSplats3D#101]
For covariance textures, it seems that using 2 RGB texels for a cov data unit is similar to using 3 RG texels, which can also make the data more compact. 
Is the only reason for using RG that it has better compatibility?
Thank you!

**Comment by mkkellogg** [comment]
The main reason is that Three.js removed support for the RGB format because often the underlying WebGL implementation or driver would just convert to RGBA format.

**Comment by xiasun** [comment]
Oh, I wasn't aware of that. Thanks!
