### ISSUE TITLE
Feature: Editing mode

### ISSUE THREAD

**Issue by yufeng1103** [mkkellogg/GaussianSplats3D#105]
I'm not sure if you have any plans to add an editing mode in the near future, which would be very useful

**Comment by mkkellogg** [comment]
At some point in the future, I would definitely like to add editing capabilities. It's really just a matter of finding the time :)

**Comment by mkkellogg** [comment]
Closing this one for now -- Since SuperSplat has evolved into such a capable editor for splats, I think I'm going to set aside any plans for creating an editor myself.
