### ISSUE TITLE
Different inference quilty 

### ISSUE THREAD

**Issue by GuoFengYung** [mkkellogg/GaussianSplats3D#106]
Hi,
I have question.
Thanks!
When I use inria's SIBR Viewer, the quality is different from that of Webgl.(left is SIBR viewer, right is WebGl)
screenshot:
![圖片2](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/d20d0666-e43d-4e44-946e-0740570dfa8d)

**Comment by mkkellogg** [comment]
I haven't really played around with the viewer from INRIA too much, but I'm not surprised there is a different in quality. Their viewer sorts the splat per on a per pixel basis using CUDA kernels (similar to compute shaders in WebGPU). Since WebGL does not have compute shaders, the next best thing we can do is a universal sort of all the splats based on distance from the camera and render them based on that ordering.

**Comment by GuoFengYung** [comment]
Thanks for your reply!
By the way, is the main problem the splat sorting or the third-order spherical harmonic function?

**Comment by mkkellogg** [comment]
The `integerBasedSort` parameter is a parameter to the `Viewer` constructor, you could use it like this:
```
const viewer = new GaussianSplats3D.Viewer({
    'integerBasedSort': false      
});
```

**Comment by GuoFengYung** [comment]
Thanks for your reply!

**Comment by mkkellogg** [comment]
Hi, would you be able to post a link to that splat you had quality issues with? I'm working on some updates that might help with it.

**Comment by GuoFengYung** [comment]
Hi,  This data is the speaker in the picture above
https://drive.google.com/file/d/1oRL1K5tQ6tFsvNh4mkQCBYiaMxo_76nH/view?usp=drive_link
But it was run using inria GS code without using the mip gaussian method(antialiased).

this link is use antialiased mode to train:
https://drive.google.com/file/d/1-RFMqRpw6xZ65VVuSvfZurNpf6Q37djb/view?usp=sharing
When I rotate the view, it will feel dirty at some angles
like this:
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/054e589a-a01c-4d98-aa22-1ba263056a92)
At first I thought it was a sorting problem, but after changing the sorting algorithm, the effect was still the same.
By the way, I have implemented antialiased mode on the viewer before.

Thanks for your reply!

**Comment by mkkellogg** [comment]
What happens to the visual quality if you set the `Viewer` constructor parameter `halfPrecisionCovariancesOnGPU` to `false`:

```
const viewer = new GaussianSplats3D.Viewer({
    `halfPrecisionCovariancesOnGPU`: false;
});
```

**Comment by GuoFengYung** [comment]
yes, my viewer option is:
```   
 import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';
    const viewer = new GaussianSplats3D.Viewer({
        'cameraUp': [0, -1, 0],
        'initialCameraPosition': [-2.6, -8, 0.5],
        'initialCameraLookAt': [3, -2.8, -0.7],
        'halfPrecisionCovariancesOnGPU': false,
        'integerBasedSort': false,
        'enableDistancesComputationOnGPU': false,
        'dynamicMode': false,
        'gpuAcceleratedSort': true
    });

   ```

**Comment by mkkellogg** [comment]
have you tried the sweater scene in Kevin Kwok's GS viewer (https://github.com/antimatter15/splat)? How does it look there?

**Comment by mkkellogg** [comment]
It also might be worth testing out Polycam's viewer to see how it looks there. For what it's worth, I added a hacky parameter `focalAdjustment` to the `Viewer` in my latest branch: https://github.com/mkkellogg/GaussianSplats3D/tree/fix_render_quality, I found that setting it to a high value can improve visual quality for some scenes.

**Comment by GuoFengYung** [comment]
Kevin Kwork(It seems to be similar to the current viewer quality):
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/c10beaaf-577b-45ee-874b-8ab68a484898)

It was experimented a long time ago
Polycam(In addition, Polycam does not implement the mip gaussian method, so there will be a gap in quality, but they have implemented spherical harmonics to create changes in light and shadow.):
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/43314406/9c949a27-5ee9-4be8-8f22-fd201552e8ad)
By the way, I am also implementing the spherical harmonic function, but the position of the view dir is not well grasped at present, causing the color to become strange.
ok i will try the [fix_render_quality] (https://github.com/mkkellogg/GaussianSplats3D/tree/fix_render_quality).
Thank !!!!
