### ISSUE TITLE
why might the viewer be stuck on loading?

### ISSUE THREAD

**Issue by lewibs** [mkkellogg/GaussianSplats3D#109]
Im trying to use the npm package with the demo code in a react app. For some reason the viewer is stuck on loading. What are some things that could cause this? In your working version it generally loads within a second

**Comment by lewibs** [comment]
its the cors issue documented at the bottom of the readme.

**Comment by wayc04** [comment]
I meet the same question. Do you have some solutions?

**Comment by mkkellogg** [comment]
It might be the CORS issue mentioned in the README, but it also might be that the file you're trying to load doesn't exist.  Double check the path & file name.
