### ISSUE TITLE
how could i do to establish an online demo?

### ISSUE THREAD

**Issue by Linkersem** [mkkellogg/GaussianSplats3D#11]
Thx for your great work !
I have run successfully locally,
How could i do to run it online?

thx for your reply!

**Comment by nosy-b** [comment]
Same I m trying to put it online but I got an error: 

"DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated."

Thanks!

**Comment by mkkellogg** [comment]
The`Viewer` class uses shared memory (via a typed array backed by a `SharedArrayBufffer`) to communicate with the web worker that sorts the splats. This mechanism presents a potential security issue, you can read more about it here: https://web.dev/articles/cross-origin-isolation-guide.

To get around it, you need a couple of extra HTTP headers sent in the response from the server, so however you're running it online, you'll need to be able to set those extra headers. For the local demo I run a simple HTTP server (`util/server.js`) that sets those headers:

```javascript
response.setHeader("Cross-Origin-Opener-Policy", "same-origin");
response.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
```

**Comment by nosy-b** [comment]
Ooo thanks @mkkellogg it works! (I didn't expect to have to write to edit the .htaccess on my host provider)

Congrats for the good work by the way :)

**Comment by fujiazhiyu** [comment]
> The`Viewer` class uses shared memory (via a typed array backed by a `SharedArrayBufffer`) to communicate with the web worker that sorts the splats. This mechanism presents a potential security issue, you can read more about it here: https://web.dev/articles/cross-origin-isolation-guide.
> 
> To get around it, you need a couple of extra HTTP headers sent in the response from the server, so however you're running it online, you'll need to be able to set those extra headers. For the local demo I run a simple HTTP server (`util/server.js`) that sets those headers:
> 
> ```js
> response.setHeader("Cross-Origin-Opener-Policy", "same-origin");
> response.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
> ```
> 
> If you're using Apache, you can edit the `.htaccess` file to do that, by adding the lines:
> 
> ```
> Header add Cross-Origin-Opener-Policy "same-origin"
> Header add Cross-Origin-Embedder-Policy "require-corp"
> ```

Hi, I use the nginx, and add the following configuraions:

```
add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
add_header 'Cross-Origin-Opener-Policy' 'same-origin';
```

but the first time I did not remove your header settings in `util/server.js`, so when I checked the chrome dev tools, I found there are duplicate same header settings of `Cross-Origin-Embedder-Policy: require-corp` and `Cross-Origin-Opener-Policy: same-origin`. Under this situation, it would also remind that "DOMException: Failed to execute 'postMessage' on 
 DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated." and it could not work
However when I remove the header settings in your `server.js` file, it works.

I wonder why it behaves like this?

**Comment by Linkersem** [comment]
> > The`Viewer` class uses shared memory (via a typed array backed by a `SharedArrayBufffer`) to communicate with the web worker that sorts the splats. This mechanism presents a potential security issue, you can read more about it here: https://web.dev/articles/cross-origin-isolation-guide.
> > To get around it, you need a couple of extra HTTP headers sent in the response from the server, so however you're running it online, you'll need to be able to set those extra headers. For the local demo I run a simple HTTP server (`util/server.js`) that sets those headers:
> > ```
> > response.setHeader("Cross-Origin-Opener-Policy", "same-origin");
> > response.setHeader("Cross-Origin-Embedder-Policy", "require-corp");
> > ```
> > 
> > 
> > If you're using Apache, you can edit the `.htaccess` file to do that, by adding the lines:
> > ```
> > Header add Cross-Origin-Opener-Policy "same-origin"
> > Header add Cross-Origin-Embedder-Policy "require-corp"
> > ```
> 
> Hi, I use the nginx, and add the following configuraions:
> 
> ```
> add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
> add_header 'Cross-Origin-Opener-Policy' 'same-origin';
> ```
> 
> but the first time I did not remove your header settings in `util/server.js`, so when I checked the chrome dev tools, I found there are duplicate same header settings of `Cross-Origin-Embedder-Policy: require-corp` and `Cross-Origin-Opener-Policy: same-origin`. Under this situation, it would also remind that "DOMException: Failed to execute 'postMessage' on DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated." and it could not work However when I remove the header settings in your `server.js` file, it works.
> 
> I wonder why it behaves like this?

Hi, I meet the same problem,when i first run the code for online,then I try to use https instead the origin http,I have solved this problem to produce my own certification and keys, I think this may be helpful to you

**Comment by fujiazhiyu** [comment]
@Linkersem  Oh, thanks for your reply, but that is not my question hahaha. I also use the https.
I mean it would not work If I keep both the nginx header configuration and the author's server.js header settings.
Maybe it has something to do with the way the browser handles headers, but I don't know exactly why.

**Comment by mkkellogg** [comment]
@fujiazhiyu  Did you ever figure out your issues with nginx?

**Comment by mkkellogg** [comment]
Closing for now, please let me know if you continue to experience issues.

**Comment by softyoda** [comment]
Hi, just wanted to know as I know some people are skilled to make [run anything on anything](https://stackoverflow.com/questions/15718649/how-to-publish-a-website-made-by-node-js-to-github-pages), can mkkellogg 3dgs viewer run on github-pages, or does it really need a backend?
