### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by laraduarte** [mkkellogg/GaussianSplats3D#111]
Is is possible to install threejs like this -> GaussianSplats3D.install({ THREE: THREE });

I want to avoid rendering threejs multiple times
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/1926934/79205930-238c-4791-a9d4-d80d4fb86b2f)

**Comment by mkkellogg** [comment]
This isn't really possible due to the fact that the library is ES module based. You can avoid this error by making your application ES module based as well. Then you link the Three.js module into the application in one location like this:

```
<script type="importmap">
    {
        "imports": {
            "three": "./lib/three.module.js",
        }
    }
</script>
```
