### ISSUE TITLE
TransformControls

### ISSUE THREAD

**Issue by lewibs** [mkkellogg/GaussianSplats3D#118]
Looks like when I use transform controls the controls appear in front of objects added into the scene but behind the splat. Would you happen to know what could be causing that and how to fix it?

**Comment by mkkellogg** [comment]
Sorry I missed this one, did you ever get this sorted out?

**Comment by mkkellogg** [comment]
Closing this one for now, let me know if you still need some assistance with it.

**Comment by AlexRynas** [comment]
@mkkellogg I can confirm that this bug still exists. It can be bypassed in the following way: for all transformControls children set depthTest and depthWrite equal to true and increase renderOrder, for example to three. This is not the best solution, but maybe it will help someone.
