### ISSUE TITLE
Uncaught Error: should never get here

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#119]
SplatMesh.js:1113 Uncaught Error: should never get here
    at t (SplatMesh.js:1113:35)

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/9602197/411f5f96-e825-448b-befb-0c1cba89fdca)

test.splat
[test.zip](https://github.com/mkkellogg/GaussianSplats3D/files/14196138/test.zip)

**Comment by mkkellogg** [comment]
Does this error happen every time you load this scene, and does it happen with any other scene? I can't reproduce it on my end with the `test.splat` you provided, so I'm not sure exactly what is happening. As a temporary work-around you can disable the partial GPU accelerated sort by passing `gpuAcceleratedSort: false` to the `Viewer` constructor.

**Comment by gotoeasy** [comment]
Yes, this error occurs every time I load this scene, and it varies for other scenes - some have the error, while others don't.

After disable the partial GPU accelerated sort, the error no longer occurs. I'll stick with this workaround for now. Thank you.

**Comment by gotoeasy** [comment]
> Does this error happen every time you load this scene, and does it happen with any other scene? I can't reproduce it on my end with the `test.splat` you provided, so I'm not sure exactly what is happening. As a temporary work-around you can disable the partial GPU accelerated sort by passing `gpuAcceleratedSort: false` to the `Viewer` constructor.

When setting gpuAcceleratedSort to false, it noticeably slows down. However, setting it to true can lead to errors on some machines that do not support it. Since errors are unacceptable, we are forced to set it to false, which is a pity. 

Is there a way to automatically determine the setting? 
For example, we could try checking if it's supported when set to true, and if not, handle it as if it were set to false.

**Comment by mkkellogg** [comment]
Do you see specific errors in the developer console? If so, could you post them here? They would be helpful in possibly figuring out a way to determine whether or not a machine supports GPU acceleration. Also, on what kinds of machines have you seen the error?

**Comment by gotoeasy** [comment]
I am using the code from the progressive_loading branch, and errors no longer occur.
