### ISSUE TITLE
Offsetting splat

### ISSUE THREAD

**Issue by LegendTova** [mkkellogg/GaussianSplats3D#12]
Hello, I am not very familiar with Three.js but have worked with Webgl and was wondering where in the code I might be able to offset the origin to draw the splat in a different location.  I presumed it should be in the SplatBuffer where I have tried modifying the position functions to shift the splat. But all I have achieved is some of the guassians being shifted and not all. So I was wondering if you would know off the top of your head where this would take place. I also tried adding a translation matrix buildPreComputedBuffers() and that didn't seem to work. If you could point me in a direction where this would be achievable in your code that would me much appreciated

**Comment by Linkersem** [comment]
Yes,I have meet similar problem, it seems the pose I set is wrong; for example ,I only set x value ,but it seems the y values also have changed, I am very confused
Thx for your relpy

**Comment by mkkellogg** [comment]
Sorry for the very late response, is there still any interest in doing this? If so, it's doable, but a little yucky :)

**Comment by seppestaes** [comment]
To move the entire GS scene (location, rotation), you can pass a SplatMesh.position and SplatMesh.quaternion.

**Comment by mkkellogg** [comment]
Closing this for now, but I'll leave everyone with this:

To apply transformations when loading a scene, you can do the following:

```javascript
viewer.loadFiles([{
            'path': '<path to first .ply, .ksplat, or .splat file>',
            'splatAlphaRemovalThreshold': 20,
        },
        {
            'path': '<path to second .ply, .ksplat, or .splat file>',
            'rotation': [-0.14724434, -0.0761755, 0.1410657, 0.976020],
            'scale': [1.5, 1.5, 1.5],
            'position': [-3, -2, -3.2],
        }
    ])
    .then(() => {
        viewer.start();
    });
```
