### ISSUE TITLE
Online demo page again not working

### ISSUE THREAD

**Issue by fasteinke** [mkkellogg/GaussianSplats3D#122]
Unfortunately, since the VR update, the issue as decribed here, https://github.com/mkkellogg/GaussianSplats3D/issues/92, has reared its ugly head again. That is, the demos work, but not a local file - a black screen only ...

**Comment by mkkellogg** [comment]
Thanks for pointing this out again! I somehow updated an old version of the online demo page with the VR link. I just pushed a fix, can you check it again?

**Comment by fasteinke** [comment]
All good now, both demos and local files work ... thanks!

**Comment by mkkellogg** [comment]
Great!
