### ISSUE TITLE
Iframe

### ISSUE THREAD

**Issue by VladimirKobranov** [mkkellogg/GaussianSplats3D#123]
How to include viewer to iframe?
Have a lot of headache with cors and postmessage. 

Tried bunch of ways, none of them is not working.

**Comment by mkkellogg** [comment]
No extra work should be required to get the viewer to work within an `iframe` beyond what you would do to get any other page working in an `iframe`. You do need to have extra CORS headers set in your web server for the shared memory feature of the viewer to work, as mentioned in the README. You can try disabling shared memory via the `sharedMemoryForWorkers` constructor parameter:
```
const viewer = new GaussianSplats3D.Viewer({
    'sharedMemoryForWorkers': false,
});
```

**Comment by VladimirKobranov** [comment]
for some reason it worked this time in vite
