### ISSUE TITLE
No XR on iOS 17 with XR Viewer

### ISSUE THREAD

**Issue by samhodge** [mkkellogg/GaussianSplats3D#127]
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/86946/33e6e465-18a2-4c98-990a-cd3f7241f7ff)

I tried to get it to work and the button appears but no result

**Comment by kotauchisunsun** [comment]
@samhodge 
As far as I know, Apple's compliance with the WebXR specification is very poor.
You can check your browser's compliance with WebXR at the following site
https://immersive-web.github.io/webxr-samples/

Probably, Safari on iOS will show no support for WebAR. This is probably why the demo program does not work.

**Comment by samhodge** [comment]
Oh sorry I was using another browser

XRViewer

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/86946/fdb9085c-160d-454f-a772-d4f5950806f7)


https://labs.mozilla.org/projects/webxr-viewer/

**Comment by samhodge** [comment]
AR works VR doesn't on my phone ![image](https://github.com/mkkellogg/GaussianSplats3D/assets/86946/e597a757-367c-4dc6-976f-eb44d988aa7f)

**Comment by jakerator** [comment]
AR doesn't work on IOS "WebXR Viewer (firefox)" neither on "XR Browser".
But "XR Browser" works fine with [Lumalabs GS library ](https://lumalabs.ai/luma-web-library).

So probably some issue with the threejs renderer. Maybe try to use buil-in ARButton component?

**Comment by mkkellogg** [comment]
Do any of the three.js official AR examples work for you?

https://threejs.org/examples/webxr_ar_lighting.html
https://threejs.org/examples/webxr_ar_cones.html
https://threejs.org/examples/webxr_ar_hittest.html

**Comment by samhodge** [comment]
> Do any of the three.js official AR examples work for you?
> 
> 
> 
> https://threejs.org/examples/webxr_ar_lighting.html
> 
> https://threejs.org/examples/webxr_ar_cones.html
> 
> https://threejs.org/examples/webxr_ar_hittest.html
> 
> 

I tried each of those URLs in the following App

https://apps.apple.com/au/app/webxr-viewer/id1295998056

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/86946/94ea401d-fc10-49bb-8e76-b17cbebe99d5)

They all failed in different ways some had the Start AR like button others had a blank screen

**Comment by mkkellogg** [comment]
Based on your findings my guess is that there is an issue with three.js' WebXR implementation. Hopefully I can dedicate some time to investigate in the near future.

**Comment by samhodge** [comment]
Thanks for your response, it seems upstream of your work. But could be worth informing the threejs people of the issue 

The iOS audience is a large portion of users

**Comment by dlazares** [comment]
@mkkellogg there's a bug in the current viewer for webxr. You can test this by downloading the visionos simulator, enabling webxr (settings -> app -> safari -> advanced -> feature flags -> enable webxr). you need to change the button to VR mode. There's a big jitter. This wasn't on previous versions. we have an earlier fork that was working on Apple Vision Pro.

**Comment by mkkellogg** [comment]
Sorry for the extended delay on this one, I made some VR/AR updates in a previous release, have these issues cleared up?

**Comment by mkkellogg** [comment]
Going to close this one for now, please let me know if this issue creeps up again.
