### ISSUE TITLE
Rendering on Smartphone 

### ISSUE THREAD

**Issue by nosy-b** [mkkellogg/GaussianSplats3D#13]
Super nice work, it renders super smooth on my Macbook pro :)

I "optimized "the ply to splat with your function but it still doens't render on my android phone (not super fast but not slow Pixel 7)

Any ideas of optimization? I tested the 3 examples too, it doesn"t work. 

Thanks!

**Comment by softyoda** [comment]
Tested on my side using a P30 Pro, on firefox mobile :

https://github.com/mkkellogg/GaussianSplats3D/assets/13988751/be01c034-fcd5-4beb-8537-019a9bb5f0c4

Exactly same behavior on chrome mobile.

**Comment by mkkellogg** [comment]
For what it's worth, I have had trouble running on mobile as well. I'm pretty sure it has to do with the large amount of memory used by the viewer. There's currently no quick fix, I just need to work on making the viewer more efficient with memory usage.

**Comment by MarcusAndreasSvensson** [comment]
@mkkellogg There's two issues from my experience so far of this issue.

The first one I encountered was that safari doesn't support importmap. This one I solved by bundling with Vite instead. This seems to be one recommended way according to mrDoob (Author of Three.js). Surely though this can be handled in another way.

Additionally as you say, there seems to be an issue with memory usage.
I managed to get the truck scene running on a iPhone 14 pro with splatAlphaRemovalThreshold set to 30. 

<img width="367" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/37627630/e39089e7-3229-487c-ba21-ca26620963c2">

**Comment by mkkellogg** [comment]
I made some tweaks to how the data textures are populated and reduced their size. I can now load all the demo scenes on my samsung galaxy s9... but it's very, very sloooooow. Pretty much unusable, but at least it loads now :) I will continue working on that. @MarcusAndreasSvensson As for the import map issue, it looks like Safari supports them as of version 16.4?

**Comment by JiamingSuen** [comment]
I'm having trouble running in Safari on my iPhone (latest OS version). It seems that the error is related to [this line](https://github.com/mkkellogg/GaussianSplats3D/blob/481ca808b25def092600ebc6ef6f7c283c918b24/src/worker/SortWorker.js#L100) in the sort worker. I'm happy to provide more info if needed.

<img width="1223" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/8616975/914acce6-d7be-4898-90b3-5c3b9215ca3f">

**Comment by MarcusAndreasSvensson** [comment]
@mkkellogg  Hmm, interesting. Yet I'm getting 
<img width="500" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/37627630/e43e30f5-b15b-46db-bcff-a76fbd3f887e">
On Safari both on iPhone and Macbook.

**Comment by mkkellogg** [comment]
Closing this issue for now, please let me know if these issues come up again. I know mobile performance is still not great, I will try to work on that :)
