### ISSUE TITLE
iPhone 13 Pro Max not loading model

### ISSUE THREAD

**Issue by laraduarte** [mkkellogg/GaussianSplats3D#130]
The viewer is not working on iPhone 13 Pro Max. Do you know if it's possible to implement a workaround?

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/1926934/2c588fb0-6c7f-4137-bd77-8f256c8c268a)

**Comment by mkkellogg** [comment]
Can you give me a little more information to help me debug -- which browser are you using, and what settings are you passing to the `Viewer`? From the error it looks like something is going wrong when loading the sorting web worker, but I'm not sure why. Maybe try different browsers to see if that changes anything.

**Comment by laraduarte** [comment]
The issue is the same in Safari and Chrome in iPhone 13 Pro Max but it works perfectly in iPhone 13, I believe the issue might be OS related

 _viewer = new GaussianSplats3D.DropInViewer({
        'threeScene': scene,
        'selfDrivenMode': false,
        'renderer': renderer,
        'camera': camera,
        'useBuiltInControls': false,
        'ignoreDevicePixelRatio': false,
        'gpuAcceleratedSort': false,
        'halfPrecisionCovariancesOnGPU': false,
        'sharedMemoryForWorkers': false,
        'integerBasedSort': true,
        'webXRMode': GaussianSplats3D.WebXRMode.None
    });

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/1926934/5d90cee6-b7a2-4cff-b444-c8278eec58cf)

**Comment by mkkellogg** [comment]
Would it be possible to update your version of iOS and try again? FWIW I have an older iPhone 11, and it's running iOS 17.1 and it seems to work fine.

**Comment by laraduarte** [comment]
after updating the ios the issue seems to be fixed :)

**Comment by mkkellogg** [comment]
Great, I love it when problems fix themselves!
