### ISSUE TITLE
Flicker during fast camera motion on Quest 3 in WebXR

### ISSUE THREAD

**Issue by JiamingSuen** [mkkellogg/GaussianSplats3D#131]
https://github.com/mkkellogg/GaussianSplats3D/assets/8616975/90656f34-4f02-4787-a9e9-611c1aaefc47

As shown in the screen recording, with relatively rapid head movements (i.e., camera motion), the entire scene flickers randomly. Some random and smaller artifacts (line jittering) are also present outside of WebXR in the normal browser interface, but cannot be recorded in the screen recording.

I'm using the VR mode (`'webXRMode': GaussianSplats3D.WebXRMode.VR`) in the recording above. AR mode also shows similar flickering when looking at the gaussians. More severe flickering will present when the gaussians are out of the rendering FoV, as shown in this video:

https://github.com/mkkellogg/GaussianSplats3D/assets/8616975/66c25e67-bd97-4429-beb4-a5f0b15cd057

I understand this could be hard to reproduce or debug. I‘m willing to investigate further, but I'm uncertain about the best approach to take. Any assistance would be greatly appreciated.

Thanks for this amazing repo!

**Comment by mkkellogg** [comment]
I have noticed this issue as well and I'm not sure what's causing it. Hopefully I'll have some time soon to investigate; I'll let you know when I find out more.

**Comment by mkkellogg** [comment]
So it looks like it's an issue with the GPU-based sort acceleration. If you run the viewer with these parameters it should fix it:
```
      'gpuAcceleratedSort': false,
      'sharedMemoryForWebWorkers': false
```
I'll get a fix into the next release where `gpuAcceleratedSort` and `sharedMemoryForWebWorkers` are disabled automatically in VR or AR mode

**Comment by mkkellogg** [comment]
Ah, so there's a typo in your code above (because there was a typo in my example). You have `gpuAcceleratesSort`, instead you need `gpuAcceleratedSort`

**Comment by JiamingSuen** [comment]
😅👏Everything works now, thanks for the rapid response!

**Comment by nosy-b** [comment]
Oooo thanks for the info, I was gonna tell you there is a typo ;) It runs without glitch now on the Quest 3 :) Great work!
