### ISSUE TITLE
Cursor raycasting not working after rotating scene

### ISSUE THREAD

**Issue by Bishadkoju** [mkkellogg/GaussianSplats3D#133]
Hi,
Rather than setting the cameraUp parameter, i was trying to rotate the whole scene. But after rotating the scene, the raycaster is not woking. Cursor position is always set to [0, 0, 0]
This is the code:

```
const viewer = new GaussianSplats3D.Viewer({
  // 'cameraUp': [0, -1, -0.54],
  'initialCameraPosition': [-3.15634, -0.16946, -0.51552],
  // 'initialCameraLookAt': [1.52976, 2.27776, 1.65898]
});
let path = 'assets/data/garden/garden';
path += isMobile() ? '.ksplat' : '_high.ksplat';
viewer.addSplatScene(path,{
  rotation: new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0, -1, -0.54), new THREE.Vector3(0,1,0)).toArray()
})
.then(() => {
    viewer.start();
});
```

<img width="1175" alt="Screenshot 2024-02-20 at 23 39 43" src="https://github.com/mkkellogg/GaussianSplats3D/assets/45235817/8778fc62-0675-443c-9b5b-ac6f49d2f7ae">

**Comment by gonzalle** [comment]
Noticed the same thing when scaling... didn't test rotation but might be the same

**Comment by mkkellogg** [comment]
Are either of you (or both of you) able to try the `fix_raycasting_alt` branch? I have a fix for this issue there, please let me know if you still see the problem. Thanks!

**Comment by Bishadkoju** [comment]
Hi it's working now. Thanks

**Comment by mkkellogg** [comment]
Glad to hear it! I have updated `main` with the fix.
