### ISSUE TITLE
Does anyone have this problem?  SharedArrayBuffer transfer requires self.crossOriginIsolated

### ISSUE THREAD

**Issue by did66** [mkkellogg/GaussianSplats3D#138]
123f1564-29cf-4f0b-9e70-4a7413c34625:169 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated.
    at blob:http://localhost:8080/123f1564-29cf-4f0b-9e70-4a7413c34625:169:26
(anonymous) @ 123f1564-29cf-4f0b-9e70-4a7413c34625:169
Promise.then (async)
self.onmessage @ 123f1564-29cf-4f0b-9e70-4a7413c34625:156

**Comment by did66** [comment]
I know the answer.
Need to set up headers: {
			'Cross-Origin-Embedder-Policy': 'require-corp',
			'Cross-Origin-Opener-Policy': 'same-origin'
		},

**Comment by LHGRylynn** [comment]
> I know the answer. Need to set up headers: { 'Cross-Origin-Embedder-Policy': 'require-corp', 'Cross-Origin-Opener-Policy': 'same-origin' },

Could you tell me more about where to set up this headers?
