### ISSUE TITLE
Splat scale feature

### ISSUE THREAD

**Issue by Bishadkoju** [mkkellogg/GaussianSplats3D#144]
Hi, would it be possible to implement "Splat Scale" feature as in [Unity GaussianSplatting Viewer](https://github.com/aras-p/UnityGaussianSplatting) .
<img width="260" alt="Screenshot 2024-03-05 at 21 48 33" src="https://github.com/mkkellogg/GaussianSplats3D/assets/45235817/062194f0-7537-467c-8bba-f3e78cafca25">

Also, Instead of showing the mesh cursor, I would like to change the color of the splat that the mouse is hovering. How can i implement this ?
Thank you.

**Comment by mkkellogg** [comment]
This would be a pretty easy thing to control through an API function, something like `Viewer.setSplatScale()`. I will try to add a function like that soon :)

**Comment by Bishadkoju** [comment]
Also , in the current implementation would it be possible to change the color of a single splat? could you guide me through it ?
Thanks;

**Comment by mkkellogg** [comment]
I'm including a function to set splat scale in the branch about to merge: https://github.com/mkkellogg/GaussianSplats3D/pull/177. The function is `SplatMesh.setSplatScale()` As for changing the color of specific splats, that will be more work, and I'll leave it up to you to implement that :) To do that you'd have to follow a similar approach as sending any of the other splat data to the shader. I would store a boolean to designate whether or not a splat is selected in one of those data textures.

**Comment by Bishadkoju** [comment]
Sure, thank you :)

**Comment by nosy-b** [comment]
Oo fun I added a setSplatScale on my code the other day :) 
Though I didn't find a way in the shader to make splats look like pointclouds when small (dot/circle and not ellipse)

**Comment by mkkellogg** [comment]
In the branch I'm about to merge (https://github.com/mkkellogg/GaussianSplats3D/tree/orthographic_projection) I'm adding a function to enable point-cloud rendering, where each splat is rendered as a circle: `SplatMesh.setPointCloudModeEnabled()`, which will hopefully solve that issue :)

**Comment by mkkellogg** [comment]
These methods are now in the latest release: `v0.3.7`. Let me know how they work out for you!

**Comment by mkkellogg** [comment]
I'm going to close this for now, let me know if you encounter any trouble with the updates!
