### ISSUE TITLE
High GPU usage

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#145]
Even when the displayed scene remains static without updates or changes, the GPU maintains a high usage rate. Is it possible to assess the state to minimize unnecessary updates? 

Similar to `https://github.com/playcanvas/super-splat`, the GPU usage is not consistently high.

**Comment by gotoeasy** [comment]
https://projects.markkellogg.org/threejs/gaussian_splats_3d_demos/garden.html

video:
[20240308_091335.zip](https://github.com/mkkellogg/GaussianSplats3D/files/14531998/20240308_091335.zip)

**Comment by mkkellogg** [comment]
So it looks like PlayCanvas (and Luma for that matter) have a render mode where the render only occurs if something relevant has changed (camera position, camera orientation, etc.) I'm working on a similar feature is this branch: https://github.com/mkkellogg/GaussianSplats3D/tree/render_only_when_necessary. You can enable it with code like the following:

```
const viewer = new GaussianSplats3D.Viewer({
  'renderMode': GaussianSplats3D.RenderMode.OnChange
});
```

Let me know if that works for you.

**Comment by gotoeasy** [comment]
Yes, this is the effect I want, it's so cool!
