### ISSUE TITLE
Restrict user's mobile perspective

### ISSUE THREAD

**Issue by 2579024264** [mkkellogg/GaussianSplats3D#146]
hello~,How to limit the user's perspective to not exceed the internal space of the model? I don't want users to see external jagged edges when rotating and translating the perspective

**Comment by mkkellogg** [comment]
I admit the current implementation doesn't have a great way to control this, right now the logic is hard-coded here: https://github.com/mkkellogg/GaussianSplats3D/blob/6298b670db89359f660a7ca1f542c8b3ffcfc143/src/Viewer.js#L1472..L1473

The reason you see the jagged edges when rotating or translating is that the viewer doesn't render sections of the scene outside the view frustum.  You can play with the hard-coded `.6`  value, if you increase it, the viewer will render more of the scene outside the frustum. If you want to just render everything, you could do this:
```
const outOfFovY = false;
const outOfFovX = false;
```

**Comment by mkkellogg** [comment]
I'm going to close this for now, if you need more help please let me know!
