### ISSUE TITLE
About the reasons for not using SH

### ISSUE THREAD

**Issue by lxzbg** [mkkellogg/GaussianSplats3D#148]
This is a great project. I have some confusion about SH, why is SH discarded even though it is included in ply? Is it because of rendering speed considerations, or does GLSL not support view-dependent rendering? Could you share your thoughts?

**Comment by mkkellogg** [comment]
It's not so much about performance or rendering speed, it's really about the amount of memory required to store all the spherical harmonics data, both in the file and in memory.  The amount of memory required to store third-order spherical harmonics is around 200 bytes per splat, which is a lot :) Eventually I do plan on adding support, contingent on figuring out a good compression scheme, or a compromise where I only use the first few orders of spherical harmonics data.

**Comment by mkkellogg** [comment]
I'll close this for now, but I'll let you know when I eventually do add support for spherical harmonics

**Comment by lxzbg** [comment]
> I'll close this for now, but I'll let you know when I eventually do add support for spherical harmonics

Thank you for your reply and sharing

**Comment by lxzbg** [comment]
@mkkellogg hi, I tried to add 1st order SH myself to achieve view dependent lighting effects, but the result seems to be unchanged. I hope if you can help me check if there are any errors in the implementation. I'm not very familiar with js and GLSL, if you think it's appropriate I can further improve the code and submit it as a PR.

here is my code: https://github.com/mkkellogg/GaussianSplats3D/compare/dev...lxzbg:GaussianSplats3D:dev

**Comment by mkkellogg** [comment]
I'll try to take a look when I have a bit more time, but I don't think I'm ready yet to incorporate spherical harmonics into the viewer. I really want to make sure I have fully thought it through, and explore all options available for compressing spherical harmonics data when loading it into both host and GPU memory.

**Comment by lxzbg** [comment]
Thank you for your reply. I am not sure about the correctness of the SH coefficient passed into the shader through the texture map. I hope you can help me check it. 
In addition, I am very confused as to why the rendering on the web always has some dirty artifacts like black fog. Do you have any thoughts on this that you can share? As is the case in [this ](https://github.com/mkkellogg/GaussianSplats3D/discussions/174)

**Comment by vadim-v-lebedev** [comment]
There are two problems with this code:
First, you need to use camera position instead of sceneCenter here:
https://github.com/lxzbg/GaussianSplats3D/blob/f8120db5d18409663f53bb8f53da24b8ef353528/src/SplatMesh.js#L178
And second, something is wrong with I tried this code and found halfPrecisionCovariancesOnGPU option implementation for SH's. Apparently when it is on all SH params are zeros, and everything is ok when it is off.

**Comment by lxzbg** [comment]
> There are two problems with this code: First, you need to use camera position instead of sceneCenter here: https://github.com/lxzbg/GaussianSplats3D/blob/f8120db5d18409663f53bb8f53da24b8ef353528/src/SplatMesh.js#L178 And second, something is wrong with halfPrecisionCovariancesOnGPU option implementation for SH's. Apparently when it is on all SH params are zeros, and everything is ok when it is off.

Thanks for your help, I've [fixed the SH direction issue](https://github.com/lxzbg/GaussianSplats3D/commit/3f494d76db5af71cf72ede865b79153a83d5d92c), but still no difference in the results between w/wo. I am not sure about the correctness of the SH coefficient passed into the shader through the texture map. I hope you can help me check it.

Also, halfPrecisionCovariancesOnGPU option implementation for SH's I didn't actually implement, so it might be buggy

**Comment by vadim-v-lebedev** [comment]
I hope we'll be able to debug this! Half precision for SH is buggy so I turn it off here
https://github.com/lxzbg/GaussianSplats3D/blob/3f494d76db5af71cf72ede865b79153a83d5d92c/src/SplatMesh.js#L819
```
let SHDataType = Float32Array;
let SHTextureType = THREE.FloatType;
```
That fixed it for me and by fixed I mean now I do see some SH effect on my models but not the right kind of effect (I am using local viewer and polycam viewer as baselines). Maybe it is just the lack of higher orders

**Comment by lxzbg** [comment]
Thanks for reminding me, this is indeed a problem. I previously manually set `halfPrecisionCovariancesOnGPU = False`, but then I thought it was False by default, which caused this problem. I have now verified that SH does work.
