### ISSUE TITLE
Updated to the newest version from 2 to 3 and im unable to load a file which was loading before

### ISSUE THREAD

**Issue by lewibs** [mkkellogg/GaussianSplats3D#155]
Unhandled Runtime Error
Error: Viewer::addSplatScene -> Could not load file /assets/splats/gs_65b3ed7156ef6dc0a36cc28c.ply

Call Stack
eval
node_modules\@mkkellogg\gaussian-splats-3d\build\gaussian-splats-3d.module.js (8386:0)

was there something that changed that would cause this to occur? I`m looking at the demos and it seems nothing changed

**Comment by mkkellogg** [comment]
That's strange, you should still be able to load .ply files just fine.  Can you attach the file so I can debug it?

**Comment by lewibs** [comment]
Is there a difference in the demo you have deployed and the current version? The ply I'm using was able to be uploaded in there. I'm gonna test it with the demo splats in a sec.

**Comment by mkkellogg** [comment]
I think the demo version is `v0.3.1` and the current version is `v0.3.2`, but all that was added in `v0.3.2` was the ability to control when the viewer renders. For what it's worth I can load and view a `.ply` on the demo page at https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php

**Comment by mkkellogg** [comment]
Actually I now see the bug you've found. I published a fix to the `npm` repository, but `main` is currently still broken. I'll try to get that fixed soon as well.

**Comment by mkkellogg** [comment]
Ok the fix is in `main` now as well

**Comment by mkkellogg** [comment]
I'll close this for now, let me know if you run into trouble again.
