### ISSUE TITLE
DropInViewer loading and raycast issues with 3.x update

### ISSUE THREAD

**Issue by timothyallan** [mkkellogg/GaussianSplats3D#158]
Great work on this library!

I've run into a couple things after going from 2.3 to the 3.3 version. I'm using the following to add to my existing scene:
```
const viewer = new DropInViewer({ gpuAcceleratedSort: true, sharedMemoryForWorkers: false });
scene.add(viewer);
viewer.addSplatScene(path, {
            splatAlphaRemovalThreshold: 5,
            format: SceneFormat.Splat,
            showLoadingUI: false,
            showLoadingSpinner: false,
            onProgress: (progress: number) => {
              console.log(`splat loading ${progress}`);
            },
            streamView: true,
          })
```

Enabling the new `streamView` gives me this
![Screenshot 2024-03-15 at 2 28 18 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/5f3a1639-3e0f-43bb-94bf-d32056f24824)

where it looks like renderer is not defined:

![Screenshot 2024-03-15 at 2 28 33 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/4e5d373a-15c8-417d-97b6-2750233fef64)

and the splat doesn't load at all.

Disabling `streamView`does seem to load the Splat visually, the browser gives me:
![Screenshot 2024-03-15 at 2 26 27 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/14f456a0-34af-48df-b8e3-d7ad777bf5bd)

which is located here:

![Screenshot 2024-03-15 at 2 26 40 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/29bec962-077f-4924-96e4-9928865c9d20)

and then raycasting that did work in 2.3 doesn't work anymore as the splatTree comes back as null when I call `viewer.raycaster.intersectSplatMesh(viewer.splatMesh, outHits);`.

![Screenshot 2024-03-15 at 2 55 54 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/e47ec8f1-c1cf-4db0-96d1-b01aada6d083)

**Comment by mkkellogg** [comment]
This is quite strange, I can't seem to reproduce the issue using the latest in the `main` branch (which currently corresponds to `v0.3.3`).  Would you able to share all your test code and/or the `.splat` model you're testing with? Also, are you using the NPM package or pulling directly from this repo?

**Comment by timothyallan** [comment]
interesting! It's integrated into a rather large project at the moment, but I'll do some more digging and see if I can make a minimal repro. I'm using the npm `"@mkkellogg/gaussian-splats-3d": "^0.3.3",` fwiw

**Comment by mkkellogg** [comment]
FWIW I just did a clean install of `@mkkellogg/gaussian-splats-3d": "^0.3.3` and it works for `.splat` files I have locally. Would you be willing to share the `.splat` you're having trouble with?

**Comment by timothyallan** [comment]
Yep, I just did the uninstall/reinstall of the npm package as well. It's also not the `.splat` unfortunately. 

I borrowed `nike.splat` just now from here https://splats.vercel.app/ and it does the exact same thing as the other splats I've been mucking with. Will keep digging as it's obviously something sus on my end.

**Comment by timothyallan** [comment]
Okay, so did some stepping through and I see where you hook in to get the ref to the renderer now, in the `onBeforeRender`. I have a transition effect onLoad which renders another scene, then crossfades into the scene with the splat. The splat scene doesn't get a renderer tick until the crossfade is completed so the renderer ref is undefined and it all blows up.

**Comment by mkkellogg** [comment]
Yeah having a way to manually set the renderer might be a good idea, but I also think it should be more resilient to these kinds of situations instead of just crashing. I added a small change to the `support_compressed_ply_streaming` branch that I think does just that, would you be interested in testing it?

**Comment by timothyallan** [comment]
Back in business with those extra renderer checks on that branch! Nice one.

One niggly thing left :) I have a check that tests when the splat is done loading, and it was playing up. Traced it down to the onProgress jumping around, not sure if that's new or was there previously as well:
![Screenshot 2024-03-15 at 5 29 12 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/85f2fd89-be0d-49a8-b8cc-0eeaa1280164)

**Comment by mkkellogg** [comment]
The `onProgress` function actually takes 3 parameters: progress percentage as a number, progress percentage as a string, and then an instance of the `LoaderStatus` enum that indicates the operation being performed. The first entries are `LoaderStatus.Downloading`, and the last couple entries are `LoaderStatus.Processing` and `LoaderStatus.Done`. I think what you want to do is watch for when the progress percentage is 100 and the loader status is `LoaderStatus.Downloading`.

**Comment by timothyallan** [comment]
perfect, my dependance on TypeScript is showing :D

**Comment by mkkellogg** [comment]
Great! Glad that solved your issues. I'll close this one for now and hopefully I'll get `support_compressed_ply_streaming` merged into `main` and published soon.
