### ISSUE TITLE
how to select coordinate points in the Splat scene

### ISSUE THREAD

**Issue by lisongxiang10599** [mkkellogg/GaussianSplats3D#16]
There is an issue that has been bothering me, which is how to select coordinate points in the Splat scene through mouse clicks in order to conveniently add regular meshes to the scene. However, when I tried to implement it using the raycaster.intersectObjects() method, it didn’t work.

**Comment by mkkellogg** [comment]
Since the splat geometry is calculated in the vertex shader, a custom ray caster will be needed for this functionality. I do plan on writing one when I have time :)

**Comment by lisongxiang10599** [comment]
I will keep an eye on it and hope to complete it

**Comment by jvallsy** [comment]
I was trying the same! Will keep trying and share it if I reach the solution :) How where you thinking on developing it @mkkellogg ??

**Comment by mkkellogg** [comment]
I added a quick-and-dirty raycasting implementation. You can press `C` to display a mesh cursor that shows where your mouse cursor is projected onto the mesh. You can press `I` to toggle an info panel that shows the 3D coordinates of that mesh cursor.
