### ISSUE TITLE
ReferenceError: __publicField is not defined

### ISSUE THREAD

**Issue by jvandereijk** [mkkellogg/GaussianSplats3D#162]
Since updating from 0.2.3 to 0.3.4 earlier today I get this error message: 

ReferenceError: __publicField is not defined

The Splat still loads, but I can no longer turn on the cursor with 'c'   ('i' and 'p' for info still works)
The line is from a file called : blob:http://localhost:5173/097ca830-27f7-4651-a87b-4a897a8ed575:39

And the line wich causes the error seems to be generated on the fly by something, as it is not in the original code base as far as I can see

(function createSplatTreeWorker(self) {

...

__publicField(_WorkerSplatTreeNode, "idGen", 0);
let WorkerSplatTreeNode = _WorkerSplatTreeNode;

...

I just can't find out who or what generates this line, Maybe it has something to do with how webworkers operate ?

I thought I found a workaround by cloning and building the GaussianSplats3D repository directly and using that js instead of using npm install, which seems to work when I run my project locally, but when I build my project , the error is back, this time slightly different because it is uglified by my vite build progress.

I also tried previous 0.3.x version, they all have the same issue for me. I also created a small test project with minimal html/js example code, but with npm install / import. And it still throws the same error

I'm probably overlooking something, but does anyone else have a similar experience ?

(Btw, Thank you mkkellogg for building and sharing this repository, combining three.js with splats is reaaly powerfull and awesome :)

**Comment by jvandereijk** [comment]
Update: I'm pretty sure now, that it's my vite.js bundler causing troubles. And even though I didnt have the issue with 0.2.4, it probably has little/nothing to do with the gaussian-splat-3d code an sich. So feel free to close the issue if it doesnt ring a bell and you think it's not related.

**Comment by mkkellogg** [comment]
Someone else reported a similar issue with versions `0.3.0` - `0.3.3`, but I included a fix in `0.3.4`. If you want to post the scene you're testing with as well as the code you're using to debug, maybe I can troubleshoot it.

**Comment by gonzalle** [comment]
Same issue here...
Seems to me that when using the npm package it creates an other worker  :
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/1769103/370979e3-9d8f-4326-81f6-3245f7440fbc)
This worker has an orphan reference to __publicField

**Comment by mkkellogg** [comment]
Creating 2 workers means it's functioning properly -- it creates one worker for sorting splats, and another for computing the splat tree (which often takes several seconds).

**Comment by gonzalle** [comment]
I see... even if I don't understand why your demo works with one worker only (left console on my screenshot) , and the one on the right (with the two worker) doesn't work. 
Whatsoever, in the createSplatTreeWorker worker
line 39 :   __publicField(_WorkerSplatTreeNode, "idGen", 0);
there is an reference to __publicField that is not defined or resloved.
Thanks again Mark for the wonderful work and the progress on this repo !

**Comment by mkkellogg** [comment]
Would you be able to share the code you're using to load & run the viewer?

**Comment by jvandereijk** [comment]
I created a minimal project where you can see the issue: https://github.com/jvandereijk/splat
When you install and run the project you should see the 'ReferenceError: __publicField is not defined' error in the console. And pressing 'c' will not trigger showing the cursor.

In source/index/html you can swap the package import for a direct js import and then everything seems to works fine.

**Comment by gonzalle** [comment]
Idem for me :
here is a running sample with a model and the local server setup for Cross-Origin-Opener-Policy

just :
```
git clone https://gitlab.com/gonzalle/websplat.git
cd websplat
npm i
npm run dev
```

**Comment by jvandereijk** [comment]
I found [this ](https://github.com/evanw/esbuild/issues/1695) related conversation  where  the possible solutions where: use 'esnex't as build target or use typescript.

With some experimentation I fixed the issue in my project for now, by adding the following lines to vite.config.js

```
 optimizeDeps: {
    exclude: ['@mkkellogg/gaussian-splats-3d'],
  },
  build: {
    target: "es2022"
  },
```

The exclude fixes my issue when running locally, and the target: "es2022"  fixes it for production builds.
( es2021 still had the issue, but es2022 did not and is probably safer to use than esnext)

**Comment by gonzalle** [comment]
jvandereijk's solution also works for me so far.... 
Thanks a lot both !
Can't live witout Vite !

**Comment by mkkellogg** [comment]
Thanks for giving me the heads up on this issue, I have verified that if I just  make that static `idGen` variable a local variable in the `createSplatTreeWorker()` function, the build issue seems to go away. I'll include that update in the next release.

**Comment by mkkellogg** [comment]
I added a fix for this to the `dev` branch, anyone want to run a quick test with that branch to see if the error goes away?

**Comment by jvandereijk** [comment]
Do you know how can I test this easily ?  I tried: `npm install git://github.com/mkkellogg/GaussianSplats3D.git#dev`

But I get a lot of errors, probably since there are only 3 files in node_modules/@mkkellogg/gaussian-splats-3d 
Do I need to take some extra steps when installing an alternative branch through npm?

For the other issue I circumvented this problem by building your dev branche and copied the js to the test project, but in this case we need to check if the full npm flow works.

**Comment by mkkellogg** [comment]
I tested it by doing a fresh clone of the repo @gonzalle mentioned and installing all the default modules:
```
git clone https://gitlab.com/gonzalle/websplat.git
npm i
```
and then overwriting the contents of `node_modules/@mkkellogg/gaussian-splats-3d/build` with the build files from my local `dev` branch. Not exactly super easy, but it did make the error go away :)

**Comment by gonzalle** [comment]
happy to hear that... can't wait for the update !

**Comment by jvandereijk** [comment]
Yep, running and deployen works without issues using the js files from the dev branche in node_modules! vite.config additions no longer needed.

**Comment by mkkellogg** [comment]
The `npm` package has been updated with the fix for this, let me know if there are still any issues there.

**Comment by mkkellogg** [comment]
Closing for now, let me know if the latest `npm` package version still has the problem.
