### ISSUE TITLE
Enabling streaming seems to affect performance

### ISSUE THREAD

**Issue by murcje** [mkkellogg/GaussianSplats3D#163]
Hi, 
I would firstly like to thank you for your fine work! 🙇‍♂️ 

After enabling streaming [on this splat](https://voluma.mediamarc.nl/show/voluma/demo/dehaar_004) it seems that performance drops significantly.

On my desktop with a 3090 there is no difference, both run around 90 fps. I do notice it on mobile. I am using an S24 Ultra and the above splat is pushing the limits on what it can handle, and differences in performance become evident.

When I enable streaming [here](https://voluma.mediamarc.nl/show/voluma/demo/dehaar_004?streaming=true) on mobile, the framerate drops significantly. I cannot use the i key on mobile so it's all visual, but eyeballing it I think it's about 12 fps non-streaming (which is fine, I knew I was pushing it), and 2 fps with streaming enabled.

Any idea what could be causing this?

**Comment by mkkellogg** [comment]
When I load that link in Chrome on my laptop, I get pretty terrible performance as well (around 11 FPS). But when I download the splat and try to load it using my demo page, then I get pretty good performance in the same browser (around 60 FPS). Can you share some of the code you're using to load and view the splat?

**Comment by murcje** [comment]
Interesting! Do you notice any difference in performance between the two links?

I will provide some code tomorrow, bedtime here =]

Thanks!

**Comment by mkkellogg** [comment]
I get bad performance with both of the links above, for what it's worth.
