### ISSUE TITLE
Using a compressed .ply crashes my mobile browser, the .splat does not

### ISSUE THREAD

**Issue by murcje** [mkkellogg/GaussianSplats3D#164]
When on desktop and loading [this](https://voluma.mediamarc.nl/show/voluma/demo/dehaar_compressed) compressed .ply file I notice faster download times (of course the file is smaller), but nothing else is noticably different (good) as opposed to [this](https://voluma.mediamarc.nl/show/voluma/demo/dehaar_004) .splat file (derived from the same original .ply file). 

But on mobile, the compressed .ply will break the site (aw, snap), while the uncompressed .splat file loads fine.

Just spitballing here but could it be that, when uncompressed, the .ply file takes up more memory than the .splat file would?

**Comment by mkkellogg** [comment]
I forgot to update the code for the online demo with the latest release :) Does it work for you now?

**Comment by murcje** [comment]
Thanks for your fast reply. I think you misunderstood my issue. The examples on your demo page work beautifully. I was talking about the links in my post. I'll try some different splats tomorrow, could well be something on my side.
