### ISSUE TITLE
streamView false doesnt affect the loading method

### ISSUE THREAD

**Issue by pesa2000** [mkkellogg/GaussianSplats3D#166]
I am using the latest version of the package with this code snippet.

Am i doing something wrong?

```
this.viewer.addSplatScene(url, {
        'splatAlphaRemovalThreshold': 0,
        'streamView': false,
        'showLoadingUI': false,
        'position': [0, 2.3, 0],
        'rotation': [0, 0, 0, -0.5],
        'scale': [1, 1, 1]
      })
```

**Comment by mkkellogg** [comment]
You're code looks correct for disabling `streamView`, but `streamView` is actually disabled by default so you shouldn't need to specify `false` for that parameter. Was your intent to prevent progressive loading?

**Comment by pesa2000** [comment]
Hi, thank you for the fast reply, yes i would like to disable streamView since the splat file is relatevely small and fast to load.

**Comment by mkkellogg** [comment]
Ah, do you mean the "unveiling" effect where the scene is gradually revealed starting from the center? That currently will happen regardless of whether or not the scene is progressively loaded. When `streamView` is false, the reveal doesn't begin until the scene is completely downloaded. It sounds like I need to add an option to disable that effect :)

**Comment by pesa2000** [comment]
disabled*

**Comment by mkkellogg** [comment]
It wasn't actually part of older versions, I added it as part of the progressive loading feature mainly to make streaming `.ksplat` files look cooler. They're organized in chunks going from the center of the scene outward, so by default there was a "blockiness" to the effect of progressively loading them. To combat that I added an effect that gradually reveals scene at a slower pace than the scene is loaded, which looked much nicer :) However it doesn't really sense to have that effect if you're not loading a `.ksplat`, or if the file is not being progressively loaded, so I will add an option to disable it.

**Comment by pesa2000** [comment]
Perfect, thank you very much for the explanation and for the fast reply!

I will wait the update. 

Have a great day!

**Comment by mkkellogg** [comment]
I pushed an update to the `dev` branch which includes the option to control the fade-in effect. If you want to have an instant fade in, you can do:
```
const viewer = new GaussianSplats3D.Viewer({
    'sceneRevealMode': GaussianSplats3D.SceneRevealMode.Instant
});
```

I'll get the changes into the next release, which should go out soon :)

**Comment by pesa2000** [comment]
Thank very much, i really appreciate it.

Have a good day!

**Comment by mkkellogg** [comment]
the `main` branch and `npm` package now have the update, let me know if it works for you :)

**Comment by mkkellogg** [comment]
Going to close this for now, let me know if anything else comes up.
