### ISSUE TITLE
null SplatTree preventing Raycaster from working.

### ISSUE THREAD

**Issue by tansh-kwa** [mkkellogg/GaussianSplats3D#168]
Very smooth integrating in this library!

One issue I'm running into is getting the provided raycaster to work correctly with my scene. I'm adding the viewer as shown below, and attempting to call the raycaster, however, it's not providing any `outHits.` Digging into this, I found that the `splatTree` is null within the viewer's `splatMesh.` Is there an explicit call to instantiate the splatTree? or is there a step I am missing. I'll add that the raycaster tools are working as expected with the demo viewer hosted here: 

How i'm adding the viewer to my own scene:
```javascript
const viewer = new GaussianSplats3D.Viewer({
    'selfDrivenMode': false,
    'renderer': renderer,
    'camera': camera,
    'useBuiltInControls': false,
    'ignoreDevicePixelRatio': false,
    'gpuAcceleratedSort': true,
    'halfPrecisionCovariancesOnGPU': true,
    'sharedMemoryForWorkers': true,
    'integerBasedSort': true,
    'dynamicScene': false,
    'webXRMode': GaussianSplats3D.WebXRMode.None,
    'renderMode': GaussianSplats3D.RenderMode.OnChange
});
viewer.addSplatScene('splats/demo.ply')
.then(() => {
    requestAnimationFrame(update);
});
```

**Comment by mkkellogg** [comment]
Could you post all of your setup code? I am unable to reproduce the issue with just what you have posted above.

**Comment by mkkellogg** [comment]
Your example code works for me, the raycaster is returning valid hits:
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/6249005/e473837c-cbe6-4b48-9ba9-8d173f3f66b7)

Are you making sure to wait until the "Optimizing Splats" dialog box goes away? The splat tree is getting built while that dialog is visible, and it doesn't start getting built until after the scene is loaded.

**Comment by mkkellogg** [comment]
Ah, Vite strikes again! I have a fix for that issue that will go out in the next release :)
