### ISSUE TITLE
How to add a skybox effect

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#171]
How to add a skybox effect, similar to what Luma does?

**Comment by mkkellogg** [comment]
Currently there's not a built-in way to do that; you'd have to do something like render the scene from a given location in all 6 directions needed for skybox (-X, +X, -Y, +Y, -Z, +Z) and make sure the rendering is done to a cube texture. But Luma also does some fancy generative AI stuff to fill in the holes, smooth the background, and I think remove stuff from the foreground as well.

**Comment by gotoeasy** [comment]
Thank you for your response!
