### ISSUE TITLE
How can the zooming range be controlled?

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#181]
Zooming in too much results in extreme blurriness, while zooming out too far makes it difficult to see, both of which are not meaningful.

How can the zooming range be controlled?

**Comment by mkkellogg** [comment]
You'd have to set the relevant properties on `Viewer.controls` : 
```
viewer.controls.maxDistance = maxDistance;
viewer.controls.minDistance = minDistance;
```
Maybe I should add `Viewer` parameters for this :)

FYI I've got a PR up to enable orthographic projection  that changes `viewer.controls` to point to one of `viewer.orthographicControls` or `viewer.perspectiveControls` so the above method won't quite work correctly; you'd have to change the min and max distance on both sets of controls.
