### ISSUE TITLE
Any ideas on how to integrate cameras.json into the gausiansplats3d?

### ISSUE THREAD

**Issue by hazy-sky** [mkkellogg/GaussianSplats3D#182]
Thank you @mkkellogg for this project. I have been trying to apply the cameras.json camera properties to the perspective cameras but I have been failing. SetRotationFromMatrix(Mat4(rotation)) + SetPosition doesn't seem to be working.

**Comment by koktavy** [comment]
@hazy-sky did you figure this out? Anything you could share back to the repo?

**Comment by pkq111** [comment]
我之前尝试做这件事情，发现我的相机朝向不正确，现在也没能解决
