### ISSUE TITLE
Online demo page not up to date

### ISSUE THREAD

**Issue by fasteinke** [mkkellogg/GaussianSplats3D#192]
Minor thing ... online demo page key help not updated with new 'U' and 'P' usage.

**Comment by mkkellogg** [comment]
Thanks for the heads up! The online demo page should be updated now, and I pushed updates for the local demo page to the `dev` branch.

**Comment by fasteinke** [comment]
Nicely done ... only thing, when I select orthographic mode the displayed splats disappear and distort as I get closer - only works from a distance.

**Comment by mkkellogg** [comment]
Hmm, that shouldn't happen. I've tested on all major browsers and operating systems and it has worked so far. What OS & browser are you using?

**Comment by fasteinke** [comment]
Okay, it seems to be about the sequence of actions prior to selecting orthographic. On Windows 10, just tried Chrome, and all seemed fine. Then went back to my normal Firefox 124.0.2, and a window that had been up a while, and running fine, just lost all splats when O input. Went backwards, and reloaded same ply - and now it works correctly, in orthographic!

So, not yet clear what the trigger is, for buggy behaviour - will try and find a sequence that consistently makes it happen ...

**Comment by fasteinke** [comment]
Okay, a few more clues ... the spalts don't disappear, but the coordinate system loses the plot; the model is still there. but you have to hunt for where it is. Plus, there are now 'ghost' models, the main subject has versions of itself completely askew from the 'main' one - if the latter exists.

**Comment by mkkellogg** [comment]
Are you just using the demo page or are you using some of your own code to run the viewer? If it's your own code and you want to post it here, maybe I can debug it.

**Comment by fasteinke** [comment]
Purely the demo page ... I've refresh it regularly, just in case. So far, the only common thread seems to be that the page has been left on a tab showing a local ply file for some time, hours say, and one of the first operations on then bringing that tab back in focus is to try orthographic. If I select a file to view, and then try all sorts of operations without moving off that page, the O key always works.

**Comment by fasteinke** [comment]
The demo page has been working fine since I last posted - toggling orthogonal has always behaved itself. But today it acted up again: the machine was hibernating, woke it up, had two ply files active in separate tabs; essentially the same model in each. Out of curiosity tried the O key - one tab was fine; the other sent the model to a completely different set of coordinates.

Was it a bug in the browser? No idea - forget about it unless somebody else has this behaviour??

**Comment by mkkellogg** [comment]
I have actually noticed something similar over the past few weeks. It happens very rarely and I can never reproduce it -- basically when I hit the `O` key the camera jumps to some random location far away. I don't think it's a bug with the browser, but based on what's in the code, what is happening doesn't make any sense to me. If you can figure out a way to reproduce it, that would be super helpful!

**Comment by mkkellogg** [comment]
Just circling back to this issue, are you still seeing this happen?

**Comment by fasteinke** [comment]
Haven't been looking for it lately - I don't require orthogonal viewing, so only found it when I saw that feature introduced, and tried it. That said, just gave the viewer a solid workout before, with a few models, testing the O key - and it always behaved.

Do you think you may changed something that has relevance to the issue?

**Comment by mkkellogg** [comment]
It's certainly possible that I unintentionally fixed what ever the issue was through some other update. I'll close this issue for now, but let me know if you notice any weird behavior again.
