### ISSUE TITLE
error ，need help

### ISSUE THREAD

**Issue by jaccen** [mkkellogg/GaussianSplats3D#20]
npm run build

> gaussian-splat-3d@1.0.0 build
> npm run build-library && npm run build-demo

> gaussian-splat-3d@1.0.0 build-library
> npx rollup -c && mkdir -p ./build/demo/lib && cp ./build/gaussian-splat-3d* ./build/demo/lib/

./src/index.js → ./build/gaussian-splat-3d.umd.cjs...
created ./build/gaussian-splat-3d.umd.cjs in 124ms

./src/index.js → ./build/gaussian-splat-3d.module.js...
created ./build/gaussian-splat-3d.module.js in 64ms
命令语法不正确。

**Comment by mkkellogg** [comment]
It seems like it is working correctly to me?

**Comment by jaccen** [comment]
this dir ：GaussianSplats3D
npm install
and then 
npm run build
there is the error

--------------------------------------

npm run demo

**Comment by fujiazhiyu** [comment]
you ran it on a windows powershell? It would output like this.
If so, change the `&&` into `;` and manually run the command but not `npm run build`.

**Comment by mkkellogg** [comment]
I apologize if you're running into Windows issues, I haven't really tested on that OS. I just updated `package.json` with a `build-windows` command, so you should be able to run:
```
npm run build-windows
```

**Comment by jaccen** [comment]
Tanks a lot！ works ok
