### ISSUE TITLE
Low Performance Mobile

### ISSUE THREAD

**Issue by lucarinaldii** [mkkellogg/GaussianSplats3D#204]
Hi Mark, I am using your viewer for some splat scenes to render from mobile (4mb per scene or so). The thing I notice is a drop in device performance (safari on iphone 14 pro) and it seems very strange to me. Your tests with much larger scenes like this https://projects.markkellogg.org/threejs/gaussian_splats_3d_demos/truck.html
seem to give no performance drop on the same device. Are some mobile device performance features coming?

Thank you very much for your great work.

**Comment by mkkellogg** [comment]
Would you be able to post the scene you are trying to load as well as the code you're using to set up the viewer? Maybe I can help troubleshoot.

**Comment by lucarinaldii** [comment]
Hi Mark, I found out the problem: was about the Pixel Ratio that was over the device capabilities. The thing is that is different in some kinds of mobile devices.. think there could be an effective way to control o set a max device performance value?

**Comment by mkkellogg** [comment]
There is a setting for the `Viewer` class that tells it to pretend the `devicePixelRatio` is 1: `ignoreDevicePixelRatio`. This could help with performance, but the visual quality may suffer a little. You'd set it like so:
```
const viewer = new GaussianSplats3D.Viewer({
   ...
   'ignoreDevicePixelRatio': true
   ...
});
```

**Comment by mkkellogg** [comment]
Just checking in... did this issue get resolved?

**Comment by mkkellogg** [comment]
Closing for now, please let me know if you need more help with this.
