### ISSUE TITLE
Occlusion Culling

### ISSUE THREAD

**Issue by abrahamezzeddine** [mkkellogg/GaussianSplats3D#208]
Hello

Any plan to implement occlusion culling in order to speed up the rendering process with integrated graphics cards? 

Frustum Culling is enabled by standard with three.js but occlusion culling does not exist, does it not?

Any thoughts about this? Thank you.

**Comment by mkkellogg** [comment]
I don't have any immediate plans to implement something like occlusion culling, mainly because it would be a significant amount of work and there are other higher priority features I'd like to implement :)

**Comment by abrahamezzeddine** [comment]
Alright. I understand. 

In theory, do you believe this would significantly increase performance of the rendering?

**Comment by mkkellogg** [comment]
Yes I believe there could a be significant performance benefits for some scenes. The major problem is that hardware accelerated occlusion culling requires usage of the depth buffer, which is not used for rendering splats (and there isn't really a great way to get depth information from rendering splats). So occlusion culling for gaussian splatting would have to be achieved through custom data structures and a manual process of identifying which portions of a scene are visible from other portions, and it would all need to be baked into a scene prior to viewing it.
