### ISSUE TITLE
Working on adding Spherical Harmonics, works good on manually upload file, but has bug when using Demo scenes.

### ISSUE THREAD

**Issue by c4488she** [mkkellogg/GaussianSplats3D#209]
Hi, I am currently working on rendering with Spherical Harmonics, and It works well when I use "Choose File" button and view.
But when I add my own .ply with 48 SH coefficient to demo scenes (those with trucks, bonsai ), it broke. I am not sure which part is wrong but I think it could be the issue of "loadFromURL( )" function. Could you take a look to my code and find how to fix it?

I am not sure how to provide my code, shoud I ZIP it?

**Comment by mkkellogg** [comment]
Would you be able to make your github repo accessible to me? Otherwise you can zip it.

**Comment by c4488she** [comment]
Sure, here is my repo https://github.com/c4488she/3D-GS-Viewer
I changed the model of "truck" at demo scene for testing.

Below is the link of my .ply
https://drive.google.com/drive/folders/1yLlWIe-io9h2WVDMSLaOWE5-r2TE8nOP?usp=sharing

Thanks!

**Comment by mkkellogg** [comment]
I was able to add your `.ply` file to the Bonsai demo scene just fine:
```
import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';
import * as THREE from 'three';
const viewer = new GaussianSplats3D.Viewer({
    'cameraUp': [0.01933, -0.75830, -0.65161],
    'initialCameraPosition': [1.54163, 2.68515, -6.37228],
    'initialCameraLookAt': [0.45622, 1.95338, 1.51278],
});
path= "assets/data/bonsai/nctu-small-ns.ply";
viewer.addSplatScene(path, {
  'streamView': true
})
.then(() => {
    viewer.start();
}
```
What kind of error are you seeing?

**Comment by c4488she** [comment]
SplatBuffer.js:270 
 Uncaught TypeError: Cannot read properties of undefined (reading 'splatCountOffset')
    at SplatBuffer.fillSplatCovarianceArray (SplatBuffer.js:270:49)
    at SplatMesh.fillSplatDataArrays (SplatMesh.js:1891:29)
    at SplatMesh.uploadSplatDataToTextures (SplatMesh.js:1153:18)
    at SplatMesh.refreshGPUDataFromSplatBuffers (SplatMesh.js:970:14)
    at SplatMesh.build (SplatMesh.js:820:40)
    at Viewer.addSplatBuffersToMesh (Viewer.js:1037:31)
    at Viewer.js:977:51
    at Util.js:144:21
    
   ----------------------------------------------------------
   
   
   And the Viewer would look like this
   
![Screenshot 2024-04-20 004115](https://github.com/mkkellogg/GaussianSplats3D/assets/90664931/882020df-7506-488e-a9c1-7a0307f81d26)

**Comment by mkkellogg** [comment]
So the problem is somewhere in the progressive loading functionality. When I make sure to set `streamView` to `false` when loading a scene it works. However, if I set it to `true`, I see the error that you see. So you can either disable progressive loading, or if you really want to you can update the progressive loading feature to support the additional SH fields :)

**Comment by c4488she** [comment]
Okay, maybe I would look into it in the future, thanks!

**Comment by hecodeit** [comment]
@c4488she Can not find your repo?
