### ISSUE TITLE
Not rendering local host

### ISSUE THREAD

**Issue by brycelynch** [mkkellogg/GaussianSplats3D#21]
After:

npm run demo

I get:

Server running at 127.0.0.1:8080

-----------------------------------------------
HTTP(500)) Request for ./build/demo/ -> Server error.
HTTP(404) Request for ./build/demo/favicon.ico -> File not found.

When I navigate to local host URL it says this:

Sorry, check with the site admin for error: EISDIR ..

When I used SERVEZ running locally I get the index page to load but the links to the three example pages don't load splats.  

I have demo data installed here: 

GaussianSplats3D-main\build\demo\assets\data

\garden
\stump
\truck

All three directories have associated splat files.

Any ideas what I might be doing wrong?

**Comment by brycelynch** [comment]
My bad... I had didn't have it installed in the correct directory.   Have it working now via 127.0.0.1:8080  and it works as expected. 

However, I have another related question... I'm using SERVEZ to host that directory to a Quest that is running on my local network.  I can see the index.html file just fine... the links to images work, which take me to the loading animation screen... but it never renders in the Quest browser.  I've run other three.js pages this way, does it have something to do with the loader?  Any ideas I could try?

**Comment by mkkellogg** [comment]
I've never actually tried running any three.js or WebGL apps on a Quest device, so I'm not quite sure how to start troubleshooting. My first thought is to look at whatever might be in the debug console -- you'll need to set up remote debugging as described here: https://discourse.threejs.org/t/debugging-threejs-vr-on-oculus-quest-2/21561. Let me know what you see there and that might point me in the right direction.

**Comment by brycelynch** [comment]
I should also add that it's not a quest browser issue, Chrome on the local machine that works using your server setup doesn't get past the loading animation either.

**Comment by brycelynch** [comment]
Also Servez logs show all the same requests that your server shows.  So it seems like it's working, it gets the .splat request but never fulfills.  Doesn't error on anything.

**Comment by mkkellogg** [comment]
So I'm guessing the issue you're running into has to do with the use of `SharedArrayBuffer` in Javascript (Which this app does use).  If you see an error like this in the debug console then that is the issue: 

```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated
```
There's a potential security issue around it, so the server needs to set some special headers. Try this:
```
npx servez --ssl ./build/demo/ --header=Cross-Origin-Opener-Policy:same-origin --header=Cross-Origin-Embedder-Policy:require-corp 
```

**Comment by brycelynch** [comment]
I'm running the gui.  But I'll see about installing Cli version. Appreciate you trying to sort this out.  Will report back to you with results.  :)

**Comment by brycelynch** [comment]
That worked!  Thanks!  Great GS implementation, thanks for sharing this!  :)

**Comment by mkkellogg** [comment]
Glad to hear it! I should probably put something in the README about those headers...

**Comment by brycelynch** [comment]
Unrelated to my previous post.. I have everything work now.  Thanks!

I have a question about the proper way to add a box mesh to the splat scene.  Following along with your description, I can't see to get the box to render.  Just the splat .  This is the code I'm using:


`<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>3D Gaussian Splat Demo - Garden</title>
  <script type="importmap">
    {
        "imports": {
            "three": "./lib/three.module.js",
            "gaussian-splat-3d": "./lib/gaussian-splat-3d.module.js"
        }
    }
  </script>
  <style>

    body {
      background-color: #000000;
      height: 100vh;
    }

  </style>

</head>

<body>

<script type="module">

    import * as THREE from 'three';

    const scene = new THREE.Scene();

    const boxColor = 0xBBBBBB;
    const boxGeometry = new THREE.BoxGeometry(2, 2, 2);
    const boxMesh = new THREE.Mesh(boxGeometry, new THREE.MeshBasicMaterial({'color': boxColor}));
    scene.add(boxMesh);
    boxMesh.position.set(3, 2, 2);

    import * as GaussianSplat3D from 'gaussian-splat-3d';
    const viewer = new GaussianSplat3D.Viewer({
    'cameraUp': [0, -1, -0.6],    
    'initialCameraPosition': [-1, -4, 6],
    'initialCameraLookAt': [-.2, 1.4, 0.6],
    'splatAlphaRemovalThreshold': 20
    });
    viewer.init();
    viewer.loadFile('assets/data/garden/garden.splat')
    .then(() => {
        viewer.start();
    });

</script>
  `

**Comment by mkkellogg** [comment]
It looks like you're forgetting to pass the `scene` parameter to the viewer :) Try this:
```
const viewer = new GaussianSplat3D.Viewer({
    'scene': scene,
    'cameraUp': [0, -1, -0.6],    
    'initialCameraPosition': [-1, -4, 6],
    'initialCameraLookAt': [-.2, 1.4, 0.6],
    'splatAlphaRemovalThreshold': 20
});
```

**Comment by brycelynch** [comment]
sorry... missed adding scene to viewer.  working now!  :)

**Comment by brycelynch** [comment]
I've merged in the threejs AR example code to see what would happen if I render this in XR...  Using these settings:

```
    const viewer = new GaussianSplat3D.Viewer({
        'selfDrivenMode': false,
        'renderer': renderer,
        'camera': camera,
        'useBuiltInControls': false
    });
```

I know this is out of scope of your solution, but do you have any idea if your gsplat viewer would work in three js XR mode?  Seems like it would work, I don't get any errors when I run this, I just don't get the splat to render before going into AR (via button press) or in AR rendering mode.  I'm using a 25mb splat file that works in a normal set up so I've validated that it works correclty.  

This  is what I'm trying to do.... does anything stick out at you as a blocker?

```

<!DOCTYPE html>
<html lang="en">
	<head>
		<title>XR Splat</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

        <style>

            body {
              background-color: #000000;
              height: 100vh;
            }
        
          </style>
        
	</head>

	<body>

		<script type="importmap">

//I've added jsm addons here:
            {
                "imports": {
                    "three": "./lib/three.module.js",
                    "gaussian-splat-3d": "./lib/gaussian-splat-3d.module.js",
                    "three/addons/": "./lib/jsm/"  
                }
            }

		</script>

		<script type="module">

			import * as THREE from 'three';
			import { ARButton } from 'three/addons/webxr/ARButton.js';
                        import * as GaussianSplat3D from 'gaussian-splat-3d';

			let camera, scene, renderer;
			let controller;

			init();
			animate();

			function init() {

				const container = document.createElement( 'div' );
				document.body.appendChild( container );

				scene = new THREE.Scene();

				camera = new THREE.PerspectiveCamera( 70, window.innerWidth / window.innerHeight, 0.01, 20 );

				const light = new THREE.HemisphereLight( 0xffffff, 0xbbbbff, 1 );
				light.position.set( 0.5, 1, 0.25 );
				scene.add( light );

				//

				renderer = new THREE.WebGLRenderer( { antialias: true, alpha: true } );
				renderer.setPixelRatio( window.devicePixelRatio );
				renderer.setSize( window.innerWidth, window.innerHeight );
				renderer.xr.enabled = true;
				container.appendChild( renderer.domElement );

				//

				document.body.appendChild( ARButton.createButton( renderer ) );

				//



                const viewer = new GaussianSplat3D.Viewer({
                    'selfDrivenMode': false,
                    'renderer': renderer,
                    'camera': camera,
                    'useBuiltInControls': false
                });

                viewer.init();
                // viewer.loadFile('<path to .ply or .splat file>')
                viewer.loadFile('assets/data/gnome/30k/data-gnome-30k-point_cloud-edit.ply')
                .then(() => {
                requestAnimationFrame(update);

                });

                function update() {
                requestAnimationFrame(update);
                viewer.update();
                viewer.render();
                }
                
                //

				const geometry = new THREE.CylinderGeometry( 0, 0.05, 0.2, 32 ).rotateX( Math.PI / 2 );


				function onSelect() {

					const material = new THREE.MeshPhongMaterial( { color: 0xffffff * Math.random() } );
					const mesh = new THREE.Mesh( geometry, material );
					mesh.position.set( 0, 0, - 0.3 ).applyMatrix4( controller.matrixWorld );
					mesh.quaternion.setFromRotationMatrix( controller.matrixWorld );
					scene.add( mesh );



				}

				controller = renderer.xr.getController( 0 );
				controller.addEventListener( 'select', onSelect );
				scene.add( controller );

				//

				window.addEventListener( 'resize', onWindowResize );

			}

			function onWindowResize() {

				camera.aspect = window.innerWidth / window.innerHeight;
				camera.updateProjectionMatrix();

				renderer.setSize( window.innerWidth, window.innerHeight );

			}

			//

			function animate() {

				renderer.setAnimationLoop( render );

			}

			function render() {

				renderer.render( scene, camera );

			}

		</script>
	</body>
</html>


```

**Comment by brycelynch** [comment]
I realized I was missing scene reference again... fix that which allows me to render a boxMesh before and during AR setup.  But still haven't sorted if/why I can't render splat.  Will keep working on it. ;)

**Comment by mkkellogg** [comment]
One thing that immediately sticks out to me is you seem to have 2 animation loops. You have `update()` which calls `Viewer.update()` and `Viewer.render()`, but then you have your own `render()` function that calls `renderer.render()`, which would clear anything that's already been rendered. Try eliminating your `render()` function and see if that helps.

**Comment by brycelynch** [comment]
Ok.  Will look at that.  

I just realized It is rendering in some capacity.  It's just rendering some weird position/rotation.  I put a cube out in front of me.  When I go into AR... I and turn my head around 180 degrees and look up and exit AR my browsers should the splat.  So I know it's rendering... just need to figure out how to align it to world origin in someway that I understand, or relative to the cube that I can control.

Before AR:
![IMG_3565](https://github.com/mkkellogg/GaussianSplats3D/assets/8460470/8927b65e-7e77-4325-8a21-e92550e32e45)
AR:
![IMG_3564](https://github.com/mkkellogg/GaussianSplats3D/assets/8460470/a3969b8d-1918-41d7-acb4-5b7b7da35176)
Rotating Head:
![IMG_3563](https://github.com/mkkellogg/GaussianSplats3D/assets/8460470/71e8c5cd-1563-485f-b692-851012293261):
After Exit:
![IMG_3562](https://github.com/mkkellogg/GaussianSplats3D/assets/8460470/5c37ee95-4a4e-47bc-9ae1-72c22de36ef1)

**Comment by brycelynch** [comment]
Maybe its a field of view issue?

**Comment by mkkellogg** [comment]
I'm not exactly sure what might be happening, it looks like three.js uses a special internal camera when rendering AR/VR so that might have something to do with it:
https://github.com/mrdoob/three.js/blob/9e29fbb6548af97343c56e69da992d36f0607763/src/renderers/WebGLRenderer.js#L1156
Also you may have to play with the `cameraUp` parameter to the viewer to get things oriented correctly, although that may not actually have an effect if three.js is using its own camera.
We're definitely getting close to the limits of my ability to troubleshoot this one :) I may have to get a headset of my own to play around with.

**Comment by brycelynch** [comment]
Ha.  No worries!  I feel down a rabbit hole and was just looking for the exit.  Totally understand.  That's helpful though, I was thinking that it might have something to do with the negative scale of world up in the camera.  I'll see about overriding that (if possible) in the XR camera.  I'll keep digging around,

One last thing I realized is that I'm actually spawning into AR at the world origin (my headset it 0,0,0, which happens to be where my splat is situated.  When I actually physically get up and move across the room and exit AR I can see  both my cube and the splat.  I enabled  your builtincontrols and after I exit (not before for some reason) I can orbit the scene and am able to understand the relationship from my cube to the splat.  If you imagine it in world space, I'm actually sitting in the gnomes face (which is upside down on my head) and I'm  looking directly at the cube.  Oh, well... getting closer.  ;)

**Comment by brycelynch** [comment]
![IMG_3566](https://github.com/mkkellogg/GaussianSplats3D/assets/8460470/cd5986cc-248e-418a-a7dd-0defb53978fc)

**Comment by mkkellogg** [comment]
I'd bet what we''ll need to do is something like passing the three.js XR camera as the `camera` parameter to the `Viewer` constructor:
```
const viewer = new GaussianSplat3D.Viewer({
      'selfDrivenMode': false,
      'renderer': renderer,
      'camera':  renderer.xr.getCamera(),
      'useBuiltInControls': false
});
```
That will not currently work because the XR camera is a three.js `ArrayCamera` and my viewer doesn't know what that is :) It should be easy to update the `Viewer` class to check if the camera is an `ArrayCamera` and then it can pull things like the FOV, focal length, projection matrix, etc. from the first camera in the array.

**Comment by brycelynch** [comment]
I love speculating.   :) 

Conceptually, I understand what you are suggesting.  I've looked in the xr webmanager at the xr camera setup and it's beefy but I'm sure there is a way to change the up vector but not sure what/if anything that will break.... I know that they've taken a specific approach to unify where/how VR/AR headsets spawn at world/origin to match player height/location and that controllers somehow (as children?) follow this so they render in the right place.  I can try experimenting with that, but not confident I'll be able to make that work at my skill level.  

Makes sense to  set   'camera':  renderer.xr.getCamera() and I understand there is a way in your viewer class  (which I just looked at) to check for it but not currently sure how to go about that.  I'll keep looking at it to see if I can make sense of it.  

I *think* I'm starting to have a clearer picture that currently the xr camera and the splat viewer are in to two different spaces and that your viewer can be set to control a scene camera and that's why we can add geometry to your viewer/scene....  but there is no way for a scene camera (in this case xr) to control the position/rotation of the viewer (where the splat renders)? 

Sorry I'm pulling you into this conversation.  Feel free to throw your hands up and bail anytime.  I won't take it personally.  ;)

Thanks Mark.

**Comment by brycelynch** [comment]
FYI... This is where I ended up, before changing the viewer camera to the xr camera:

https://youtu.be/ZzDOBmYaU64

**Comment by mkkellogg** [comment]
I'm happy to continue trying to help, I'm just not sure how constructive I am being at this point :) 

I dug through the `WebXRManager` code a bit more as well and you're right about how the XR camera is managed internally in such a way that customizing its orientation, up-vector or anything else directly will be problematic. It does look like the three.js developers added a way to deal with the XR space not matching the physical space you're trying to view though. 

They have an example here that showcases how to change the XR reference space: https://github.com/mrdoob/three.js/blob/master/examples/webxr_vr_teleport.html. The specific lines of interest start at 102:

```
const offsetPosition = { x: - INTERSECTION.x, y: - INTERSECTION.y, z: - INTERSECTION.z, w: 1 };
const offsetRotation = new THREE.Quaternion();
const transform = new XRRigidTransform( offsetPosition, offsetRotation );
const teleportSpaceOffset = baseReferenceSpace.getOffsetReferenceSpace( transform );

renderer.xr.setReferenceSpace( teleportSpaceOffset );
```

I think what you'd need to do is calculate the correct `XRRigidTransform`, and then calculate the delta between the XR camera's default reference frame and your calculated frame (via the `getOffsetReferenceSpace()` function) and then apply that final transformation via `setReferenceSpace()`.

Every splat scene / point cloud will have its own custom reference frame, that's why I added the `cameraUp` parameter to the `Viewer`. It was a super quick fix -- the alternative was altering the position & orientation of all the splats in the scene to be aligned with the default world frame in three.js. For the scenes I included in my demo, I think you should be able to derive a reference frame transformation based on the `cameraUp` for each scene -- essentially you'd need a transformation that rotates the default camera up `<0, 1, 0>` to the scene's camera up.

Of course that's all theoretical at this point, I find that in reality these kinds of things always turn out to be more complicated

**Comment by brycelynch** [comment]
Ha... so true.  I always imagine things to be way simpler than reality... I guess that's what get me invested.  ;)

Thanks for this info.  I'll digest this and see what I can come up with.  :)
