### ISSUE TITLE
I want to do a point-to-point measurement function, I would like to ask whether the function is possible to achieve.

### ISSUE THREAD

**Issue by chaoyang915506** [mkkellogg/GaussianSplats3D#215]
I want to do a point-to-point measurement function, I would like to ask whether the function is possible to achieve.
Can be realized if there is no recommended direction

**Comment by mkkellogg** [comment]
Sorry for the late response, how did you want to achieve the measurement? You could certainly use the built-in ray caster to get the 3D position (as a Three.js vector) of splats under the cursor and then use three.js functionality to calculate the distance between them. Would that work?

**Comment by JeS24** [comment]
@chaoyang915506 If you want to do this outside of writing JS code, you can open the GS `.ply` files in  [CloudCompare](https://www.danielgm.net/cc/) and compute cloud-to-cloud/mesh distances, perform change detection, or calculate other statistical quantities. There is also this converter -- https://github.com/francescofugazzi/3dgsconverter to convert the GS `.ply` files into CC-compatible point clouds, although it usually strips the color information (even with the `--rgb` flag).

**Comment by chaoyang915506** [comment]
> 抱歉回复晚了，您想如何实现测量？您当然可以使用内置的光线投射器来获取光标下的 splats 的 3D 位置（作为 Three.js 向量），然后使用 Three.js 功能来计算它们之间的距离。那行得通吗？



> Sorry for the late response, how did you want to achieve the measurement? You could certainly use the built-in ray caster to get the 3D position (as a Three.js vector) of splats under the cursor and then use three.js functionality to calculate the distance between them. Would that work?

Ok, thank you very much. May I ask what the splatIndex in the ray collision point stands for? The quality of my Gaussian file is not very good, and the situation of clicking into the air may occur. Besides optimizing the Gaussian file, is there any other way to recommend it?

**Comment by mkkellogg** [comment]
You probably don't need to worry about `splatIndex`, that just tells you the relative order of the splat within the file from which the splats were loaded. I mainly have it there for debugging purposes :)

**Comment by chaoyang915506** [comment]
> You probably don't need to worry about `splatIndex`, that just tells you the relative order of the splat within the file from which the splats were loaded. I mainly have it there for debugging purposes :)

I want to know how the splatIndex field relates to the raw data in my Gaussian file. This allows you to filter out some of the noise generated in the file when you click on the ray.

**Comment by seppestaes** [comment]
@mkkellogg : Please keep the splatIndex in there :)

**Comment by mkkellogg** [comment]
I will definitely keep `splatIndex` in there :) Is this issue resolved now?

**Comment by mkkellogg** [comment]
I'm going to close this one for now, let me know if you have any further trouble!

**Comment by seppestaes** [comment]
Didn't have an issue, just responded to the splatIndex. Thx for keeping it in there :)

**Comment by gotoeasy** [comment]
> I want to do a point-to-point measurement function, I would like to ask whether the function is possible to achieve. Can be realized if there is no recommended direction

https://github.com/reall3d-com/Reall3dViewer
