### ISSUE TITLE
Dropin-viewer rotation

### ISSUE THREAD

**Issue by wakufactory** [mkkellogg/GaussianSplats3D#217]
When using Dropin-viewer, if rotate the viewer's parent three.js object,
it will display the object's front side inside out.
If move the viewpoint, it will return to normal.
Is there a solution?

The video is here.
https://twitter.com/wakufactory/status/1784771134933897594

**Comment by mkkellogg** [comment]
Thanks for the heads up on this, it looks like it's due to a small bug in my viewer. Currently the viewer decides when it should sort splats based on camera movement, but it doesn't check for scene movement :) As a work-around, whenever the viewer's parent moves you can call:
```
dropInViewer.viewer.updateSplatSort(true);
```
