### ISSUE TITLE
I added it to my vite project, but the page keeps going on processing splates

### ISSUE THREAD

**Issue by lim663** [mkkellogg/GaussianSplats3D#218]
I run this npm install @mkkellogg/gaussian-splats-3d to configure the environment 
Subsequently I add the page 3dplayer.html and write the following code in the corresponding App.vue
<script setup lang="ts">
import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';
import * as THREE from 'three';

const viewer = new GaussianSplats3D.Viewer({
    'cameraUp': [0, -1, -0.6],
    'initialCameraPosition': [-1, -4, 6],
    'initialCameraLookAt': [0, 4, 0]
});
viewer.addSplatScene('@/data/point_cloud.ply', {
    'splatAlphaRemovalThreshold': 5,
    'showLoadingUI': true,
    'position': [0, 1, 0],
    'rotation': [0, 0, 0, 1],
    'scale': [1.5, 1.5, 1.5]
})
.then(() => {
    viewer.start();
});
</script>

<template>

yoyoyo
</template>
<style scoped>

</style>

The page was successfully generated but the console reported the following error:
 DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated.

Could you tell me how to correct it?

**Comment by mkkellogg** [comment]
You'll want to look into how to handle CORS with Vite. There is a section in the README: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-with-vite. Let me know if that works for you!

**Comment by lim663** [comment]
I didn't work. And the error is reported as follows.
<img width="748" alt="屏幕截图 2024-04-30 145501" src="https://github.com/mkkellogg/GaussianSplats3D/assets/153208249/0679b652-33a7-489c-9e2d-559d36d96a3d">
![屏幕截图 2024-04-30 145457](https://github.com/mkkellogg/GaussianSplats3D/assets/153208249/8e133dd2-9680-4ba4-b58c-102d4687e748)

**Comment by lim663** [comment]
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/153208249/789d2aca-f1e7-44a1-a795-c773effa6655)

**Comment by lim663** [comment]
I see what the problem was, I didn't add the following inside the main.ts document: import viewer from '. /Viewer'; viewer.start Now the problem is solved! Thank you for your help and sharing!

**Comment by lim663** [comment]
> You'll want to look into how to handle CORS with Vite. There is a section in the README: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-with-vite. Let me know if that works for you!

I see what the problem was, I didn't add the following inside the main.ts document: import viewer from '. /Viewer'; viewer.start Now the problem is solved! Thank you for your help and sharing!
