### ISSUE TITLE
Dynamic scene transform.

### ISSUE THREAD

**Issue by wakufactory** [mkkellogg/GaussianSplats3D#220]
This wonderful library is giving me a lot of ideas.

I can add multiple splats with addSplatScenes, but is it possible to dynamically set the transform of each scene afterwards?
I tried getting the scene with getSplatScene and changing the transform, but the scene did not change.
Do I need to update anything?

**Comment by mkkellogg** [comment]
You will need to set the `dynamicScene` parameter for the `Viewer` constructor to `true` for starters. You can check out the dynamic scenes example for guidance: https://github.com/mkkellogg/GaussianSplats3D/blob/main/demo/dynamic_scenes.html

**Comment by wakufactory** [comment]
Thank you for your reply. I overlooked the demo.
