### ISSUE TITLE
Splat meshes dont occlude other objects in same scene as DropInViewer

### ISSUE THREAD

**Issue by IsaacBerman** [mkkellogg/GaussianSplats3D#222]
Is there a way to have splats render in front of other objects in the same scene as DropInViewer. I've attempted to change renderOrder to 0 and this doesn't seem to help. Any guidance would be appreciated, thanks.

**Comment by mkkellogg** [comment]
Sorry for the late response, are the objects you want to occlude transparent? If so, then setting their `renderOrder` properties to something less than the instance of `DropInViewer` should work. When you say you set the `renderOrder` to 0, did you mean for the `DropInViewer` or for the objects you're trying to occlude? Objects with a higher render order get rendered after objects with a lower render order.

**Comment by mkkellogg** [comment]
Closing this for now, let me know if you need further assistance with this issue.
