### ISSUE TITLE
How to turn the built-in viewer off?

### ISSUE THREAD

**Issue by Leaf-Player** [mkkellogg/GaussianSplats3D#224]
When I'm already on the current page run the built-in viewer, if I want to run another built-in viewer, they will appear on the same page and overlap.
Just like this:
![Snipaste_2024-05-04_14-18-55](https://github.com/mkkellogg/GaussianSplats3D/assets/105987046/28b28a9b-27b3-49ee-8855-a3580e941b2e)
What should I do if I want to close the previous viewer？

**Comment by mkkellogg** [comment]
Trying calling the `dispose()` function on the viewer, that might be all you need to do.
