### ISSUE TITLE
CDN for GaussianSplats3D

### ISSUE THREAD

**Issue by JeS24** [mkkellogg/GaussianSplats3D#225]
Hi, is a CDN version of this library on the roadmap?

**Comment by graemeniedermayer** [comment]
There seems to be a copy located on unpkg

`https://unpkg.com/@mkkellogg/gaussian-splats-3d@0.4.0/build/gaussian-splats-3d.module.js`

I'm not sure who maintains it.

**Comment by JeS24** [comment]
@mkkellogg Could you please confirm if this is maintained by you?

**Comment by mkkellogg** [comment]
Yeah that should be my package, I believe it is automatically updated as part of the `npm publish` process.

**Comment by JeS24** [comment]
@mkkellogg Thanks. Also, thank you @graemeniedermayer for the find. I believe, this issue can be closed.
