### ISSUE TITLE
How to change "controller" to first-person perspective

### ISSUE THREAD

**Issue by ooyac1** [mkkellogg/GaussianSplats3D#232]
Thank you very much for your work, it's been very helpful. 

However, I'd like to change the controller to a first-person perspective. I've tried a few attempts but they've all failed. Currently, only the 'OrbitControls' mode is available. I would like to use a controller similar to '**PointerLockControls**' or '**FirstPersonControls**' found in Three.js. I hope to expand the interface for future work.

Thank you once again for your work; it's truly great.

**Comment by mkkellogg** [comment]
Others have had issues attempting to do this same thing, but I think they were eventually successful. Can you read through this thread to see if it helps: https://github.com/mkkellogg/GaussianSplats3D/issues/211 ?

**Comment by ooyac1** [comment]
Great, this method worked successfully. Thank you very much.
