### ISSUE TITLE
Loading Issues with Cached Splats?

### ISSUE THREAD

**Issue by timothyallan** [mkkellogg/GaussianSplats3D#237]
Sorry in advance, but this is one of those "can't replicate" issues :)

I'm loading the .splat files like this:

```JSX
     const viewer = new DropInViewer({
          gpuAcceleratedSort: true,
          sharedMemoryForWorkers: false,
          sphericalHarmonicsDegree: 0,
          splatAlphaRemovalThreshold: 5,
        });

       scene.add(viewer);

...

   viewer.addSplatScene(path, {
            splatAlphaRemovalThreshold: 5,
            format,
            showLoadingUI: false,
            showLoadingSpinner: false,
            streamView: true,
          })
```
Myself and a couple other testers have been running into this issue where the Splat isn't loaded correctly if we've already loaded it multiple times. The only way I've been able to fix it, is to open up dev tools, disable the cache and reload. This is on our staging site where the code hasn't changed in days, so it's not something related to building/compiling other javascript.

Seems to only happen in Chrome, although again that might be because it's the one I primarily use for dev/testing and the issue requires multiple re-loads of the same splat.

Currently using Release v0.4.1, although it was happening with previous versions as well.

![Screenshot 2024-05-21 at 5 31 58 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/f8029484-8ea1-48ad-b878-1dc9b2a357be)

Here's a couple before/afters in case it visually shows you anything:

![Screenshot 2024-05-21 at 5 46 46 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/add6864c-98d1-4485-bcec-e8531ca6eabd)
![Screenshot 2024-05-21 at 5 46 40 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/d797ea72-b257-405c-923c-93694117ea7e)
![Screenshot 2024-05-21 at 5 46 12 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/4ab993fd-344c-499d-9bc0-5721665c9692)
![Screenshot 2024-05-21 at 5 37 01 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/f1630511-bff5-41f5-817f-87e9ef5511b8)

Edit: It seems to be a race condition somewhere, which probably explains why it happens only on the compiled staging site, and not on the slower dev stuff. 

If I throttle the network, it still loads from the cache, and the splat appears fine all the time. Changing the network throttle back to none and reloading the page give me the messed up view consistently.

![Screenshot 2024-05-22 at 1 30 43 PM](https://github.com/mkkellogg/GaussianSplats3D/assets/1995135/c101a4fb-bb5a-4d44-a9b3-e3f5425c5b3e)

**Comment by timothyallan** [comment]
The issue is that I attach an object to the Drop in Viewer after `onProgress` hits 1, but it seems like there's something else that needs to run internally after that, and my object botches it up.

If I ignore the `onProgress` and just us a `then()` after  `viewer.addSplatScene`, my object attaches fine, and the splat renders correctly all the time.

**Comment by mkkellogg** [comment]
Ah, so `onProgress()` will show progress for both downloading the splat scene and then for processing the scene after downloas. For each of those tasks the percentComplete value ranges from 0 to 1, so you're probably trying to do something after the scene is downloaded, but before it is processed.

**Comment by timothyallan** [comment]
That'd do it!  think there's multiple issues actually:

Adding my object after the train .splat was done processing fixed that issue, but the tractor .ply file was only loading portions correctly. 

It would have visible seams either right down the middle, or in 4 squares, where 3 squares were not loaded properly... on a guess, I set `streamView: false` on the viewer, and magically it now loads fine every time. Will have to do some more investigation it looks like. Thanks for the help.
