### ISSUE TITLE
Model rendering does not work in browsers on iOS versions below 16.4

### ISSUE THREAD

**Issue by whwhwwhwwh** [mkkellogg/GaussianSplats3D#241]
Hi,

First of all, I want to say that your model library is fantastic, and I really enjoy using it. However, I have encountered an issue where the model can not rendering on iPhones running iOS versions below 16.4.

Could you please look into this issue and let me know what might be causing it?

Thank you!

**Comment by mkkellogg** [comment]
I'll see if I can find a device with an appropriate iOS version and I'll get back to you :)

**Comment by whwhwwhwwh** [comment]
I reproduced this issue on an iOS 16.1 simulator, as shown in the screenshots below (Figures 1 and 2 are the exception captures I added in the source code, and Figure 3 is the console error). The error occurs in the WebAssembly.compile(sorterWasmBytes) section. Could you take a look and see how this issue can be resolved?

![note1](https://github.com/mkkellogg/GaussianSplats3D/assets/37065614/d7c8f332-4f28-4612-94b3-8c148ee82d60)


![note2](https://github.com/mkkellogg/GaussianSplats3D/assets/37065614/9fbdfbfc-aa3a-435e-b8d5-73a810938ba6)
![error](https://github.com/mkkellogg/GaussianSplats3D/assets/37065614/2de1fc10-0fe5-4376-9240-38a980cb3051)

**Comment by mkkellogg** [comment]
I should have asked this earlier, but does this error occur only in specific browsers (like Safari) or all browsers?

**Comment by mkkellogg** [comment]
I made an update that forces a non-SIMD version of the splat sort when using iOS < 17.0 here: https://github.com/mkkellogg/GaussianSplats3D/tree/general_updates. Would you be able to try that out?

**Comment by whwhwwhwwh** [comment]
Thank you very much for your response and the provided solution. I tested it on an iOS 16.1 simulator and it works fine under normal circumstances. However, when I set `sharedMemoryForWorkers` to `false` or when I render the model using an iOS 15.0 simulator, I encounter the following error: "WebAssembly.Module doesn't parse at byte 67shared memory is not enabled". I am not sure how to resolve this issue. Could you please take another look?

![WechatIMG44287](https://github.com/mkkellogg/GaussianSplats3D/assets/37065614/2f7499f0-cf13-4e7d-b266-8b2591488af7)

**Comment by mkkellogg** [comment]
Ok I've made a few more tweaks targeting iOS versions below 16.0 to that same branch, want to give it another try?

**Comment by mkkellogg** [comment]
Great, glad it worked!

**Comment by whwhwwhwwh** [comment]
Hello, after conducting my tests, there still seems to be an issue with iOS versions below 16.4. I think the following changes can be made to the code in the file /src/worker/SortWorker.js:

```
    // iOS makes choosing the right WebAssembly configuration tricky :(
    let iOSSemVer = isIOS() ? getIOSSemever() : null;
    if (!enableSIMDInSort && !useSharedMemory) {
        sourceWasm = SorterWasmNoSIMD;
        if (iOSSemVer && iOSSemVer.major < 16) {
            sourceWasm = SorterWasmNoSIMDNonShared;
        }
    } else if (!enableSIMDInSort) {
        sourceWasm = SorterWasmNoSIMD;
    } else if (!useSharedMemory) {
        if (iOSSemVer && iOSSemVer.major < 16) {
            sourceWasm = SorterWasmNonShared;
        }
    }
```

In the code, change the condition 
`if (iOSSemVer && iOSSemVer.major < 16) {` 
to
`if (iOSSemVer && iOSSemVer.major <= 16 && iOSSemVer.minor < 4)`
Moreover, according to the previous logic, the `if` inside the last `else if` should not be reachable.

Therefore, the modified code segment would be:

 ```
  // iOS makes choosing the right WebAssembly configuration tricky :(
  const iOSSemVer = isIOS() ? getIOSSemever() : null
  if (!enableSIMDInSort && !useSharedMemory) {
    sourceWasm = SorterWasmNoSIMD
    if (iOSSemVer && iOSSemVer.major <= 16 && iOSSemVer.minor < 4)
      sourceWasm = SorterWasmNoSIMDNonShared
  }
  else if (!enableSIMDInSort) {
    sourceWasm = SorterWasmNoSIMD
  }
```
