### ISSUE TITLE
Certain 3DGS models cause crashes on iOS browsers

### ISSUE THREAD

**Issue by karlleungkm** [mkkellogg/GaussianSplats3D#245]
As title says, when loading certain models (such as the garden scene in the online demo, both low and high quality), no matter through viewer or drop-in viewer, the page crashes and shows the "A problem repeatedly occured" error.
The issue persists whether using .ply or .ksplat formats.
Additionally, whether the page crashes or not, occasionally the progress window would show the loading progress reach 100%, then drop down to 0% and start climbing again.

Tested in Chrome and Safari on:
iPhone 14 Pro, running:
- iOS 17.4.1
- Safari 604.1
- Chrome 125.0.6422.145
iPhone 15 Pro, running:
- iOS Version 17.5.1
- Safari 604.1
- Chrome 125.0.6422.145

**Comment by mkkellogg** [comment]
Just to clarify: this doesn't happen on all models? For models that do cause a crash, are they typically large models or is there some other distinguishing characteristic about them?

**Comment by karlleungkm** [comment]
It's not all models, no.
The ones that do crash are large models, but not all of the large models (both scene or file size) cause crashes; We can't really find any sort of common pattern between the models causing crashes

**Comment by mkkellogg** [comment]
Large models crashing on mobile devices is unfortunately quite common. If you can consistently load smaller models without crashes, I would be file size (splat count) is the culprit here. Are you enabling spherical harmonics? Disabling them or only using 1st degree should help.

**Comment by mkkellogg** [comment]
I recently made some updates around memory usage, you might be able to get away with using compressed `.ksplat` files for larger scenes now.

**Comment by mkkellogg** [comment]
I'll close for now, let me know if you need any more help.

**Comment by MarcelloPajntar97** [comment]
any update about this? i have the same issue

**Comment by mkkellogg** [comment]
@MarcelloPajntar97 It might just be that your specific iOS device isn't capable of displaying splats (I could be wrong about that). What device & iOS version are you using?

**Comment by Vision70s** [comment]
> @MarcelloPajntar97 It might just be that your specific iOS device isn't capable of displaying splats (I could be wrong about that). What device & iOS version are you using?

I think this is a current problem, I encounter it, everything works fine in progressive loading mode, but at the stage of date optimization the page reloads, we would like to figure this out, and improve performance, perhaps consider Donation
