### ISSUE TITLE
how to roam around in a room unable to zoom upto the mark 

### ISSUE THREAD

**Issue by sumanttyagi** [mkkellogg/GaussianSplats3D#256]
how to use three js for indoor scene  - as it is getting restricted zoom in certain areas how to i zoom to pass that surface area .

**Comment by mkkellogg** [comment]
If you are unable to zoom past a certain point, you probably need to pan the camera to a different location with a better vantage point. With a mouse you can do this by dragging the mouse while holding the right mouse button.

**Comment by mkkellogg** [comment]
Just checking in, we you able to resolve this issue?

**Comment by mkkellogg** [comment]
Closing for now, please let me know if you're still having trouble with this.
