### ISSUE TITLE
Issues rendering spherical harmonics

### ISSUE THREAD

**Issue by nickpaustian-slv** [mkkellogg/GaussianSplats3D#263]
I have a very simple scene setup using the library via npm and it works perfectly, until I enable spherical harmonics. 

<img width="677" alt="Screenshot 2024-06-14 at 12 16 57 PM" src="https://github.com/mkkellogg/GaussianSplats3D/assets/169336958/14e884c1-d656-48cb-bf48-8a25eec570c6">

I have tested the model in the online viewer (https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php) and it works there so I am sure it is something to do with my setup so I am still working through debugging, however I thought I would ask in case someone can point me in the right direction.

The code that loads the splat:

private async loadSplat() {
    this.splatViewer = new GaussianSplats3D.Viewer({
      threeScene: this.scene,
      renderer: this.renderer,
      camera: this.camera,
      useBuiltInControls: false,
      sphericalHarmonicsDegree: 2,
    })

    this.splatViewer
      .addSplatScene(plyUrl, {
        position: [0, 0, 0],
        rotation: composedRotation,
        scale: [100, 100, 100],
        progressiveLoad: false,
        showLoadingUI: false,
      })
      .then(() => {
        this.splatViewer.start()
      })
  }

**Comment by mkkellogg** [comment]
Would you be willing to share your `.ply` file? Maybe I can do some troubleshooting on my end.

**Comment by nickpaustian-slv** [comment]
I believe I have uncovered the issue, it looks like the spherical harmonics are affected by the scale of the splat scene.

Here is the same splat at a lower scale:

<img width="565" alt="Screenshot 2024-06-21 at 2 15 52 PM" src="https://github.com/mkkellogg/GaussianSplats3D/assets/169336958/7f96f813-4025-405b-a09c-7447c85ce33f">

and at a scale of 1:

<img width="602" alt="Screenshot 2024-06-21 at 2 16 19 PM" src="https://github.com/mkkellogg/GaussianSplats3D/assets/169336958/639635f5-e834-4b4b-99fe-941ec65d1248">

I think I was using a higher scale to work with some other objects I had in my scene, but I should be able to scale those down to work with the splat instead.

**Comment by mkkellogg** [comment]
Thanks for figuring this out, it turns out I didn't take the scene's scale into account when rotating spherical harmonics (I just assumed a scale of <1, 1, 1>). I'll include a fix in the next release.

**Comment by mkkellogg** [comment]
I made an update in the `2dgs` branch that should address this issue, want to try it out? You should be able to scale the scene now without affecting the spherical harmonics.

**Comment by nickpaustian-slv** [comment]
Thanks @mkkellogg, that is working great now when scaled.
