### ISSUE TITLE
The v0.4.2 has a greenish tint in the rendered scenes, which did not occur in version v0.4.0.

### ISSUE THREAD

**Issue by lucylucy27** [mkkellogg/GaussianSplats3D#266]
Hi，

I accidentally encountered this issue when rendering a PLY file. Not every file exhibits this problem.
This issue comes from the upgrade from 0.4.0 to 0.4.2.

Thanks~

**Comment by lucylucy27** [comment]
![v0 4 0](https://github.com/mkkellogg/GaussianSplats3D/assets/149787651/06a071cf-e4cd-4a1f-b556-4cd9e48bc72e)
![v0 4 2](https://github.com/mkkellogg/GaussianSplats3D/assets/149787651/6ba5697f-7a16-43b9-9f3e-ce7bdf24a460)

**Comment by mkkellogg** [comment]
Would you be able to share a `.ply` file that has the problem? That might help me debug it.

**Comment by mkkellogg** [comment]
Can you try out the latest in the `2dgs` branch to see if recent updates might have fixed this issue?

**Comment by lucylucy27** [comment]
Yes. It's fixed in 2dgs branch.

Thanks~
