### ISSUE TITLE
When can 2D Gaussian be supported？

### ISSUE THREAD

**Issue by chenqi13814529300** [mkkellogg/GaussianSplats3D#267]

**Comment by mkkellogg** [comment]
Very soon :) It's just a matter of verifying that the output of my viewer matches the output of the reference viewer in https://surfsplatting.github.io/. I've just been having a hard time getting their viewer to work. My viewer currently appears to work pretty well for 2D splat scenes so you can just use the `2dgs` branch right now if you want.

**Comment by chenqi13814529300** [comment]
Very cool, thank you very much for your efforts!

**Comment by hbb1** [comment]
Thank you for integrating 2DGS into your impressive viewer! Our Mip-Splatting has also benefited greatly from your viewer. I truly appreciate your efforts and support!

**Comment by mkkellogg** [comment]
I was happy to do so! Please let me know if you notice any serious discrepancies between my viewer and yours.

**Comment by LaFeuilleMorte** [comment]
<img width="565" alt="image" src="https://github.com/user-attachments/assets/9816fbe3-4abf-42ad-af15-32133f151790">
Hi, I've encountered bug when trying to load 2D gaussian scenes.  My pannel was like this:
<img width="354" alt="image" src="https://github.com/user-attachments/assets/d27e530b-7f1a-49df-b7e4-14c27f69e93d">

**Comment by mkkellogg** [comment]
What kind of file is it? Is it a `.ply` file? I think my viewer is having a hard time determining the type because there is no extension on the filename ("room").

**Comment by LaFeuilleMorte** [comment]
> What kind of file is it? Is it a `.ply` file? I think my viewer is having a hard time determining the type because there is no extension on the filename ("room").

Oh, I forgot to add extension name to my ply file. Everything works as normal when I added it. Thank you very much!

**Comment by mkkellogg** [comment]
Going to close this for now, please let me know if any issues arise with the current 2D implementation!
