### ISSUE TITLE
Orientation problem after nerfstudio export

### ISSUE THREAD

**Issue by pesa2000** [mkkellogg/GaussianSplats3D#268]
Hi Mark, how are you? 

The question itself is not properly related to your viewer but i hope you can still help me in some way, i dont know how much you are familiar with nerfstudio but when training a scene the viewer of nerfstudio renders the scene correctly with a vertical orientation and everything is aligned to the ground, in other words the scene is exactly like it was captured. 
Now when exporting it to the ply format and rendering it trough your own viewer or even the supersplat viewer(PlayCanvas), the scene is rotated, i assumed there is something in the output of the training that contains those type of data and in fact i found a file with a scale and tranform array.

`{
    "transform": [
        [
            0.9978084564208984,
            0.0593765564262867,
            0.02920190431177616,
            -0.062379609793424606
        ],
        [
            0.02920190431177616,
            -0.7911737561225891,
            0.6108939051628113,
            -0.07375505566596985
        ],
        [
            0.0593765564262867,
            -0.6087023019790649,
            -0.7911737561225891,
            -0.00241132453083992
        ]
    ],
    "scale": 0.23555300962586065
}`

Assuming the transform matrix is for rotating the scene i tried it without the expected results, plus shouldnt the transform matrix be a 4 x 4? 

Am i missing something?

Thank you very much for your time, have a great day!

**Comment by mkkellogg** [comment]
Hmm, I'm not exactly sure how that transform data should be used, although I have some guesses. Could you share the corresponding `.ply` file and I can try to figure it out?

**Comment by pesa2000** [comment]
Sure, thank you very much in advance, i will give you a little more context, when exporting from nerfstudio there are 3 parameters that make you center/scale/rotate the scene before processing the ply file, in my case even when using those 3 the scene doesnt change at all so i will need another method to rotate them.

This is the corresponding ply 
https://we.tl/t-dsrvvPVPaV(cant upload a ply on github)

**Comment by pesa2000** [comment]
At this point i will provide two more screenshots of the  nerfstudio viewer maybe you can understand better what actually si going on

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/36411479/53251d71-6f84-44e4-b434-aeba125496ab)
![Screenshot_3](https://github.com/mkkellogg/GaussianSplats3D/assets/36411479/7538640b-b84c-46fd-9b55-6ac62ac309f0)

**Comment by mkkellogg** [comment]
So after playing around with the `transform` data you supplied above, the scene is still not oriented correctly. My best advice (without knowing much about how nerf studio sets the orientation) would be to just manually orient the scene in my viewer, then open the info panel with the `I` key to see the camera parameters, and then use those parameters when setting up the viewer.

**Comment by pesa2000** [comment]
Thank you for the advice i will surely try it today, for now im testing with only one dataset so i dont actually now if every output is oriented in the same way, if this is the case i can perform a rotation (that i need to calculate) on every one of them.

**Comment by abrahamezzeddine** [comment]
The reason is because nerfstudio flips the orientation between regular COLMAP and nerfstudio format. Z<->Y

**Comment by pesa2000** [comment]
I actually found out the issue, if you use `ns-process-data images` the nerfstudio implementation of colmap skips completely the step called "Model Aligner", after adding this step the reconstruction is correctly oriented in the final output.

Im gonna close since it was already irrelevant at the time, thank you very much @mkkellogg for the tests.
