### ISSUE TITLE
Viewer is not defined

### ISSUE THREAD

**Issue by hariharan1412** [mkkellogg/GaussianSplats3D#269]
I want the current ```Camera position``` ,  ```Camera Look up``` array from InfoPanel so I tried to debug from console but when I tried calling Viewer, it threw this error.  I don't know JavaScript that much.

```
VM1630:1 Uncaught 
ReferenceError: Viewer is not defined
    at <anonymous>:1:1
```

**Comment by mkkellogg** [comment]
Can you share your code? That might help me debug.

**Comment by hariharan1412** [comment]
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/51135395/cb9d4d4c-904d-4cea-a544-edd7d1c9446a)



Hi, as you can see, I'm using your default Demo Viewer for debugging, but this itself is throwing the same error.

**Comment by mkkellogg** [comment]
Yes that is what I would expect to happen, you can't really use the debug console like that :)

What you need to do is set a breakpoint at an appropriate place in the code. Here I have set a breakpoint at line 1546 in `Viewer.js`:
<img width="1260" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/6249005/42f2cab8-bba8-42ae-b490-4bc3b9256e7f">

When the execution reaches the above breakpoint, I can then inspect viewer properties or camera properties in the debug console:
<img width="1240" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/6249005/a55ebc5d-30b2-452a-a6cf-c78d78923584">

**Comment by mkkellogg** [comment]
Closing this for now, let me know if you need any more help with this.
