### ISSUE TITLE
Can we dynamically swap PLY files

### ISSUE THREAD

**Issue by lucylucy27** [mkkellogg/GaussianSplats3D#270]
Hi,

viewer.addSplatScenes([
{
  'path': plyPath1
},
{
  'path': plyPath2
}]);

I use this command to add ply1 and ply2. After that, both ply1 and ply2 will be loaded into CPU and GPU memory to render. 
I want to achieve the functionality where I can continue rendering ply1 while releasing the memory occupied by ply2 and loading ply3. How can I accomplish this?

Thanks~

**Comment by mkkellogg** [comment]
Once both ply1 and ply2 have been loaded, you can call `Viewer.removeSplatScene(<sceneIndex>)` to remove a splat scene. Once that call completes, you can then load ply3. Something like:

```
viewer.addSplatScenes([{
  'path': plyPath1
},{
  'path': plyPath2
}])
.then(() => {
  viewer.removeSplatScene(sceneIndex)
  .then(() => {
     viewer.addSplatScene(ply3Path, ply3Options);
  });
})
```

**Comment by lucylucy27** [comment]
Hi, [mkkellogg](https://github.com/mkkellogg),

It works for me, thanks~
