### ISSUE TITLE
Weird rotation of splats in some section of point cloud

### ISSUE THREAD

**Issue by kstoneriv3** [mkkellogg/GaussianSplats3D#272]
I have a relatively large .ply file (that was artificially generated from point cloud data). This file looks fine on another viewer (https://github.com/playcanvas/supersplat) but when I view it on the three.js viewer, the rotation of the splats are corrupted in some area. As can be seen in the screenshot, there seem to be a clear rectangular boundary which separates the area of corrupted rotation and one with fine rotation.

As the file was generated in a way that should not cause such an issue and the file looked fine on another viewer, I suspect there is some problem in the three.js viewer. 

<img width="1325" alt="スクリーンショット 2024-07-02 15 17 35" src="https://github.com/mkkellogg/GaussianSplats3D/assets/30857855/79a72dcf-d204-4edc-bd39-27e91e9cbfb2">

https://github.com/mkkellogg/GaussianSplats3D/assets/30857855/7a0610cc-fc78-4c85-98a1-d1eb82de016f

The boundary looks like a combination of surfaces of boxes, which makes me wonder if this has something to do with how points are stored and rendered within the viewer.

**Comment by mkkellogg** [comment]
Yeah if you could share the `.ply` file as well as your code for setting up the viewer, that would be helpful. The best email to share it with would be mkkellogg [at] gmail.com

**Comment by kstoneriv3** [comment]
Hi @mkkellogg , that'd be great! Thank you! I should have shared the file on google drive (with my corporate email address). Please let me know if you cannot find the shared file.

**Comment by mkkellogg** [comment]
So I'm having some trouble loading your `.ply` because it is too big :) Until I am able to get it loaded and debug it, you might try setting `integerBasedSort: false` for the `Viewer` constructor.

**Comment by kstoneriv3** [comment]
Thank you for checking this and sorry for the large file that sent you! I tried to trim down the data but with more aggressive trimming, I could not reproduce this issue. 

> you might try setting integerBasedSort: false for the Viewer constructor.

I tried running the demo with `integerBasedSort: false` but it did not fix the problem.

**Comment by mkkellogg** [comment]
Out of curiosity, if you load your `.ply` into super splat and then export to `.splat`, and then load the `.splat` file using my viewer, does the problem still occur?

**Comment by kstoneriv3** [comment]
I still see the issue with the .splat file generated by supersplat but with some difference. This time, corrupted rotation appears in different section:

![スクリーンショット 2024-07-08 10 33 08](https://github.com/mkkellogg/GaussianSplats3D/assets/30857855/17bbbd38-41b7-4723-b10d-2f93e682bae8)
![スクリーンショット 2024-07-08 10 33 34](https://github.com/mkkellogg/GaussianSplats3D/assets/30857855/05abf721-d54a-4a8d-a911-fcd500136951)


The red lines roughly indicates the boundary of corrupted splats and uncorrupted ones.

**Comment by mkkellogg** [comment]
So it turns out this issue is caused by a weird problem I've run into before where for some reason the maximum number of texels in a three.js data texture is 16777216 (2 ^ 24). I don't know what the root cause is, but for the time-being I have implemented a work-around by improving the way half-precision covariance values are packed into a texture. The work-around is now in the `2dgs` branch and can be activated if you pass a value of `true` for the `Viewer` constructor parameter `halfPrecisionCovariancesOnGPU`. Can you try it out to see if it fixes the problem?

**Comment by kstoneriv3** [comment]
Thank you so much! I can confirm that your workaround works on my local environment as well.

The root cause you mentioned sounds greek to me but it is great to hear that it can be dealt with. 

 Do you have any ideas on when this fix becomes available on the main branch? (I am in no rush but just being curious...)

**Comment by mkkellogg** [comment]
Hopefully I will get this out as part of an official release within the next week.

**Comment by kstoneriv3** [comment]
Thank you! That's great to hear!!
