### ISSUE TITLE
problem about refreshGPUDataFromSplatBuffers() and add scenes

### ISSUE THREAD

**Issue by Linkersem** [mkkellogg/GaussianSplats3D#284]
Hello, in order to solve the problem of black screen when adding scenes, I was reading the code, when adding scenes, I noticed that the `refreshGPUDataFromSplatBuffers `function would be called, but the parameter `sinceLastBuildOnly `never seemed to be true, I made it true when I added a new scene, However, this leads to an error when calling the `fillSplatDataArrays `function,I felt very strange.

> TypeError: Cannot read properties of undefined (reading 'splatCountOffset')

And after adding it, I get the `buildResults `variable and start sorting, but I don't know what happened after sorting, how do I make sense of it here?

**Comment by mkkellogg** [comment]
`sinceLastBuildOnly`  should never be set directly, it's really only used for progressive loading. Can you share your code for adding the scenes?

**Comment by Linkersem** [comment]
Okay, I noticed that this parameter seems to be able to add data directly after the data added before, so I thought maybe this could solve the problem of black screen when adding scenes, so I forcibly modified it to "true" through a logical judgment, like this:

>         if (splatBuffers.length != 2) {
>              isUpdateBuild = true;
>         }

and at the same time I noticed that when I continued to add scenes, the `disposeTextures()` function would be called, and I commented it out, but there would still be a black screen problem, and I felt clueless, I don't understand what is the reason for the black screen when adding the scene, and is this not possible to modify from the lowest level of code logic?
and this is my code for add scenes.
[test.txt](https://github.com/user-attachments/files/16277648/test.txt)

**Comment by mkkellogg** [comment]
So for adding scenes, you also need to implement a render pause. Try this update function:
```
function update() {
  requestAnimationFrame(update);
  if (!renderPause) {
    controls.update();
    renderer.render(threeScene, camera);
  }

  count++;
  console.log("============",count);
  if(count == 3000){
    var list = [0,1];
    renderPause = true;
    viewer.addSplatScenes([        
    {
      'path': 'assets/data/garden/garden_high.ksplat',
      'splatAlphaRemovalThreshold': 20,
    },
    {
      'path': 'assets/data/stump/stump_high.ksplat',
      'splatAlphaRemovalThreshold': 20,
    }
    ]).then(() => {
      renderPause = false;
    });
  }
}
```

**Comment by Linkersem** [comment]
EMmm,all right, but is it inevitable that this will cause the rendering to pause, and the picture will stutter, and there is no good way to switch scenes seamlessly?  I've also tried to create multiple viewers to render another scene when switching, but I still get stuttering. I've been trying this lately, but there's been no progress.

**Comment by mkkellogg** [comment]
Yeah there's really no way to get around the picture stutter or rendering pause at the moment; the viewer was never designed to seamlessly add or remove scenes while maintaining responsiveness and interactivity during the entire transition.

**Comment by mkkellogg** [comment]
Closing for now, let me know if there's anything else related to this I can help with.
