### ISSUE TITLE
View costum ksplat

### ISSUE THREAD

**Issue by DuVogel87** [mkkellogg/GaussianSplats3D#285]
Hello.

How can i view a costum .ksplat (converted here: https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php) ?

I put the .ksplat in the dir: C:\mark kellogg\GaussianSplats3D\build\demo\assets\data\Dachboden

In this dir i run the terminal and execute the command: npm run demo

The terminal then says: 

C:\mark kellogg\GaussianSplats3D\build\demo\assets\data\Dachboden>npm run demo

> @mkkellogg/gaussian-splats-3d@0.4.3 demo
> node util/server.js -d ./build/demo

Server running at 0.0.0.0:8080

I then copy 0.0.0.0:8080 to my firefox browser but get an error, saying: no connection can be established

Sorry, i am a beginner and think its a silly mistake or misunderstandig from my side HOW things work. 

I appreciate any kind of guidance here. Thanks! 

![kellogg 00008080 error no connection](https://github.com/user-attachments/assets/2f9fb8ce-8346-493d-beca-409f463d67ba)
![kellogg converted ksplat](https://github.com/user-attachments/assets/d9f2ea66-0f9c-4295-93d6-2ad138859748)
![kellogg npm run demo](https://github.com/user-attachments/assets/48650d8d-3d5e-4a84-99d3-c68d44522bd7)

**Comment by mkkellogg** [comment]
Hmmm, I can see why that message is confusing, the way you should actually access the demo locally is:
```
http://127.0.0.1:8080
```
I'll fix that message in the next release.

**Comment by DuVogel87** [comment]
Thanks for your super fast answer. Still i dont get i run. 

My Terminal says: 
![kellogg npm run demo2](https://github.com/user-attachments/assets/f48446e9-fd75-4496-beb6-c92a835728cc)

What i dont understand is, that the terminal seems to look into ./build/demo
while in your github repo it says, that i shall put the demo (and also my costum .ksplat) into build/demo/assets/data

Thats how my dir looks like. I have a demo and a build folder. Am i placing files wrong?
![kellogg build demo assets data](https://github.com/user-attachments/assets/2d6ab145-72bf-4156-99e1-78c66f673b2f)

Also, when i type in http://127.0.0.1:8080 in my browser after executing npm run demo in the terminal i get directed to your page:
![kellogg 1270018080](https://github.com/user-attachments/assets/580820e0-7dc2-4ed3-bed6-d848f71a9e0e)

Sorry again if i sound to noobish!

**Comment by mkkellogg** [comment]
The location of your `.ksplat` file can be anywhere, you just need to use the UI circled in red below to view it:
![image](https://github.com/user-attachments/assets/e885689b-4019-4e13-bb31-1f7ccbaeb581)
Click on "Choose file" to choose your `.ksplat` file and then set any of the other parameters for setting up your scene.

**Comment by DuVogel87** [comment]
Thanks. I thought it immediatly should pop up and run the scene. Chase closed! :)

**Comment by mkkellogg** [comment]
Glad you got it working!

**Comment by DuVogel87** [comment]
ah maybe one last question. is it possible to host your code on my own website due to copyright?

And also do you have a guide how to do it.

Would be nice to show my own models like so, on my webpage:
![Uploading screenshot scene.PNG…]()

**Comment by DuVogel87** [comment]
![Uploading screenshot scene.PNG…]()
