### ISSUE TITLE
Trying to make it work on Expo/React Native

### ISSUE THREAD

**Issue by Jacky56** [mkkellogg/GaussianSplats3D#287]
Hello all,

I'm trying to build a react native app using this 3dgs viewer but couldn't make it work on android (works on web). I suspect there's an issue with how `GLView` loads the viewer.

Error:
![image](https://github.com/user-attachments/assets/8af03202-343a-442e-b1c3-4991609c858e)

```txt
TypeError: Cannot read property 'add' of undefined
```

sample code:
```tsx
import { GLView } from "expo-gl";
import { Renderer } from "expo-three";
import {GridHelper, PerspectiveCamera, Scene,} from "three";
import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';

export default function App() {

  const onContextCreate = async (gl) => {
    const { drawingBufferWidth: width, drawingBufferHeight: height } = gl;
    const renderer = new Renderer({ gl });
    renderer.setSize(width, height);

    const camera = new PerspectiveCamera(70, width / height, 0.01, 1000);

    const scene = new Scene();
    camera.lookAt(scene.position);
    scene.add(new GridHelper(5, 5));

    const viewer = await new GaussianSplats3D.Viewer({
      'renderer': renderer,
      'camera': camera,
      'threeScene': scene,
      'sharedMemoryForWorkers': false,
      'gpuAcceleratedSort': false,
    });
  
    viewer.addSplatScene('<a .splat file>')
    .then(() => {
        viewer.start();
    });

    // const render = () => {
    //   timeout = requestAnimationFrame(render);
    //   viewer.render();
    //   viewer.update();
    //   // renderer.render(scene, camera);
    //   gl.endFrameEXP();
    // };
    // render();
  };

  return (
    <GLView style={{ flex: 1 }} onContextCreate={onContextCreate}  />
  );
}
```

**Comment by Jacky56** [comment]
Update:
- It doesn't work on native platforms because of objects such as `LoadingSpinner`, trying to find `div` when it shouldn't exist on other platforms.


is there a way to only use the splat loader such as `viewer.addSplatScene('<a .splat file>')`?

**Comment by mkkellogg** [comment]
If you disable display of the loading spinner, does that fix the issue? You could try:
```
viewer.addSplatScene('<a .splat file>', { showLoadingUI: false });
```

**Comment by Jacky56** [comment]
Hi @mkkellogg thank you for your response, I have tried this too, it did work but [antimatter15](https://github.com/antimatter15/splat)'s implementation uses web workers which doesn't translate to native platforms ([1](https://github.com/mkkellogg/GaussianSplats3D/blob/main/src/worker/SortWorker.js#L200-L207) [2](https://github.com/antimatter15/splat/blob/main/main.js#L768-L774)), I've tried to edit the code to use [worklets](https://github.com/margelo/react-native-worklets-core) instead of workers but my javascript knowledge is quite poor.


The final work around was to wrap in a [WebView](https://github.com/react-native-webview/react-native-webview) component which does works but I'm worried about the additional resources used, especially for weaker devices

**Comment by seppestaes** [comment]
@Jacky56 : Is the performance OK in the WebView (iOS / Android) ? Br, Seppe

**Comment by mkkellogg** [comment]
Closing for now, please let me know if there are any other questions I can answer.

**Comment by IsmailOuazzani** [comment]
Hi @Jacky56 , I have been facing this issue myself and have not succeeded with the WebView. Would you mind sharing your code?
Thank you so much.
