### ISSUE TITLE
Odd progressiveLoad reveal with scaled splat

### ISSUE THREAD

**Issue by jvandereijk** [mkkellogg/GaussianSplats3D#292]
When I try to progressively load a .ply or .splat file and I set the scale property (to [10,10,10]), the loading seems wierd.
At first a small part of the splat is revealed and after a couple of seconds, suddenly the full splat is shown.

When I remove the scale, it loads normally. (Actually the reveal is a bit fast now, but maybe because this splat is so small).

It looks like the reveal progress is based on the original scale perhaps ?

Test/demo code can be found [here](https://github.com/jvandereijk/splat/blob/main/source/index.html)

**Comment by mkkellogg** [comment]
I think there is a bug in my code. Can you try changing the line at https://github.com/mkkellogg/GaussianSplats3D/blob/ef524f4308c7793c78005aeedc03a2f8f8f138fa/src/splatmesh/SplatMesh.js#L1177
I think it should be:
```
this.getSplatCenter(i, tempCenter, true);
```

**Comment by jvandereijk** [comment]
Yep, that seems to fix it, Thanks!

PS: For this cropped splat the center seems a bit off, but I tried with other splats and they look fine.

**Comment by mkkellogg** [comment]
Glad you got it working! The scene reveal process always starts from the 3D origin <0, 0, 0> and precedes outward from there. So if your model's center is not at <0, 0, 0> it won't look quite right.
