### ISSUE TITLE
Share splat scene between several viewers

### ISSUE THREAD

**Issue by AlexYukhnevich** [mkkellogg/GaussianSplats3D#296]
My case is as follows:
1. I have two viewers created by `Viewer` class with the same configuration. 
At now each viewer run `addSplatScene` and sends a request to the same `url`. The relation is like **one-to-one**. I want to share one data source between two viewers like **one-to-many**. 
The question: How to share one data source (splat scene) between several viewers?
2. The second question: How to sync camera (`position`, `rotation`, `zoom`) between two viewers with the same data source if it's possible?

Thanks in advance!

**Comment by mkkellogg** [comment]
For (1), there's no built-in way to do what you're describing. Each instance of `Viewer` is completely isolated from any other instance and there's no way to share data between them.
For (2), there's also no built-in way to do this, but it wouldn't too hard to implement if you want :)

**Comment by mkkellogg** [comment]
Closing for now, let me know if you need any assistance with implementation.
