### ISSUE TITLE
Iphone X renders completely different with same asset and same settings

### ISSUE THREAD

**Issue by pesa2000** [mkkellogg/GaussianSplats3D#297]
Hi Mark, how are you? 

I was making a couple of tests on my implementation of your viewer and i noticed something really strange happening on an old iphone of mine, on this iphoneX as you can see there is something really strange.

![image](https://github.com/user-attachments/assets/93264e67-d5f9-444e-bfe4-f57ad4fc566d)

This is the render in every other devices

![image](https://github.com/user-attachments/assets/9d2244b4-394d-4e23-ba8d-d0a88d97cbab)

Can this be something browser related like a safari version?

**Comment by mkkellogg** [comment]
Have you tried different browsers besides Safari? Also, have you tried setting `sharedMemoryForWorkers` to `false` when instantiating the `Viewer`?

**Comment by pesa2000** [comment]
![image](https://github.com/user-attachments/assets/e7440539-fd27-4288-b33a-5e4f28566ef1)

![image](https://github.com/user-attachments/assets/7e8250f8-0e13-4622-9f6b-56601b9234e0)

these are the settings im currently using for both the scene and the viewer. 

I'll let you know asap if it happens in other browsers too.

**Comment by lucarinaldii** [comment]
Same problem for me with iPhone 8 @mkkellogg

**Comment by pesa2000** [comment]
Hi Mark, i had the possibility to test this error on another device too. 

like @lucarinaldii i faced the same problem on iphone 8 and iphoneX 

![image](https://github.com/user-attachments/assets/25444723-5d96-40cc-a4c2-176815da8c0d)

this is an example tested with both safari and chrome. 

both iphones uses the latest IOS 16 version. 

are there any settings that you know that can give those type of problems? maybe like "gpuAcceleratedSort" or "halfPreciosCovarianceOnGpu"? 

Thank you for your time and patience.

**Comment by mkkellogg** [comment]
Sorry for the late response, what type of file are you trying to load? If it is a `.ply` file, you might want to try setting `plyInMemoryCompressionLevel: 0`. You should also try setting `halfPrecisionCovariancesOnGpu: false` (make sure to check the spelling), `integerBasedSort: false`, and `antialiased:false` (unless you know for sure it is an anti-aliased scene).

**Comment by pesa2000** [comment]
Thank you for the response, ill try it asap.
In the meantime i found this #265 , are these problems related?

Thank you for your time and patience.

**Comment by pesa2000** [comment]
Hi Mark, like the #265 the problem seems related to the selector of the WebAssembly configuration. 

![image](https://github.com/user-attachments/assets/3e7885a8-bc41-4d7f-b9e2-75c1e9f66e5c)

In my case since im not using shared memory the code that is indeed executed is the first condition. 

With the version 16.2 the sourceWasm is set to "SorterWasmNoSIMD" and doesnt work,  i modified it(just for test) and added a new line making it that the configuration chosen is always "SorterWasmNoSIMDNonShared", in this way it seems to work. 

Is there a way to map those configurations more precisely?

**Comment by mkkellogg** [comment]
Would you be able to try the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch and see if that works for you?

**Comment by pesa2000** [comment]
Tested on the same device i tested yesterday and now it seems to work, but i have a new error when loading a new splat(the first one loaded seems always to work) this is it:  

![image](https://github.com/user-attachments/assets/1959ee3f-e17a-4075-a1e9-c73df628cfcd)

The view completely freeze and doesnt even unload the previous one.

**Comment by pesa2000** [comment]
I tested a couple more things, the error above is related to the latest version too(0.4.4), switching back to 0.4.3 fixes the issue. 
The [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch has indeed the same problem.

**Comment by mkkellogg** [comment]
Did you mean the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch has the same error cause by `runSplatSort()`? I just pushed a fix for that this morning. If that issue is resolved, but the visual glitch is still there, I'll keep digging. The code *should* now select the `SorterWasmNoSIMDNonShared` WASM module if your iOS version is equal to or below 16.4, as long as `enableSIMDInSort` is false and `sharedMemoryForWorkers` is false.

**Comment by pesa2000** [comment]
I mean that using the latest version(0.4.4) has now the same problem as mentioned above. 

![image](https://github.com/user-attachments/assets/417ed89b-7ed4-4819-b0ac-676c5b0a8862)

0.4.3 is fine so maybe is related to the changes above?

**Comment by mkkellogg** [comment]
Good to know. I just pushed a fix for the `runSplatSort()` problem to the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations)  branch this morning so I think it should be fixed there.

**Comment by pesa2000** [comment]
Perfect, seems fixed right now for both problems.

I will try to let you know if i find more problems related to IOS devices.

Thank you very much for now, ill wait for the release.

**Comment by pesa2000** [comment]
Since i have this ticket open i wanted to ask something else. 

I tried to create a ShaderMaterial to use on a spherical object with a custom vertex shader, i wanted to use this sphere to wrap the splat object to create some sort of background gradient that can rotate with the camera. 

When i use this sphere with a glb it renders correctly, when i try to do it on a splat it seems like that the splat is overwriting every pixel of the canvas making it impossible to render the sphere. 

Is there something i can try to do? Didnt have luck with the "renderOrder" option

**Comment by mkkellogg** [comment]
It sounds like you essentially need to mix normal three.js objects with the splats? There's a section of the README that talks about that: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#integrating-threejs-scenes. If that's not quite what you're trying to do, maybe you can post your code and I can try to help.

**Comment by pesa2000** [comment]
As soon as i have a little more time i will send to you a snippet of my code. 

I'll open a new ticket for that, for now the issue above seems resolved for every IOS device. Thank you again.
