### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by abernier** [mkkellogg/GaussianSplats3D#3]
would be great to PR some of those classes to mrdoob/three.js?

**Comment by mkkellogg** [comment]
I did recently share this project on the three.js forums, who knows what will happen next :)

**Comment by mrdoob** [comment]
Are you planning on publishing this on npm?

Recently we have been using unpkg in examples that use external libraries:

https://github.com/mrdoob/three.js/blob/bf7d99e30e2393e5f7bcdc9b6781406ffca58374/examples/webgl_renderer_pathtracer.html#L47-L48

**Comment by mkkellogg** [comment]
I actually haven't really thought about publishing it, but if it's something people will potentially find useful, I'd be happy to do so. I'll make sure to include a UMD build as well.

I will probably need to alter my development habits and adopt a more formal, release-based workflow with proper feature branches, testing, etc. Up until now I've been pretty fast and loose with the direct updates to `main` for every little change :)

**Comment by MarcusAndreasSvensson** [comment]
I would absolutely love this as a package and I'm sure I'm not alone. Feel free to ping me if you want any assistance!

**Comment by mrdoob** [comment]
No need for branches 🤓

As long as what you "npm publish" is stable that's all that's needed.

**Comment by mkkellogg** [comment]
Yep, `stable` is the operative word, so I should at the very least write a few tests :)

**Comment by mrdoob** [comment]
You can also let the community test it for you. They'll complain if something broke 😇

**Comment by mkkellogg** [comment]
test it all in production... it's the dream!
