### ISSUE TITLE
A usage issue: How can I obtain the following coordinate data, such as the midpoint of the target?

### ISSUE THREAD

**Issue by lancelot666** [mkkellogg/GaussianSplats3D#300]
<img width="618" alt="image" src="https://github.com/user-attachments/assets/3277123c-e4c6-4bda-8dcc-0b29d2f53e3d">
How can I obtain the following coordinate data, such as the midpoint of the target?

**Comment by lancelot666** [comment]
I imported the file but don't know how to aim the camera at the target, such as a building in the city

**Comment by mkkellogg** [comment]
If you press the `I` key, it will pop up a window will a lot of debug info, including those variables:

<img width="943" alt="image" src="https://github.com/user-attachments/assets/20cf400d-c8d2-4be9-982d-1e817cb4ebef">

You can change the "Camera look-at" by clicking on something in the scene and making it the focal point. You can also use the left and right arrows to rotate the camera's up vector. Someone else had similar difficulties a while back and you can follow how we solved the issue for him here: https://github.com/mkkellogg/GaussianSplats3D/issues/40

**Comment by mkkellogg** [comment]
Just checking in -- Did you get this issue resolved?

**Comment by mkkellogg** [comment]
Going to close this for now, please let me know if you need more assistance.
