### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'quaternion')

### ISSUE THREAD

**Issue by xuzhuang1996** [mkkellogg/GaussianSplats3D#302]
when I want to test "drop-in" mode, I have this error:
`
TypeError: Cannot read properties of undefined (reading 'quaternion')
`
this is my code:
```javascript
import * as GaussianSplats3D from '@mkkellogg/gaussian-splats-3d';
import * as THREE from 'three';

const threeScene = new THREE.Scene();
const viewer = new GaussianSplats3D.DropInViewer({
    'gpuAcceleratedSort': true,
    'sharedMemoryForWorkers': false
});
viewer.addSplatScenes([
    {
        'path': 'point_cloud.ply',
        'rotation': [0, -0.857, -0.514495, 6.123233995736766e-17],
        'scale': [1.5, 1.5, 1.5],
        'position': [0, -2, -1.2]
    }
]);
threeScene.add(viewer);
```

I see the error code in 1811 line in Viewer.js:
`this.camera.quaternion`,and the camera is undefined.

Thanks!

**Comment by mkkellogg** [comment]
I think this issue might be fixed with some updates that went into this branch: https://github.com/mkkellogg/GaussianSplats3D/tree/cleanup-abort-behavior. Want to try it out?

**Comment by xuzhuang1996** [comment]
> I think this issue might be fixed with some updates that went into this branch: https://github.com/mkkellogg/GaussianSplats3D/tree/cleanup-abort-behavior. Want to try it out?

I run `npm run build-windows`,and run `npm run demo`,and replace my file 'point_cloud.ply', the error is disappear,but the page is empty. the question is still here!
