### ISSUE TITLE
A question about using WebXRMode.VR in GaussianSplats3D.DropInViewer.

### ISSUE THREAD

**Issue by pollyon** [mkkellogg/GaussianSplats3D#308]
I used your 'GaussianSplats3D.DropInViewer' method to load a splat file and added the viewer into 'Object3D' so that I can later control its position and size within the scene. Everything was working fine until I added the WebXR VR button. After entering VR mode, the splat model only partially renders or doesn’t render at all, and it seems like the camera is no longer calculating the distance to the splat correctly. Is there a way to resolve this issue?

Additionally, since I need to control the position and size of the splat within the scene, I am unable to use your 'GaussianSplats3D.Viewer' method to activate VR mode.

**Comment by mkkellogg** [comment]
There may actually be some problems with using `DropInViewer` with VR, I don't think I've ever tried doing that myself :) Can you post your source code? Maybe I can help you debug.

**Comment by mkkellogg** [comment]
Just circling back -- did you make any progress with this one?

**Comment by pollyon** [comment]
I sincerely apologize for the late response. I've been extremely busy with work over the past few weeks, but I finally have time to prepare the test files for the project. 

Below is the link to the test project.
[download link](https://drive.google.com/file/d/1ii6xaYOr5JoGIERW1vnGQjxXCaYFgdlU/view?usp=sharing)

We used the DropInViewer method to import the splat file, and after entering VR mode with the Meta Quest headset, the issue we previously discussed occurs. I've also attached a video recording of the VR view. I hope to receive your assistance. Thank you very much.

**Comment by pollyon** [comment]
We tried using your 'GaussianSplats3D.Viewer' method to start VR mode, but since your VR mode automatically generates a new WebXR configuration, it caused a conflict with our original WebXR settings, resulting in an error. We had to remove our own WebXR settings to run your VR mode properly.

On the other hand, when using the 'GaussianSplats3D.DropInViewer' method, since it does not trigger the WebXR generation mechanism in your JavaScript, no errors occur, and we can enter our own WebXR settings. However, for some reason, the Gaussian Splats appear broken and incomplete, as shown in the attached video, and the surface variations of the Gaussian Splats stop computing. These are the results of our testing over the past few weeks. We hope to receive your assistance. Thank you very much.

**Comment by mkkellogg** [comment]
One thing you can also try (if I understand the issue around the WebXR config) is to use the new [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch, which has a `Viewer` parameter for specifying WebXR initialization parameters: `webXRSessionInit`. Maybe that will work for you?

**Comment by pollyon** [comment]
We are using the version from the memory-optimizations branch and have tested webXRSessionInit. We made the settings as shown in the image, 
![1725644464428](https://github.com/user-attachments/assets/104310e2-03b6-4397-9757-b874ecde9dcd)
but after clicking "ENTER VR," an error occurred, as shown in the image. 
![1725644840269](https://github.com/user-attachments/assets/4bb4c747-1fba-4124-b8d2-9ab9bf3d445c)
![1725644643878](https://github.com/user-attachments/assets/ce0dd1fe-adf0-4d2f-a43a-ed1903891c28)
Aside from the issue of unsupported hand-tracking in the webXRSessionInit settings, the internally written layers also encountered the same unsupported issue. Even after we removed both settings, the issue persists with the error: "Cannot render to a XRWebGLLayer framebuffer outside of an XRSession animation frame callback."

**Comment by pollyon** [comment]
Currently, when testing with the viewer method, if we integrate our custom three.js scene, errors occur after clicking "ENTER VR." The only case where there is no error is when using the "DropInViewer" method, but this results in the splat model stopping surface computation and being incomplete, as shown in the image. 
![1725646577701](https://github.com/user-attachments/assets/27aedef3-8279-4dda-9ad1-8960f562eb0c)
![1725646562562](https://github.com/user-attachments/assets/55964df6-9101-4a5e-825a-a60167376750)

Is there a solution for the issues with the splat model stopping surface computation and its incompleteness?

Since "DropInViewer" does not execute the init() and setupWebXR() functions from gaussian-splats-3d.module.js, and we use our own VR button method in the three.js scene to enter VR, perhaps we don’t need to handle the WebXR settings in gaussian-splats-3d.module.js?

**Comment by mkkellogg** [comment]
FYI Using the `DropInViewer` should still result in `init()` and `setupWebXR()` being called.

For the error you're seeing using the `GaussianSplats3D.Viewer` mode, is it possible that the `renderer` that you're passing to `GaussianSplats3D.Viewer` when you initialize it is being used outside of the animation loop that it is supposed used in? When you tell the viewer to use WebXR, all rendering needs to occur in the callback function passed to `renderer.setAnimationLoop()`, and that is set up here: https://github.com/mkkellogg/GaussianSplats3D/blob/2d80511077fcb83ec5cb6da7336dc38e55d4a14b/src/Viewer.js#L1385
Because you're passing in an external `renderer`, the viewer makes it a WebXR render here: https://github.com/mkkellogg/GaussianSplats3D/blob/2d80511077fcb83ec5cb6da7336dc38e55d4a14b/src/Viewer.js#L361
After which it may not be able to be used anywhere else.

**Comment by mkkellogg** [comment]
Going to close this for now, but please let me know if you need more help.

**Comment by pollyon** [comment]
We are certain that when using DropInViewer, init() is indeed not executed, including the internal setupWebXR(), as shown in the screenshot below:
![1727464243070](https://github.com/user-attachments/assets/cae3ec6d-f879-4272-b6c0-ecba54f91a91)
In your gaussian-splats-3d.module.js at line 8843, there is a check that only executes this.init() if this.dropInMode is false. Therefore, when using DropInViewer, dropInMode is set to true, and the internal setupWebXR() is not executed. This prevents conflicts with our VR setup, allowing us to enter VR mode smoothly. However, the current issue is that after entering VR mode, the Splat model computation stops.

We want to use our own external three.js scene configuration and WebXR. If we use the three.js and WebXR setup within your gaussian-splats-3d.module.js, it will interfere with other functionalities of our program.

We hope you can provide a method that allows Splat to continue computing after entering external VR mode in DropInViewer mode. Once again, we appreciate your assistance.

**Comment by mkkellogg** [comment]
When you use the `DropInViewer` and `dropInMode` is true, the `init()` function gets called in a different way; specifically it gets called at this line: https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/Viewer.js#L1633
I just want to make sure that you have verified that it is not called there either.

**Comment by pollyon** [comment]
Hello, I have integrated the writing of DropInViewer from your example into the test project I sent you (without modifying your code). As shown in the image.
![1728900779367](https://github.com/user-attachments/assets/5aeadaa9-aaad-4b80-8b2c-e9a10de91842)

I also did not specify any external renderer and camera inside DropInViewer, so I am unsure whether the updateForDropInMode(renderer, camera) in the update function is being triggered. If it is, I have disabled this.init() inside updateForDropInMode to prevent it from executing. Will this solve the problem?

Thank you!

**Comment by mkkellogg** [comment]
`updateForDropInMode()` should always be called when you're using the `DropInViewer`. I actually cannot predict if disabling `this.init()` inside that function will fix your issue because I have never tested anything like that :) You may have to test that out yourself.
