### ISSUE TITLE
Can we change 'sphericalHarmonicsDegree' option while rendering

### ISSUE THREAD

**Issue by lucylucy27** [mkkellogg/GaussianSplats3D#312]
Hi Mkkellogg,

I can set the option sphericalHarmonicsDegree at start of rendering, and it works fine.
Now if I want to change the value during rendering without restart, how can i do ?

Thanks for your great work~

**Comment by mkkellogg** [comment]
There's not currently a nice way to do it (I need to add a function to do that). For now you could do something like:
```javascript
viewer.splatMesh.material.uniforms.sphericalHarmonicsDegree.value = [desired spherical harmonics degree]
viewer.splatMesh.material.uniformsNeedUpdate = true;
```

**Comment by mkkellogg** [comment]
I'm adding a function to set the spherical harmonics degree at runtime in [this PR](https://github.com/mkkellogg/GaussianSplats3D/pull/319). It should get released this week.

**Comment by lucylucy27** [comment]
> There's not currently a nice way to do it (I need to add a function to do that). For now you could do something like:
> 
> ```js
> viewer.splatMesh.material.uniforms.sphericalHarmonicsDegree.value = [desired spherical harmonics degree]
> viewer.splatMesh.material.uniformsNeedUpdate = true;
> ```

Thanks~~ It really works! @mkkellogg
