### ISSUE TITLE
How to determine which Gaussian bodies are rendered first while progressive loading ？

### ISSUE THREAD

**Issue by Linkersem** [mkkellogg/GaussianSplats3D#317]
Hello, Thank you for your outstanding work！
I would like to know, in the process of progressive loading, how to determine which Gaussian primitives are rendered or loaded first? I don't seem to find it in the code, can you please tell me the general principle and where it is in the code？
Thanks for your reply！

**Comment by mkkellogg** [comment]
The splats are loaded in the order that they are organized in the file from which they are loaded. You can simply look at `Viewer.splatMesh.getSplatCount()` to get the number of splats currently loaded.

**Comment by Linkersem** [comment]
Thanks for the reply！
can I understand that the ply file obtained from the original 3d gaussian-splating training does not do some extra operations in the loading process, but instead is the file type that has already been processed for ksplat and splat files?

**Comment by mkkellogg** [comment]
Right, the `.ply` files are the native output of the original 3DGS process. `.splat` (developed by [Kevin Kwok](https://github.com/antimatter15/splat)) and `.ksplat` (developed by myself) are processed versions of those files. The order of splats in `.splat` depends on the software used to generate them -- Kevin's viewer will generate them, but it won't reorder the splats, while I think [Super Splat](https://github.com/playcanvas/supersplat) optimizes the order for better cache usage. The splats in my `.ksplat` files are also reordered to have better cache utilization.

**Comment by mkkellogg** [comment]
I'll close this for now, but let me know if you have any other questions.
