### ISSUE TITLE
Sorry, check with the site admin for error: EISDIR ..

### ISSUE THREAD

**Issue by kenchikuliu** [mkkellogg/GaussianSplats3D#32]
![图片](https://github.com/mkkellogg/GaussianSplats3D/assets/44759890/599d2ffe-f619-4a45-abdb-c7a4fc0d5d19)
I run successly in my local computer,but it shows the bug. anyone can help me？

**Comment by kenchikuliu** [comment]
![图片](https://github.com/mkkellogg/GaussianSplats3D/assets/44759890/bbf68e3c-6215-42f2-aaf8-d2000e50e408)

**Comment by Brawnee** [comment]
try going directly to http://localhost:8080/index.html instead of just localhost:8080

**Comment by kenchikuliu** [comment]
> try going directly to http://localhost:8080/index.html instead of just localhost:8080

![图片](https://github.com/mkkellogg/GaussianSplats3D/assets/44759890/ab7fe6a0-86d8-425f-8dc4-6d8a9d952fb4)
![图片](https://github.com/mkkellogg/GaussianSplats3D/assets/44759890/18a10e23-1caa-44a9-8391-758fd5fd3c56)

thx, it works but the page keeps loading no 3d scence.

**Comment by Brawnee** [comment]
make sure you follow this from the README
_____________________________________________________________________________________________
The demo will be accessible locally at http://127.0.0.1:8080/index.html. You will need to download the data for the demo scenes and extract them into

<code directory>/build/demo/assets/data

The demo scene data is available here: https://projects.markkellogg.org/downloads/gaussian_splat_data.zip

**Comment by mkkellogg** [comment]
FWIW I updated the server code to support `index.html` or `index.htm` by default if not specified.

**Comment by kenchikuliu** [comment]
> FWIW I updated the server code to support `index.html` or `index.htm` by default if not specified.

Thx a lot, it runs successly, btw, could u pls tell me how to change the rendering background to white?
<img width="767" alt="1699155645024" src="https://github.com/mkkellogg/GaussianSplats3D/assets/44759890/2ea86aa8-d504-47da-a8b0-15a1d408f4be">

**Comment by Brawnee** [comment]
in the .html for example garden.html theres a "background-color" value, change that

body {
      background-color: #000000;
      height: 100vh;
      margin: 0px;
    }
