### ISSUE TITLE
Cannot read properties of null (Reading 'visibleRegionChanging' Nextjs 14.2.2

### ISSUE THREAD

**Issue by v2img** [mkkellogg/GaussianSplats3D#324]
# Unhandled Runtime Error: Cannot read properties of null (reading 'visibleRegionChanging')

## Description
When using the gaussian-splats-3d library in a Next.js application, an unhandled runtime error occurs intermittently. The error message states: "Cannot read properties of null (reading 'visibleRegionChanging')". This error seems to occur in two scenarios:
1. When navigating to a window with the gaussiansplat3d library rendered.
2. When refocusing the browser tab that has some splatscenes rendered.

![image](https://github.com/user-attachments/assets/e0d28fd6-3844-4761-88a9-073684579ff0)
![image](https://github.com/user-attachments/assets/60158682-770c-4648-ace9-42737bc95cb5)

## Environment
- Next.js version: 14.2.2
- gaussian-splats-3d library version: 0.4.4 (@mkkellogg/gaussian-splats-3d)
- React Strict Mode is enabled

## Error Message
```
TypeError: Cannot read properties of null (reading 'visibleRegionChanging')
```

## Stack Trace
```
Viewer.eval [as shouldRender]
    webpack-internal://node_modules/@mkkellogg/gaussian-splats-3d/build/gaussian-splats-3d.module.js (12777:1)
Viewer.selfDrivenUpdate
    webpack-internal://node_modules/@mkkellogg/gaussian-splats-3d/build/gaussian-splats-3d.module.js (12742:1)
```

## Code Context
The error occurs in the `shouldRender` function of the library:

```javascript
shouldRender = function() {
    let renderCount = 0;
    const lastCameraPosition = new three__WEBPACK_IMPORTED_MODULE_0__.Vector3();
    const lastCameraOrientation = new three__WEBPACK_IMPORTED_MODULE_0__.Quaternion();
    const changeEpsilon = 0.0001;
    return function() {
        let shouldRender = false;
        let cameraChanged = false;
        if (this.camera) {
            const cp = this.camera.position;
            const co = this.camera.quaternion;
            cameraChanged = Math.abs(cp.x - lastCameraPosition.x) > changeEpsilon || Math.abs(cp.y - lastCameraPosition.y) > changeEpsilon || Math.abs(cp.z - lastCameraPosition.z) > changeEpsilon || Math.abs(co.x - lastCameraOrientation.x) > changeEpsilon || Math.abs(co.y - lastCameraOrientation.y) > changeEpsilon || Math.abs(co.z - lastCameraOrientation.z) > changeEpsilon || Math.abs(co.w - lastCameraOrientation.w) > changeEpsilon;
        }
        // Problematic line:
        shouldRender = this.renderMode !== RenderMode.Never && (renderCount === 0 || this.splatMesh.visibleRegionChanging || cameraChanged || this.renderMode === RenderMode.Always || this.dynamicMode === true || this.renderNextFrame);
        if (this.camera) {
            lastCameraPosition.copy(this.camera.position);
            lastCameraOrientation.copy(this.camera.quaternion);
        }
        renderCount++;
        return shouldRender;
    };
}();
```

The error suggests that `this.splatMesh` is null when trying to access `visibleRegionChanging`.

## Steps to Reproduce
The issue occurs indeterministically and cannot be reliably reproduced. It seems to happen:
1. Sometimes when navigating to a window with the gaussiansplat3d library rendered.
2. Occasionally when refocusing the browser tab that has some splatscenes rendered.

## Expected Behavior
The application should render the gaussian splats without throwing an unhandled runtime error.

## Actual Behavior
The application throws an unhandled runtime error, which appears in the console log repeatedly.

## Additional Context
- The error occurs intermittently and is not consistently reproducible.
- It seems to be related to the timing of when the splatMesh is initialized or updated.
- React Strict Mode is enabled, which might be contributing to the issue due to its behavior of double-rendering components.

## Possible Solutions
1. Add a null check before accessing `this.splatMesh.visibleRegionChanging`.
2. Ensure that `splatMesh` is properly initialized before the `shouldRender` function is called.
4. Investigate the lifecycle of the `splatMesh` object to understand why it might be null at certain times.
5. Consider the impact of React Strict Mode on the component lifecycle and see if disabling it resolves the issue (though this is not recommended as a long-term solution).

Any insights or suggestions on how to resolve this issue would be greatly appreciated.

**Comment by mkkellogg** [comment]
Thank you for the heads up, I think I might know why this is happening in a Next.js application, and that is because of how strict mode causes the first instantiation of the viewer to get disposed right away. I think the solution is to update the `shouldRender()` function to add the following lines at the beginning:
```javascript
  if (!this.initialized || !this.splatRenderReady) return false;
  if (this.isDisposingOrDisposed()) return false;
```

**Comment by mkkellogg** [comment]
I pushed a fix to the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch, can you try that out?

**Comment by v2img** [comment]
Hi @mkkellogg , can you advise me on what's the best way to try out your branch? Shall i be downloading and attaching it locally to try? Pardon me, not really technical in these areas

**Comment by mkkellogg** [comment]
You'd have to clone this repository in a separate folder and build it there. The directions for that are here: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#building-from-source-and-running-locally

Then you install that source folder as an npm module from your main project:

```
npm install <path to source GaussianSplats3D folder>
```

(You'll have to first remove the version that you installed with `npm install @mkkellogg/gaussian-splats-3d`)

**Comment by v2img** [comment]
Hi there! thank you for your contribution and prompt responses, the library doesn't seem to be spitting out any issues so far. I've been continuing my development and dont see the error with the memory-optimization branch. LGTM!

**Comment by newguy123-creator** [comment]
> You'd have to clone this repository in a separate folder and build it there. The directions for that are here: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#building-from-source-and-running-locally
> 
> Then you install that source folder as an npm module from your main project:
> 
> ```
> npm install <path to source GaussianSplats3D folder>
> ```
> 
> (You'll have to first remove the version that you installed with `npm install @mkkellogg/gaussian-splats-3d`)

do I point the npm install to the other ones build folder or to its root folder?

**Comment by mkkellogg** [comment]
You point it to the root folder

**Comment by v2img** [comment]
@mkkellogg hello! Would there be an estimate of when would the memory optimization branch be merged and tagged/published? :D
