### ISSUE TITLE
rotating the scene while it's already loaded

### ISSUE THREAD

**Issue by LearnedVector** [mkkellogg/GaussianSplats3D#327]
Hi, if a scene is already loaded, and i want to create controls to enable users to rotate the scene, what is the best method for this? 

I tried this

```
const sceneIndex = 0; // Assuming the first scene added
const scene = viewer.getSplatScene(sceneIndex);

// Rotate the scene by 45 degrees on the Y-axis
const axis = new THREE.Vector3(0, 1, 0);
const angle = Math.PI / 4;
scene.rotateOnAxis(axis, angle);

// Update and re-render
viewer.splatMesh.updateTransforms();
viewer.forceRenderNextFrame();
```

but doesn't seem to work

**Comment by mkkellogg** [comment]
Are you making sure to enable dynamic mode? It is disabled by default but it needs to be enabled if you want to update scene transforms at runtime. You can enable with the `Viewer` parameter `'dynamicScene': true`.

**Comment by LearnedVector** [comment]
ahh that was it. thanks!
