### ISSUE TITLE
dispose failed due to Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by v2img** [mkkellogg/GaussianSplats3D#329]
A little context:
my application renders 3d splat model inside a div in a component. When i navigate away from the div and unmounts the component, i do a viewer.dispose but it always fails due to that error. 

My canvas is not the child of the document. 

Also, this stemmed from another issue. 
The event listeners WASD, was not cleaned up properly and after i load the gaussian 3D model from the .ply file using a normal Viewer (not drop in), my WASD are disabled through my application permenantly until a refresh of the tab.

This is my code to initialise the viewer:
`viewer = new GaussianSplats3D.Viewer({
        cameraUp: [0, 1, 0],
        initialCameraPosition: [0, 0, 7],
        initialCameraLookAt: [0, 0, 0],
        rootElement: containerRef.current,
        sharedMemoryForWorkers: false,
        dynamicScene: true,
      });`

this is how i dispose it:
`viewer
          .dispose()
          .then(() => {
            console.log('viewer disposed');
          })
          .catch((err: any) => {
            console.log("Didn't successfully dispose viewer", err);
          });`

**Comment by v2img** [comment]
So my question is, i wonder why is the event handlers not cleaned up properly, and how do i properly dispose it?

Im wondering when your dispose function promises catches an error, does the keyboard listener still get removed?

**Comment by v2img** [comment]
After investigation, it seems like it is orbital controls fault that the event listeners are not being cleaned up. Any suggestions on how to clean it up?

**Comment by v2img** [comment]
Ok i found the fix. in your viewer's dispose, 
add in 
`
 this.orthographicControls.dispose();
this.perspectiveControls.dispose();
`

**Comment by mkkellogg** [comment]
Ah, good catch! I'll add this fix to the next release.

**Comment by mkkellogg** [comment]
I pushed an update to the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch, could you see if that fixes it for you?

**Comment by mkkellogg** [comment]
So apparently I lied earlier 😄 The change should be in there now.

**Comment by v2img** [comment]
HAHA xD
Yes it works! Thanks :D Looking forward to next release

**Comment by mkkellogg** [comment]
Great! The next release should hopefully go out in the next couple of days.

**Comment by mkkellogg** [comment]
These changes are all now in the latest release, [v0.4.5](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.4.5)

**Comment by v2img** [comment]
Thanks for your amazing talent and contribution ser
