### ISSUE TITLE
Set internal render resolution?

### ISSUE THREAD

**Issue by Brawnee** [mkkellogg/GaussianSplats3D#33]
Hi, im wondering if theres a way in the code to set the internal render resolution, so maintain the same size viewer but for example set the model itself to be at 0.5* the resolution?

**Comment by mkkellogg** [comment]
So I don't have a "nice" way to do something like this (e.g. via a constructor parameter to the `Viewer` class). You could modify the `Viewer.init()` where it sets up the root element to look like:
```
if (!this.rootElement && !this.usingExternalRenderer) {
  this.rootElement = document.createElement('div');
  this.rootElement.style.width = '50%';
  this.rootElement.style.height = '50%';
  document.body.appendChild(this.rootElement);
  this.rootElement.style.transform = "translate(50%, 50%)";
}
```
and that would reduce the viewer's dimensions by half and center it.

Or you could use your own renderer & canvas and pass it into the constructor for `Viewer` and then you'd have complete control over the viewport size.

**Comment by Brawnee** [comment]
Appreciate the response, this seems to only make the canvas window smaller, and the gaussian is itself still the same internal resolution.

**Comment by Brawnee** [comment]
Ok, thanks for taking your time to respond.
