### ISSUE TITLE
When I draw a point or line segment, my point or line segment floats in the air instead of the ground there is no good way to solve this

### ISSUE THREAD

**Issue by chaoyang915506** [mkkellogg/GaussianSplats3D#331]
![image](https://github.com/user-attachments/assets/7a232769-0992-463e-b340-4264be0ccfee)
I use is the onMouseUp method in code, by directly using this. SceneHelper. MeshCursor. This method to get the position to the current point and mapped point or line, because I have a lot of white noise model, It causes me to float in the air most of the time when I'm drawing a point or a line segment, is there a good way to do that?

**Comment by chaoyang915506** [comment]
![image](https://github.com/user-attachments/assets/ba80303f-f6c1-4e7e-948d-ab78cd0ae75a)

**Comment by mkkellogg** [comment]
Currently, there isn't a great way to handle the mostly translucent floaters that can be found in noisy scenes. You could try loading the scene with a higher alpha threshold to eliminate some of the very translucent splats:

```javascript
viewer.addSplatScene(path, {
  'splatAlphaRemovalThreshold': 10 // valid values: 1 - 255
})
```

**Comment by chaoyang915506** [comment]
Okay, thank you.

**Comment by mkkellogg** [comment]
I'll close this for now, but please let me know if you have any other questions.
