### ISSUE TITLE
Custom Shader Material not rendering in the same scene of the threejs viewer

### ISSUE THREAD

**Issue by pesa2000** [mkkellogg/GaussianSplats3D#333]
As mentioned in the ticket #297 im trying to add a custom ShaderMaterial to render a Sphere with inside the splat. 

This is a really simple shader that creates a sphere, i then add this to the scene and then proceed to render sometimes a GLB and sometimes a SPLAT. 

I added the wireframe for better debug logic, when i load in front of the sphere a GLB it works without problems, when i do it with a splat the background is completely black and the wireframe is not visible.

Im using the same camera parameters with same NEAR/FAR planes.  

I tried to change something related to alphaTest and alphaDepth in your code too with no luck.

const vertexShader = `
      varying vec3 vPosition;

      void main() {
          vPosition = position;
          gl_Position = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      }
    `;

      // Custom fragment shader to create a spherical gradient
    const fragmentShader = `
      uniform vec3 color1; 
      uniform vec3 color2; 
      varying vec3 vPosition;

      void main() {
          float len = length(vPosition);
          float gradientFactor = len / 5.0;
          gradientFactor = clamp(gradientFactor, 0.0, 1.0);

          vec3 color = mix(color1, color2, gradientFactor);
          gl_FragColor = vec4(color, 1.0);
      }
    `;

    const uniforms = {
        color1: { value: new THREE.Color('#D4145A') },
        color2: { value: new THREE.Color('#1BFFFF') },
    };

    const material = new THREE.ShaderMaterial({
        vertexShader,
        fragmentShader,
        uniforms,
        side: THREE.DoubleSide,
        transparent: false,
        depthWrite: true,
        depthTest: false
    });

    material.wireframe = true;
    
    const geometry = new THREE.SphereGeometry(5, 64, 64);
    const sphere = new THREE.Mesh(geometry, material);
    sphere.name = "SPHERE"
    sphere.renderOrder = 0
    this.scene.add(sphere);
    
    I would be very grateful if you mind test this snippet on your code.

**Comment by mkkellogg** [comment]
Could you post the rest of your code? Specifically the code you use to set up and run the gaussian splats viewer.

**Comment by pesa2000** [comment]
I will provide a code snippet thank you can run as soon as possible.

**Comment by pesa2000** [comment]
Nvm, i was actually using a copy of my real code where i was testing something without the threeScene parameter. 

Now is working fine, thank you again
