### ISSUE TITLE
[Demo issue] - Processing splats ... infinitely

### ISSUE THREAD

**Issue by gaetan-landreau** [mkkellogg/GaussianSplats3D#343]
Hi, 

I'm a super novice in Javascript but I would like to locally run the demo of this project. Put the ksplat under `/demo/assets/data` as requested, install the project and run `npm run demo `. It works, as least I'm able to see the very first main page, but once I click on any scene, as garden for instance, something is running, but I finally ends up on a whole black page with a "processing splats" spinning indefinitely (and this _HTTP(404) Request for ./build/demo/favicon.ico -> File not found._  log from my terminal). 

Is anyone have any clues of what I'm doing wrong here ? 
Thanks a lot in advance for you help, 🙏🏻

**Comment by mkkellogg** [comment]
So just to clarify, you did download the demo data from https://projects.markkellogg.org/downloads/gaussian_splat_data.zip and you put it under `build/demo/assets/data` ? The contents of `build/demo/assets/data` should look like:
<img width="762" alt="image" src="https://github.com/user-attachments/assets/d0193542-13fa-4387-8c45-1a84dd6b66c6">

**Comment by gaetan-landreau** [comment]
Yep, we're good on this point ! Main page is loaded properly, any `.ksplat`  file is found, but loading somehow get stuck. 
<img width="245" alt="Screenshot 2024-10-01 at 08 36 26" src="https://github.com/user-attachments/assets/a7f4c32c-7133-41ff-99e3-f13746d167a9">

**Comment by mkkellogg** [comment]
And there aren't any other messages in the debug console other than the `HTTP(404) Request for ./build/demo/favicon.ico -> File not found` message? If there aren't any errors there, and the "network" tab in the developer console is showing the `.ksplat` files are getting downloaded successfully, then I admit I'm a bit stumped. I'll think about it a little more and let you know if I come up with any other ideas -- in the mean time you could try stepping through the code when it's in the infinite loop to see where it might be getting stuck.

**Comment by gaetan-landreau** [comment]
![Screenshot 2024-10-01 at 12 58 00](https://github.com/user-attachments/assets/4ac4cd22-950b-4806-8b12-5213e088873f)
Got this _pending_ status for this favicon.ico media, but I don't know to what's it related 🥲

**Comment by gaetan-landreau** [comment]
Update: got the issue - I should rather connect to `localhost:8080` !

**Comment by mkkellogg** [comment]
Glad you got it sorted out!
