### ISSUE TITLE
Camera up vs Orientation behavior

### ISSUE THREAD

**Issue by djnugent** [mkkellogg/GaussianSplats3D#35]
### Problem description:

Setting camera UP vector on file loading works great for orienting my model. But I would love to use the orientation feature instead so the model can exist in default world space. However, it does not appear to work how I'd expect. I would assume it would yield the same visual effect as changing the camera up i.e. the camera orbits the camera on the correct plane. 

**Can you confirm the expected behavior/functionality and usage?** 

### Relevant code:

```js
const up = [0.1294521689414978, -0.4815174639225006, -0.8668235540390015]
const viewer = new Viewer({
    rootElement: containerRef.current,
    //cameraUp: up,
    initialCameraPosition: [-1, 4, 6],
    initialCameraLookAt: [0, 0, 0],

});

const orientation = new THREE.Quaternion();
orientation.setFromUnitVectors(
    new THREE.Vector3(0, 1, 0),
    new THREE.Vector3(up[0], up[1], up[2]).normalize()
);

viewer.init();
viewer.loadFile(file, {
    splatAlphaRemovalThreshold: 5,
    halfPrecisionCovariancesOnGPU: true,
    position: [0, 0, 0],
    orientation: orientation.toArray(),
})
    .then(() => {
        console.log('File loaded');
        viewer.start();
    });
```

### Suggested solution:

I dug through the code to look for potential bugs, but came up empty handed. I lose track of the splatMesh.quaternion but my guess is because its a member of a threejs parent class. 

Thanks!

**Comment by mkkellogg** [comment]
I think my directions in the README are confusing. The way you'd want to construct `orientation` would be going from the `up` vector that you have already determined works well to the default up vector `<0, 1, 0>`. See if this works:
```
orientation.setFromUnitVectors(
    new THREE.Vector3(up[0], up[1], up[2]).normalize(),
    new THREE.Vector3(0, 1, 0)
);
```

**Comment by djnugent** [comment]
Ah understood. That worked great. Thank you!

I look forward to diving into your code more. A lot of great stuff going on under the hood.
