### ISSUE TITLE
DropInViewer seems to render but is invisible in three.js scene

### ISSUE THREAD

**Issue by hybridherbst** [mkkellogg/GaussianSplats3D#357]
This project uses Needle Engine (a component system for three.js). 
I attempted to add the gaussian splat viewer, however, something seems to be missing - the splats are rendered (I can see the corresponding draw call, but no visuals, in spector.js) but nothing shows up.

Reproduction: https://stackblitz.com/edit/three-dev-n6xvbd?file=main2.js

1. Load the page
2. Wait for installation
3. On the right side, a 3D scene appears
4. This repo's built-in progress bar correctly shows up
5. The draw call seems to be sent, but nothing is rendered

**Comment by seppestaes** [comment]
I'm not familiar with the product, from what i see in your example the grid and axisHelper are Needle's? Is there a way to access/pass Needle's camera, renderer to the viewer?

**Comment by hybridherbst** [comment]
Yes, but since Needle is using three.js under the hood camera and renderer are already accessible to GaussianSplats3D in the `onBeforeRender` callback that `DropInViewer` uses. There should be no difference to three.js in this regard.

If need be they can be accessed with `this.context.mainCamera` and `this.context.renderer` but I don't believe that should be necessary since they're already available in the callback.

**Comment by seppestaes** [comment]
Can you pass them to the DropInViewer? 
`
const viewer = new DropInViewer({
selfDrivenMode: false,
threeScene: scene,
renderer: gl,
camera: camera,
...
`

**Comment by hybridherbst** [comment]
I tried that and it does not change the behaviour. 
`DropInViewer` ignores those parameters since they are passed into onBeforeRender:
- https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/DropInViewer.js#L18-L19

**Comment by seppestaes** [comment]
As far as i understand: if you use the DropInViewer, the Viewer won't create new ones (camera, renderer) and they need to be passed in the options.

https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/Viewer.js#L1607C5-L1608C73

Can you check the update in Viewer?

**Comment by seppestaes** [comment]
As far as i understand: if you use the DropInViewer, the Viewer won't create new ones (camera, renderer) and they need to be passed in the options.

https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/Viewer.js#L1607C5-L1608C73

Can you check the update in Viewer?

**Comment by hybridherbst** [comment]
As mentioned, they do get passed in by three.js in the onBeforeRender callback:

https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/DropInViewer.js#L123-L125

I verified that the correct camera and renderer are passed into the update() call through the onBeforeRender callback. That's how DropInViewer works. I believe the issue here must be something else.

> Can you check the update in Viewer?

As expected, passing in those options does not change the behaviour. I updated the StackBlitz repro:
https://stackblitz.com/edit/three-dev-n6xvbd?file=main2.js%3AL21

**Comment by seppestaes** [comment]
<img width="705" alt="Screenshot 2024-11-05 at 16 57 31" src="https://github.com/user-attachments/assets/dbe6fd9d-362e-4ffc-a722-b2966b58f892">

You're right, they are present. Camera settings? Frustum culling?

**Comment by hybridherbst** [comment]
If I knew I probably wouldn't have needed to open an issue :)

@mkkellogg wanted to take a look directly:
- https://github.com/mkkellogg/GaussianSplats3D/issues/345#issuecomment-2441539325

**Comment by mkkellogg** [comment]
Sorry for the lack of movement on this one, I've been terribly busy with other things. I hope I can devote some time to it soon.

**Comment by mkkellogg** [comment]
After looking at your sample for a while, there's no obvious reason why it should not be working. There must be something happening under the hood with your engine that is affecting the rendering of the splats, and there's no way for me to debug that.

**Comment by hybridherbst** [comment]
Thanks for investigating. Needle is not doing anything special to the three.js renderer – it just adds objects to the scene graph. I'll see if I can find anything else.

**Comment by mkkellogg** [comment]
To be completely honest, I think I somewhat arbitrarily added the `.parentElement` at some point during the early days of development, and then never thought about it again 😄  (It possibly was for testing purposes, but I can't remember what I would have been testing) I actually have no specific reason for attaching the render to the DOM in that manner, so I think it could probably just go away?

I'll remove it and do some quick testing. Thank you for digging into this!

**Comment by mkkellogg** [comment]
I have a branch with what I think should fix the issue (along with some other updates) here: https://github.com/mkkellogg/GaussianSplats3D/compare/minor-updates

Want to try it out to see if it works for you?

**Comment by hybridherbst** [comment]
Tested & looking good! Thank you!
Will you make a new (minor?) release with these changes?

**Comment by mkkellogg** [comment]
Yeah that's the plan!

**Comment by hybridherbst** [comment]
Any news on that release so the issue can be closed? :)

**Comment by mkkellogg** [comment]
Well I was waiting on @jesse-small to verify that the changes in https://github.com/mkkellogg/GaussianSplats3D/compare/minor-updates matched what he had proposed in https://github.com/mkkellogg/GaussianSplats3D/pull/354

**Comment by hybridherbst** [comment]
Thank you!

**Comment by mkkellogg** [comment]
@hybridherbst So I now have a better sense of why I originally made the `rootElement` the parent of `renderer.domElement`, and it had to do the loading spinner functionality. The changes I made for this fix broke the loading spinner for some use cases, so I've had to restore using `renderer.domElement.parentElement` as the `rootElement` and rework how the renderer dimensions are calculated. The updates are in the [dev](https://github.com/mkkellogg/GaussianSplats3D/tree/dev) branch, could you see if they work for you?
