### ISSUE TITLE
Can't open file from presigned URL

### ISSUE THREAD

**Issue by hyqshr** [mkkellogg/GaussianSplats3D#373]
This `.splat` file is correct and working for me:
```
'https://huggingface.co/datasets/runes/coolsplats/resolve/main/output.splat'
```

But if I download the file from above and put it in Azure Shared Access Signature (equal to AWS S3 presigned URL) and get this url:

```
https://forreal.blob.core.windows.net/forreal-model/0/large.splat?sv=2023-01-03&st=2024-11-18T16%3A13%3A38Z&se=2024-11-21T16%3A13%3A00Z&sr=b&sp=r&sig=liN4cXEgk3ETBL2YYH2xw2fS88tjbJdK2YFGiA7Bcc4%3D
```

I will get error:

<img width="750" alt="image" src="https://github.com/user-attachments/assets/cbae035c-c8d9-4a94-9105-620400a9f6fb">

The same url will work in R3F drei `<Splat />` tag 
https://drei.docs.pmnd.rs/abstractions/splat

**Comment by mkkellogg** [comment]
Sine your aws url has no file extension, my viewer can't tell what the format is. One of the properties you can add to the `addParams` for each scene in your call to `addSplatScenes()` is `format` (sorry, I realize now that the comments for the function don't mention that property):

```javascript
viewer.addSplatScenes([
    {
      'path': '<path to first scene>',
      'splatAlphaRemovalThreshold': 20,
      format: GaussianSplats3D.SceneFormat.Ply
    },
    {
      'path': '<path to second scene>',
      format: GaussianSplats3D.SceneFormat.Splat
    }
], true)
```

**Comment by hyqshr** [comment]
Worked, thank you!
