### ISSUE TITLE
Question about Camera and Cursor Parameters in Gaussian Splats Viewer

### ISSUE THREAD

**Issue by wuhaoran11** [mkkellogg/GaussianSplats3D#374]
I hope this message finds you well. I'm currently using the Gaussian Splats Viewer and noticed the following parameters displayed during usage:

Camera position: 1.00591, 0.02695, -0.18080
Camera look-at: -0.38898, -0.46748, 7.90106
Camera up: 0.20539, -0.96532, -0.16119
Camera mode: Perspective
Cursor position: -0.39636, -0.49209, -7.91252

I’m curious about how these parameters are calculated, particularly the cursor position. Since I'm not very familiar with the inner workings of Three.js, I’d greatly appreciate it if you could explain or point me to relevant parts of the code or documentation for understanding this.

**Comment by mkkellogg** [comment]
The camera position, camera-up, and camera look-at are all standard properties of a `Camera` object in three.js, and you can read about that more here: https://threejs.org/docs/#api/en/cameras/Camera. The cursor position is calculated by performing a raycast from from the camera position, using the direction the camera is facing to create a ray, and finding the first splat in the scene that ray intersects with.  The calculation starts here: https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/Viewer.js#L561.

**Comment by wuhaoran11** [comment]
Thank you so much for your quick response! I really appreciate your help and the time you took to answer my question.
