### ISSUE TITLE
Question about Cursor Position

### ISSUE THREAD

**Issue by luisjm1992** [mkkellogg/GaussianSplats3D#379]
Thank you for the excellent work on GaussianSplats3D—it's very helpful!

Is there a function to get the mesh cursor position, like the one shown in the debug panel? I’d like to access this value to draw lines or perform other actions.

I really appreciate your help!

**Comment by mkkellogg** [comment]
A direct but hacky way to do it would be to access the viewer's `sceneHelper,` and then access its `focusMarker` property:
```javascript
viewer.sceneHelper.focusMarker.position
```
You could also code up the raycasting to compute the position yourself by doing something similar to the `Viewer` class:
https://github.com/mkkellogg/GaussianSplats3D/blob/f6f4adea2e0a5745f942767214c7d3b335a10751/src/Viewer.js#L562

**Comment by luisjm1992** [comment]
I am new to using the GaussianSplats3D viewer and I’m a bit confused about how to implement certain custom functionalities. I want to configure the viewer so that its default controls do not interfere with the features I want to add, such as raycasting to detect points when clicking on the scene and adding points of interest. How can I achieve this and ensure that my custom interactions work alongside the viewer’s default controls?

Thanks for answering.

**Comment by luisjm1992** [comment]
> Soy nuevo en el uso del visor GaussianSplats3D y estoy un poco confundido sobre cómo implementar ciertas funcionalidades personalizadas. Quiero configurar el visor para que sus controles predeterminados no interfieran con las funciones que quiero agregar, como la proyección de rayos para detectar puntos al hacer clic en la escena y agregar puntos de interés. ¿Cómo puedo lograr esto y asegurarme de que mis interacciones personalizadas funcionen junto con los controles predeterminados del visor?
> 
> Gracias por responder.

I found an example with DropInViewer, which was exactly what I was looking for.

**Comment by luisjm1992** [comment]
Point coordinates do not match the click position in the Gaussian Splating visualization.

Description
I am using the Raycaster from the library (not Three.js) to capture the (x, y, z) coordinates when clicking on a Gaussian Splating visualization. The goal is to place points at the exact position where the user clicks and eventually draw lines between these points. The code I am using is as follows:

```
const renderDimensions = new THREE.Vector2();
const mousePosition = new THREE.Vector2(event.offsetX, event.offsetY);
const outHits = [];
viewer.getRenderDimensions(renderDimensions);
viewer.raycaster.setFromCameraAndScreenPosition(viewer.camera, mousePosition, renderDimensions);

viewer.raycaster.intersectSplatMesh(viewer.splatMesh, outHits);
if (outHits.length > 0) {
    const hit = outHits[0];
    const intersectionPoint = hit.origin;
    console.log(`x=${intersectionPoint.x}, y=${intersectionPoint.y}, z=${intersectionPoint.z}`);
    const lineDrawer = new LineDrawer(intersectionPoint.x, intersectionPoint.y, intersectionPoint.z);
    const point = lineDrawer.drawingPoint();
    viewer.scene.add(point);
} else {
    console.log("No intersections detected.");
}

```

The problem is that the generated points are not positioned correctly in the Gaussian Splating visualization, meaning they do not align with the click location.

Am I skipping or missing something?

**Comment by koktavy** [comment]
@luisjm1992 did you find a solution you can share?

**Comment by ryouhei0622** [comment]
@luisjm1992 
I would also like to add points and draw lines at clicked positions. If you could share any information, I would greatly appreciate it.

**Comment by utadluis** [comment]
@koktavy @ryouhei0622  Did they find a solution?
