### ISSUE TITLE
Camera orientation settings not clear

### ISSUE THREAD

**Issue by fasteinke** [mkkellogg/GaussianSplats3D#40]
Nicely done ...

Unfortunately, at the moment with the View Your Own Scene on the demo page, it's very unintuitive as to how to set the Camera orientation parameters to get an uploaded splat view to change with the controls as expected - I tried half a dozen times, and always failed. Would it be possible to make this clearer, or easier to use?

**Comment by mkkellogg** [comment]
It's definitely annoying trying to figure out the correct orientation via trial-and-error. I added a debug object that shows the orientation of the camera controls that is toggled with the `P` key. You can also rotate the camera's up vector with the left or right arrow keys, and view the current up vector components (x, y, and z) in the info panel that is toggled with `I`.  Hopefully lining up the debug object with the desired orientation will help you figure out the right up vector for the camera. It's still not ideal, and a bit of a pain, but it will get the job done :)

**Comment by fasteinke** [comment]
Excellent! Worked like a charm ...
