### ISSUE TITLE
For the Docu: Vite and CORS

### ISSUE THREAD

**Issue by rowild** [mkkellogg/GaussianSplats3D#41]
In case somebody uses Vite: Vite seems to require some special CORS configuration to be able to read SharedBufferArray. A solution would be this:
https://github.com/chaosprint/vite-plugin-cross-origin-isolation/issues/3
or this vite plugin:
https://github.com/chaosprint/vite-plugin-cross-origin-isolation

**Comment by guyettinger** [comment]
If you don't have the ability to configure cross origin isolation on the server (i.e. github pages), you can also use a [coi-serviceworker](https://github.com/gzuidhof/coi-serviceworker) in your webpage:
```html
<script src="coi-serviceworker.js"></script>
```

**Comment by mkkellogg** [comment]
I'm going to close this issue, but I will add this info to the README.

**Comment by MengtianWen** [comment]
If you need to deploy your project to a server via Nginx, you can also achieve cross-origin isolation via Nginx configuration:
```
server {
  listen       80;
  listen  [::]:80;
  server_name  localhost;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
    add_header 'Cross-Origin-Opener-Policy' 'same-origin';	 
  }
}
```
