### ISSUE TITLE
[Help needed] - File loaded, but not displayed

### ISSUE THREAD

**Issue by rowild** [mkkellogg/GaussianSplats3D#43]
I setup an example here:
https://stackblitz.com/edit/github-ugddhz?file=index.html,src%2Fapp.js

The file is loading, the CORS are working, too. But nevertheless I do not see my file. It is a ply file from poly.cam that I converted with your converter to make it a splat file. But other files are there, too (also in the "local" public folder), and they won't work, either.

Am I doing something wrong?

And is there another place to ask question or can I ask here?

PS: I should add that the converted splat file is displayed correctly on the website demo page, where it is possible to upload a file...

**Comment by mkkellogg** [comment]
So I probably need to work on this a bit, but right now the viewer assumes the `body` element occupies the entire screen. In my demo pages I have a CSS style to force that. Try adding this to your `style.css`:

```
body {
  height: 100vh;
}
```

**Comment by rowild** [comment]
@mkkellogg You are a gem! Thank you so much for clearing the fog for me!

Would you mind letting me know if it is ok to ask here or if you prefer question somewhere else? (I think there is a kind of forum functionality here on github, maybe that one would be better?)

**Comment by mkkellogg** [comment]
Great, glad it worked! As for where to ask these kind of questions, I think for specific questions like this one, the `Issues` section is just fine (I've never actually tried the `Discussions` feature, but I think that is for more open-ended issues).

**Comment by rowild** [comment]
Ok! I hope I will not get on your nerves, because I really like your app and I would like to implement it on my website; so I assume lots of questions will come up! :-)

(I just saw at the `Super Splat` repo that the `Discussion` tab has a dedicated `Q&A` section. I personally like that.)
