### ISSUE TITLE
Run establish an online demo error

### ISSUE THREAD

**Issue by GuoFengYung** [mkkellogg/GaussianSplats3D#53]
Thanks for your great work !
I have a program
### Reproduction Step:
I use the nginx proxy pass port, and add the following configuraions:
add_header 'Cross-Origin-Embedder-Policy' 'require-corp';
add_header 'Cross-Origin-Opener-Policy' 'same-origin';

### Acutal Result:
But appear:
DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': SharedArrayBuffer transfer requires self.crossOriginIsolated .

How can i resolve this program~
Thanks

**Comment by mkkellogg** [comment]
I'm not at all familiar with how `nginx` works, so I can't really say what the right solution is. Are you sure the headers are getting set correctly? This post seems to indicate different syntax for setting headers for the proxy:  [https://stackoverflow.com/questions/19751313/forward-request-headers-from-nginx-proxy-server](https://stackoverflow.com/questions/19751313/forward-request-headers-from-nginx-proxy-server)

**Comment by GuoFengYung** [comment]
Thank you for your reply
I'll try something else~
