### ISSUE TITLE
Error: export 'default' (imported as 'SorterWasm') was not found in './sorter.wasm'

### ISSUE THREAD

**Issue by AlexRynas** [mkkellogg/GaussianSplats3D#58]
Hi. Can you tell me what sorter.wasm file is for and how to compile it? I'm trying to build this package in my Angular project. When trying to create a build, the following errors appear:
```
./src/app/services/engine/GaussianSplatsViewer/worker/SortWorker.js:96:38-48 - Error: export 'default' (imported as 'SorterWasm') was not found in './sorter.wasm' (possible exports: __wasm_call_ctors, emscripten_tls_init, sortIndexes)
./src/app/services/engine/GaussianSplatsViewer/worker/sorter.wasm - Error: Module not found: Error: Can't resolve 'env' in 'E:\Projects\artwork-threed-visualizer\VoyagerFrontend\src\app\services\engine\GaussianSplatsViewer\worker'
```
I see the compile_wasm.sh script, I ran it using PowerShell but no new file was generated. I also don’t see anything in the package.json file that relates to wasm. Can you tell me what these files are needed for and how to configure the build correctly?
Or is sorter.wasm just a binary file that needs to be imported into a JS file as a string?
**EDIT:**
It doesn't matter anymore. I used fetch to download this file. And to fix the error with self.crossOriginIsolated, I set some headers in the angular.json file. Maybe this will help someone in the future.
```
Viewer.js
fetch('assets/libs/sorter.wasm').then((response) => response.arrayBuffer())
                .then((sortWorkerBuffer) => {
                    const base64String = this.arrayBufferToBase64(sortWorkerBuffer);
...
});
```
```
angular.json
"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "artwork-threed-visualizer:build",
            "headers": {
              "Cross-Origin-Opener-Policy": "same-origin",
              "Cross-Origin-Embedder-Policy": "credentialless"
            }
          },
```

**Comment by mkkellogg** [comment]
I'm curious why you ran into the initial error. Maybe it has to do with how Angular builds work? (I've never used Angular). The rollup config specifies a plugin to import `.wasm` files as base-64 strings:
```
plugins: [
    base64({ 
        include: "**/*.wasm",
        sourceMap: false
    })
]
```

The actual plugin is a custom plugin that I included with the source code: `util/import-base-64.js`.

**Comment by AlexRynas** [comment]
The Angular build is quite difficult to customize to work with non-standard files, so it’s easier to use fetch.
