### ISSUE TITLE
Is it possible to invert the vertical rendering of a SplatMesh object?

### ISSUE THREAD

**Issue by AlexRynas** [mkkellogg/GaussianSplats3D#61]
When using an external scene, the SplatMesh object does not react in any way to changes in the camera's Up vector. All examples in the description use the negative direction of the camera Y axis, but in ThreeJS the positive Y direction is the default. Can you tell me where to change your code in order to either implement a dependence on the Up vector of the camera or at least change the direction of the SplatMesh rendering?

**Comment by mkkellogg** [comment]
I'm not sure I understand the problem, can you paste an example of your code? Altering the camera's up vector should change it's relative orientation to the scene. You can also directly access the splat mesh's transformation matrix if you want to alter its position or orientation there. Just change `Viewer.splatMesh.matrix`

**Comment by AlexRynas** [comment]
Let's take your demo as an example. In truck.html, change the cameraUp value from [0, -1, -.17] to [0, 1, -.17]. You will get an upside down scene. The mesh should depend on this value, but it doesn't. I haven't tried flipping the mesh matrix manually yet.

**Comment by mkkellogg** [comment]
Yes changing the camera's up vector doesn't actually change anything about the splat mesh's orientation, it just changes how it looks relative to the camera. If you want to change the actual position, orientation, or scale of the splat mesh, you need to change these values: `SplatMesh.position`, `SplatMesh.quaternion`,  or `SplatMesh.scale`. You can also set `SplatMesh.matrixAutoUpdate` to false and then make changes to `SplatMesh.matrix` directly.

**Comment by AlexRynas** [comment]
Ok. Got it. Thanks
