### ISSUE TITLE
Support more splat compressions levels

### ISSUE THREAD

**Issue by naive17** [mkkellogg/GaussianSplats3D#62]
Some splat imported from other compressors have different compression levels.
namely splats imported from playcanvas compressor have 190 as compression level and splats from polycam website have 97 as level and in SplatBuffer.js at line 58 it throws an error as it's not able to load these files.
is there any way to fix this behaviour?

**Comment by mkkellogg** [comment]
The only files I have tried importing from PolyCam did not have any compression and worked OK, so I have not tested with any compressed scenes. I will try to test with some and see if there is an easy fix.

**Comment by naive17** [comment]
I can send you over some files that thrown these errors! these are downloaded from the the splat viewer.
May i post a wetransfer link?

**Comment by mkkellogg** [comment]
Sure, I'd be happy to take a look

**Comment by mkkellogg** [comment]
Sorry I was confused about the nature of the problem in the beginning. I think the actual problem is that the `.splat` files you are trying  to load are compatible with the [antimatter15](https://github.com/antimatter15/splat) viewer. Those are not compatible with my viewer. It's really starting to sound like I need to support that format because it is becoming commonly used.

**Comment by mkkellogg** [comment]
I have just released an update that supports importing standard `.splat` files. If you were previously using any `.splat` files you created by converting `.ply` files to my own custom format, you'll need to rename those with a`.ksplat` extension for them to work properly.

**Comment by naive17** [comment]
Seems like it's not loading properly on a mac M1 on chrome, let's see on my main machine

**Comment by mkkellogg** [comment]
Actually I'm running into the same problem when I try to load it as well. It's weird because my viewer can load any of the .`splat` files from the antimatter15 repo. I guess I need to investigate some more.

**Comment by mkkellogg** [comment]
It looks like that file might be corrupt, or it might be not the antimatter15 format. It technically loads on the antimatter15 viewer but doesn't look right at all. When I inspect the data, the very first position is [272595901346876500000, 1236999340032, 1.2611686178923354e-44] which doesn't make any sense, and I'm guessing there are issues like that throughout the file.

**Comment by mkkellogg** [comment]
Going to close this for now. Let me know if you still need help.
