### ISSUE TITLE
Not working on android browsers except firefox android

### ISSUE THREAD

**Issue by Asxcvbn** [mkkellogg/GaussianSplats3D#63]
I have tried the online demo and also set up a website for viewing and configured the proper CORS settings in Nginx, as well as implemented HTTPS. The site is functioning fast and well on Windows browsers and iOS. However, it is not working on the default browser (webview) in Android. I checked the 'crossOriginIsolated' variable using dev tools and found that it is always false, regardless of the CORS settings I apply. Interestingly, the site works well on the Firefox mobile browser on the same device.

Upon consulting MDN, I discovered that while the 'crossOriginIsolated' variable is [available in webview](https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated), the term 'SharedArrayBuffer' is [never supported in webview](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#browser_compatibility). Additionally, MDN indicated that Chrome on Android supports SharedArrayBuffer, but it still failed to run on Chrome for Android.

Do you have any ideas on how to resolve this issue and get the website running on Android browsers? A fix would be great help and enable a broader range of users. Thanks.

**Comment by Asxcvbn** [comment]
Please note that this problem seems to be related to [this issue](https://github.com/mkkellogg/GaussianSplats3D/issues/56)

**Comment by mkkellogg** [comment]
Thanks for pointing this out, I was unaware of this issue for webview. FWIW, I have been able to get it working in Chrome on several Android devices, so I'm not quite sure what issue you're experiencing there. However it looks like I will need to support a different mode for communicating with web workers to enable webview usage.

**Comment by Asxcvbn** [comment]
Chrome Android somehow worked for me so it looks closer to what MDN said. The webview issue remains, though.

**Comment by mkkellogg** [comment]
If you're still interested, I just added a new release that allows you to disable the usage of `SharedArrayBuffer`: [v0.1.9](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.1.9).

**Comment by Asxcvbn** [comment]
Glad to know that.  I tested it out, and it worked well. Thank you! 

I guess this issue can be closed?
