### ISSUE TITLE
Support for disposal and freeing up client resources

### ISSUE THREAD

**Issue by UrbanBaumki** [mkkellogg/GaussianSplats3D#64]
In a context of SPA web apps we need a method of the Viewer to release hogged up resources. 
The issue is: If the viewer is integrated into a SPA framework (Blazor in my case), upon navigating to a "page" with no viewer and then back again to the viewer, there will be a significant performance and stuttering issues up to a point of unusability. Resources from each load/visit of the viewer are still hogging clients memory. This is because resources aren't freed since a navigation in a SPA means just an in-place html replace and NOT a full page reload. I checked memory usage upon each viewer initialization, and it keeps adding up but not freeing the memory since SPA frameworks dont know how to do that with .js resources. SPAs only handle their component disposal which has nothing to do with resources that are used up by .js libraries. This will eventually result in memory leak.
Usually .js libraries offer some kind of a destroy or dispose method. Is there a way for the viewer to do the same? If not I would grately appreciate some sort of an implementation in the future release.

**Comment by mkkellogg** [comment]
That's absolutely something I can add in a future release, should be a straightforward thing to do.

**Comment by mkkellogg** [comment]
I know it has taken a long time, but I finally added support for disposing viewer resources in [v0.2.2](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.2.2)

**Comment by laraduarte** [comment]
hello @mkkellogg viewer.dispose() is undefined in the last release (0.2.2) after using GaussianSplats3D.DropInViewer(). 

Can you provide the right way to call it?
