### ISSUE TITLE
WebXR support for Quest 3

### ISSUE THREAD

**Issue by dlazares** [mkkellogg/GaussianSplats3D#65]
Hey great work here so far @mkkellogg!

I'd love to help out where we can on a WebXR viewer for Splats.
We have our own internal renderer right now running on WebXR but it's closed source. Ideally we could support a open source renderer in a popular framework like Three.js to make them more accessible.

We have optimized splats to make them really small while retaining most of the quality. We have the splat here in the repo running at 90FPS on Quest 3 in our WebXR renderer. Hope this can be useful for testing out in the headset since most of the data out there is too large to be useful.
https://github.com/gmix-tech/small_splats

Let me know how I can help out.
Feel free to ping me at diego@gmix.ai

**Comment by mkkellogg** [comment]
Yeah if you have the `.ply` version, that would be helpful. I currently don't have code to import the antimatter15 `.splat` format. I should really make an importer for it since it's becoming so commonly used.

**Comment by dlazares** [comment]
Added it to the repo!

**Comment by chrisirhc** [comment]
Fyi, I did some exploration of getting WebXR to work while trying to get the Gaussian Splat to render on the Looking Glass (still WIP). 

I did it via the dropin.html . It *is* pretty straightforward, though I needed to set local development server to https, and change the rendering from requestAnimationFrame to `renderer.setAnimationLoop`. I tested things via the WebXR Chrome extension since I don't have a Quest device.

Ref: https://github.com/mkkellogg/GaussianSplats3D/compare/main...chrisirhc:GaussianSplats3D:chrisirhc/attempt-webxr

**Comment by mkkellogg** [comment]
@chrisirhc Thanks so much for  doing this! @dlazares Sorry for the delay in looking into this, I've got a lot on my plate these days.

**Comment by dlazares** [comment]
I tried @chrisirhc code on my Quest 3 and it works for rendering it but there was a couple issues. one had to with coordinate frames which I sorta fixed by adding
```
    renderer.xr.addEventListener('sessionstart', (e) => {

			controls.update();

            const baseReferenceSpace = renderer.xr.getReferenceSpace();
            
            const offsetPosition = camera.position;

		
			const offsetRotation = camera.quaternion;

            const transform = new XRRigidTransform( offsetPosition, { x: offsetRotation.x, y: -(offsetRotation.y), z: offsetRotation.z, w: offsetRotation.w } ); 

            const teleportSpaceOffset = baseReferenceSpace.getOffsetReferenceSpace( transform );

            renderer.xr.setReferenceSpace( teleportSpaceOffset );

		});
```

the major issue left is that the immersive scene is blurry. It's not blurry in the emulator and it's not blurry on the preview canvas on the Quest 3, but once you click enter VR and enter the immersive scene it becomes blurry. It's not blurry per se, but the splats become chunkier.

My theory is it has something to do with the change in camera. I know from previous development that the projection matrices for the webxr emulator and the actual devices are not the same. I also know we had a bug around focal length due to webxr.

@mkkellogg any thoughts on what it could be?

**Comment by dlazares** [comment]
okay turns out it was related to focal length/viewport

I bumped the version number to 1.6.0 for Three.js so that it included this issue fix
https://github.com/mrdoob/three.js/issues/21188 which was addressed by this PR. 
https://github.com/mrdoob/three.js/pull/26905

got it running 90 FPS on the Quest 3 :) 
still very minor issues around rotation

**Comment by mkkellogg** [comment]
Glad you got it working! Looks like I should incorporate the three.js version bump into the release. Thanks again @chrisirhc for helping with this.

**Comment by chrisirhc** [comment]
@dlazares Thanks so much for pointing out the blur issue and the fix! 

I think that was an issue I ran into but was stuck for a long time (and gave up).

@mkkellogg Looking forward to the merge :)

**Comment by umarkhalidAI** [comment]
Really good discussion. In your opinion, what should be the best repo to follow for WebXR (such as Quest3)? Can you also discuss some pros&cons?
1- [GaussianSplats3D-three.js](https://github.com/mkkellogg/GaussianSplats3D/)
2- [HuggingFace](https://github.com/huggingface/gsplat.js)
3-[WebGL implementation](https://github.com/antimatter15/splat/)

**Comment by mkkellogg** [comment]
@dlazares Would you be willing to share the code you used to get it running at 90 fps? I have a Quest 3 and I've managed to sort through the rotation issues so it technically works... the performance is just bad for some reason. (Not to mention when I exit immersive mode, the device basically freezes up). Also, are you using the Quest's built-in browser?

**Comment by Bishadkoju** [comment]
hi @mkkellogg  could you update the current progress in `web-xr` branch ? Thank you.

**Comment by mkkellogg** [comment]
@dlazares I have included built-in WebXR support in this branch: https://github.com/mkkellogg/GaussianSplats3D/tree/web_xr. Would you be able to try out the included demo in `demo/vr.html` to see how it works for you? Thanks!

**Comment by mkkellogg** [comment]
Going to close this one since WebXR support is now built in. Let me know if you run into any issues with it!

**Comment by EliCDavis** [comment]
I'm probably getting like, ~1 fps in WebXR on Quest 2 on my splat of 857805 points. What is your splat point count to get 90fps on quest 3 @dlazares?
