### ISSUE TITLE
Feature Request: FPS widget in the corner with option to hide 

### ISSUE THREAD

**Issue by Niko-La** [mkkellogg/GaussianSplats3D#72]
<img width="156" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/14004559/bf50d0cc-a22e-4a9f-a62a-86ec1da955f8">

Something like this, i think threejs has this already. would be very useful.

**Comment by mkkellogg** [comment]
Just circling back to this one, is the current functionality for display FPS good enough?

**Comment by Niko-La** [comment]
looks good, no complaints.

maybe make it more transparent will be nicer but not a big deal.

**Comment by mkkellogg** [comment]
Sounds good, I will probably update that info widget to look nicer :)
