### ISSUE TITLE
How can I successfully run the demo without  the CORS settings

### ISSUE THREAD

**Issue by yufeng1103** [mkkellogg/GaussianSplats3D#76]
Is there any other way to run without setting CORS，Thank you

**Comment by mkkellogg** [comment]
There currently is no way to run the demo without setting the appropriate CORS headers to enable usage of `SharedRaayBuffer`. 

But so many people have been having trouble with that part, it makes me think I need to add a parameter to disable `SharedArrayBuffer` for communicating with the web worker. It will be a bit slower, hopefully not too bad.Maybe in the next release I can do that.

**Comment by yufeng1103** [comment]
> There currently is no way to run the demo without setting the appropriate CORS headers to enable usage of `SharedRaayBuffer`.
> 
> But so many people have been having trouble with that part, it makes me think I need to add a parameter to disable `SharedArrayBuffer` for communicating with the web worker. It will be a bit slower, hopefully not too bad.Maybe in the next release I can do that.

If it could be disabled, that would be great because in some cases, I cannot set the CORS headers.

**Comment by mkkellogg** [comment]
I just added a new release that allows you to disable shared memory usage: [v0.1.9](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.1.9). Let me know if that works for you.

**Comment by yufeng1103** [comment]
After disabling SharedArrayBuffer, it can run without setting CORS headers or HTTPS protocol, and can also be used on mobile phones. Amazing!
![微信图片_20231213094254](https://github.com/mkkellogg/GaussianSplats3D/assets/149665181/3e066617-c7e8-4cb0-9344-8db2ad5d5ad8)

**Comment by mkkellogg** [comment]
glad to hear it!
