### ISSUE TITLE
3D Doesn't Appear

### ISSUE THREAD

**Issue by dbco0409** [mkkellogg/GaussianSplats3D#78]
Hello. I was looking to work on Gaussian Splat with Three.js and found this GitHub repository.
However, I immediately ran into a major obstacle.
Even after installing and uploading to the server, and testing with the codes provided in the sample, I can't see the ksplat on my server. The splat files we worked on also don't upload.
In the sample page console, there are a few more Views.js files that appear, but
Views.js doesn't show up in our console.
What could be the problem?

![we](https://github.com/mkkellogg/GaussianSplats3D/assets/75134167/b08e03c8-cfd2-4457-9153-0d55ff77cb67)
` import * as THREE from 'three';
    import * as GaussianSplats3D from 'gaussian-splats-3d';

    const viewer = new GaussianSplats3D.Viewer({
        'cameraUp': [0, -1, -0.54],
        'initialCameraPosition': [-3.15634, -0.16946, -0.51552],
        'initialCameraLookAt': [1.52976, 2.27776, 1.65898]
    });
    viewer.init();
    let path = './shoose.splat';
    viewer.loadFile(path, {
        'halfPrecisionCovariancesOnGPU': true
    })
    .then(() => {
        viewer.start();
    });`

**Comment by dbco0409** [comment]
Thank you for your prompt response.
However, it seems like there are no errors catching on my debug console.
I am leaving the test URL here
[https://bexcos.mycafe24.com/coor/ply/webgl3.html](url)

**Comment by mkkellogg** [comment]
> I am leaving the test URL here
> [https://bexcos.mycafe24.com/coor/ply/webgl3.html](https://github.com/mkkellogg/GaussianSplats3D/issues/url)

When I visit that URL, I see the follow error in the debug console:
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/6249005/212bfa7c-7729-424b-881c-daabe771ae6a)

That error means you don't have the necessary CORS headers set on your server that allow a `SharedArrayBuffer` to be used with web workers. The README talks about how to solve that problem: [https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-issues-and-sharedarraybuffer](https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-issues-and-sharedarraybuffer)

Or you can disable shared memory like I showed in the example above.

**Comment by dbco0409** [comment]
Thank you! Finally, 3D has come out.
I didn't know because I didn't get a console error.
Thank you very much for your kind and quick response.

**Comment by mkkellogg** [comment]
Great!
