### ISSUE TITLE
data expired?

### ISSUE THREAD

**Issue by 3a1b2c3** [mkkellogg/GaussianSplats3D#8]
https://github.com/mkkellogg/GaussianSplats3D/blob/main/projects.markkellogg.org/downloads/gaussian_splat_data.zip

**Comment by mkkellogg** [comment]
Thanks for the heads up, I swear that link was working properly :)

**Comment by 3a1b2c3** [comment]
i have a couple of minor problems on windows, might do a pr

**Comment by 3a1b2c3** [comment]
Maybe use google drive or drop box?

**Comment by 3a1b2c3** [comment]
Maybe use google drive or drop box? Is the splat format explained somewhere by the ay? Is it just ply?

**Comment by mkkellogg** [comment]
Sorry it took me so long to respond, the `.splat` format has been continually evolving until recently. Right now it is a bit more settled; It's way more trimmed down than a `ply` and supports compression using a chunking scheme. It still needs work, although with all the other splat viewers being developed it might make more sense to come to some agreement on a single format.
