### ISSUE TITLE
Splats disappearing depending on tilt

### ISSUE THREAD

**Issue by skia** [mkkellogg/GaussianSplats3D#80]
Hi @mkkellogg !

I'm experiecing some strange behaviour and i was wondering if you could help me/had an idea of what could be happening.

I have a ksplat that i'm trying to playback but depending on the tilt of the camera a lot of the splats disappear.
This doesn't happen when using the SIBR viewer (or antimatter15 implementation for what i can tell, but i might be wrong, as i just used the online viewer and is not too user friendly).

For what is worth i think it's to do with the sorting: i removed the `toHalfFloat` for the covariance and i could see all the points without the splats, and they were still disappering. Then again, i'm not sure why just sorting the splats would make them disappear, so maybe it's something else.

I attacched a test i've done:
[converted_file.zip](https://github.com/mkkellogg/GaussianSplats3D/files/13660255/converted_file.zip)
If you try with:
` 'cameraUp': [0, 0, -1],`
` 'initialCameraPosition': [9993.60576, -277.27384, -435.28904],`
` 'initialCameraLookAt': [9293.52797, 251.08879, 28.23262],`

and slightly tilt up/down you should see them disappearing

Note on the file: when i was playing around with the `bucketSize` and having huge files back, i did something to cull out the model given a point and a radius. 
What i've attacched is just a culled version fo the entire model, i was trying to check if there was something "in front" that would occlude the rest, i can assure you this happens on the full model as well, this is just simplier to attach 😄

**Comment by mkkellogg** [comment]
I tried with the file you attached and I cannot see anything, so I'm not sure what the problem is there.

But I think I might know what your original problem is: I currently cheat a bit to boost performance by converting splat centers to integers for the sort. The way I do it makes it possible for integer overflow to occur during the calculation of splat distances from the camera. Integer based calculations are a lot faster than floating point so this resulted in a noticeable improvement in sort time.

This isn't a problem for small scenes, but definitely is for larger scenes. I guess I need to just convert back to a floating point sort.

**Comment by mkkellogg** [comment]
I have added a WIP branch that forces the sort to be floating sort based:  [https://github.com/mkkellogg/GaussianSplats3D/tree/float_sort](https://github.com/mkkellogg/GaussianSplats3D/tree/float_sort). By default, the integer-based sorting should be off. Try that out and let me know if it changes anything. If it doesn't, I think maybe my octree might be causing problems.

**Comment by skia** [comment]
Thank you @mkkellogg !

This works like a charm 😄 

To be honest i wasn't sure it was the integer-based sorting because i couldn't figure out why they would disappear - i would have imagined points at the back would come to the front or something similar...

I think integer-based sorting should be on by default - most of the people would use small scenes and as you said it's faster, i think it would attract more people to use this library 😄 . 
Then again, in both cases i have solid 60fps using a GTX1070 - so maybe the difference is not noticeable and it's better to be more compatible?

Sorry - i forgot to mention i also changed `MaximumDistanceToRender` and `Camera.Far` to 50000!

**Comment by mkkellogg** [comment]
Great, I'm that fixed it!
