### ISSUE TITLE
Feature: Export `.ksplat` to `.ply`

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#82]
If a `.ply` file is converted to `.ksplat`, can the `.ksplat` file be converted back to `.ply` without the original `.ply` file?

**Comment by mkkellogg** [comment]
The `.ksplat` could conceivably be converted to a `.ply` (all the necessary data is present), but there currently isn't any exporter code in the app to actually output `.ply` files... is that something that would be useful?

**Comment by gotoeasy** [comment]
When i only have a `.ksplat` file and i want to edit or modify it, there are no specific tools available to directly edit a `.ksplat` file. However, if it is possible to convert the `.ksplat` file to a `.ply` file, then i can use tools that support editing `.ply` files to make the desired modifications.

**Comment by mkkellogg** [comment]
That makes sense, but how did you acquire said `.ksplat`? All `.ksplat` files get generated by converting from some other format, often `.ply`. So if you have a `.ksplat` file, there should already be a `.ply` somewhere from which it was converted.

**Comment by gotoeasy** [comment]
> That makes sense, but how did you acquire said `.ksplat`? All `.ksplat` files get generated by converting from some other format, often `.ply`. So if you have a `.ksplat` file, there should already be a `.ply` somewhere from which it was converted.

Compared to `.ply` files, `.ksplat` files are significantly smaller, so it's natural to want to use `.ksplat` for visualization, implying that people will only share and use `.ksplat` files amongst each other. This can potentially make the original `.ply` files difficult to find or even risk being lost. If the original `.ply` file cannot be found and the `.ksplat` file cannot be modified, it can be a cause for concern.

**Comment by mkkellogg** [comment]
At some point, I will probably write a `.ply` exporter. I eventually plan on writing an editor and that would be a natural feature.

**Comment by gotoeasy** [comment]
That would be great if there could be an editor as well!

**Comment by gotoeasy** [comment]
Is there a way to remove the halo and fog parts from a generated PLY model? 
 It would be even better if it can be done automatically without the need for manual editing.

**Comment by gotoeasy** [comment]
The .splat files are relatively small and are used fairly often, so it may not be strictly necessary to have the functionality to convert ksplat to ply. Therefore, I am closing this issue for the time being.

**Comment by X-deepact** [comment]
How can I make ksplat file viwer?

**Comment by hietwll** [comment]
hi, what is status for this enhancement?  also looking for tools to convert .ksplat to .plt :)

**Comment by williefalloon** [comment]
I'm also encountering a scenario where conversion back to ply would be very useful. If it's possible to support this it would be great.
