### ISSUE TITLE
Can `Cesium` support displaying `.ksplat` model files?

### ISSUE THREAD

**Issue by gotoeasy** [mkkellogg/GaussianSplats3D#83]
The compression effect of `.ksplat` model on `.ply` is great! I wonder if it is possible to display `.ksplat` models in Cesium?

For example, displaying a `.ksplat` model of a building on Cesium using a Cesium plugin, and ensuring compatibility with Cesium's browsing features like zooming, panning, and rotating...

**Comment by mkkellogg** [comment]
I have never tried integrating my splat viewer with Cesium, so I'm not sure if it's possible or how well it would work. If you would like to give it a try, I'd be very interested to hear how it goes!
