### ISSUE TITLE
 The custom camera's "lookat" parameter is not working.

### ISSUE THREAD

**Issue by pkq111** [mkkellogg/GaussianSplats3D#87]
![Uploading 屏幕截图 2023-12-19 161551.png…]()

**Comment by mkkellogg** [comment]
Could you give me a little more info on the problem, maybe some sample code? The image link above is broken.

**Comment by pkq111** [comment]
const camera = new THREE.PerspectiveCamera(
  65,
  renderWidth / renderHeight,
  0.1,
  2000
);
camera.position.copy(
  new THREE.Vector3().fromArray([13.5425, -12.13746, -37.56349])
);
camera.up = new THREE.Vector3()
  .fromArray([0.0, -0.85749, -0.5145])
  .normalize();
camera.lookAt(
  new THREE.Vector3().fromArray([10.92729, 11.80962, 9.39365])
);

let target = new THREE.Vector3(3.83761, -3.31724, 15.38071); 

let radius = 5; 
let angle = 0; 
let isRotating = true; 

const viewer = new GaussianSplats3D.Viewer({
  camera: camera, //I have set the camera parameters here.However, the "lookAt" parameter did not take effect.
  halfPrecisionCovariancesOnGPU: true,
  selfDrivenMode: false,
  ignoreDevicePixelRatio: false,
});
let loadingSpinner = new GaussianSplats3D.LoadingSpinner(null, document.body);
loadingSpinner.show();
loadingSpinner.setMessage(`Downloading splats...`);
viewer
  .loadFile("https://xxxxxx/liyang.splat", {
    splatAlphaRemovalThreshold: 1,
    showLoadingSpinner: true,
    position: [0, 1, 0],
    rotation: [0, 0, 0, 1],
    scale: [1, 1, 1],
  })
  .then(() => {
    loadingSpinner.hide();
    animate();
  });

**Comment by mkkellogg** [comment]
So it looks like there is a bug in the `Viewer` class. Even when you pass in your own camera, it uses the `initialCameraLookAt` parameter to set the camera's look-at position when it starts. When you don't specify a value for `initialCameraLookAt`, it defaults to `[0, 0, 0]`. I'll fix the issue in the next release, but in the mean-time the work-around would be to pass `initialCameraLookAt` to the `Viewer` constructor.

**Comment by mkkellogg** [comment]
Actually now that I've thought about it a bit more, I don't think this should be classified as a bug. If you use your own camera, but still tell the viewer to use its built-in controls, it still needs to set the target for the controls to be some position, which will in-turn make the camera's look-at be that same position. I think the solution here is to either:
1. Pass the desired initial camera look-at via the `initialCameraLookAt` parameter to the `Viewer` constructor
2. Tell the viewer to not use its own built-in controls, via the constructor parameter `useBuiltInControls: false`

I'll close this for now, let me know if you have any additional thoughts.
