### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by fasteinke** [mkkellogg/GaussianSplats3D#92]
Latest changes possibly caused a problem - will happily process a file from local system; but only shows a black screen for any of the demo items.

**Comment by mkkellogg** [comment]
Can you post the contents of the debug console? I'm not seeing any issues on my end, I re-cloned the repo and tested from scratch and it seems to work OK.

**Comment by fasteinke** [comment]
Just tried Google Chrome - was fine.

Normally use Firefox, current is 121.0:

Browser Console Mode
Parent process only(Fast)
Multiprocess(Slower)
Experiment next-generation-accessibility-engine-powering-screen-readers has unknown featureId: accessibilityCache 2 [RemoteSettingsExperimentLoader.sys.mjs:596:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
Alternate Service Mapping found: https://adservice.google.com.au:-1 to https://googleads.g.doubleclick.net:443 2
Referrer Policy: Ignoring the less restricted referrer policy “unsafe-url” for the cross-site request: https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&expflag=embeds_enable_muted_autoplay%3Atrue&fs=1 [embed](https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&expflag=embeds_enable_muted_autoplay%3Atrue&fs=1)
Alternate Service Mapping found: https://adservice.google.com.au:-1 to https://googleads.g.doubleclick.net:443 2
NotFoundError: No such JSWindowActor 'DevToolsFrame'

**Comment by mkkellogg** [comment]
Is this on a mobile device or a PC, and which OS are you using? For what it's worth I have tried Firefox on multiple machines and it seems to work fine, although I have only tried on Ubuntu.

**Comment by fasteinke** [comment]
Most curious! Just tested it now, and it works fine, on a Windows 10 workstation - hadn't looked at this thread, before I tried. It's just possible that a forced restart of Firefox resolved things - some cache/cookie thing?

**Comment by fasteinke** [comment]
I think I'm going mad!! The 'bug' has reversed - that is, the demo links work, but now the local files can't be viewed! Ply, splat, ksplat all just show a black screen ...

This is now "more serious" ... browser console:

Browser Console Mode
Parent process only(Fast)
Multiprocess(Slower)
Experiment next-generation-accessibility-engine-powering-screen-readers has unknown featureId: accessibilityCache 4 [RemoteSettingsExperimentLoader.sys.mjs:596:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)
ASRouter: CheckBrowserNeedsUpdate failed :>>  
XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, responseURL: "https://aus5.mozilla.org/update/6/Firefox/121.0/20231211174248/WINNT_x86_64-msvc-x64/en-GB/release/Windows_NT%252010.0.0.0.19045.3803%2520(x64)/ISET%3ASSE4_2%2CMEM%3A16312/default/default/update.xml?force=1", status: 0, statusText: "", responseType: "", response: "", responseText: "" }
[ASRouterTargeting.jsm:263](resource://activity-stream/lib/ASRouterTargeting.jsm)
Experiment next-generation-accessibility-engine-powering-screen-readers has unknown featureId: accessibilityCache [RemoteSettingsExperimentLoader.sys.mjs:596:21](resource://nimbus/lib/RemoteSettingsExperimentLoader.sys.mjs)

**Comment by fasteinke** [comment]
Okay, we're now getting consistency!! Chrome, which worked perfectly yesterday, now displays the same symptoms as Firefox - that is, demos display correctly, but only get a black screen for file views.

Which implies that the issue _is_ with the structure of the web page?

**Comment by mkkellogg** [comment]
So just to clarify, you were seeing this issue with the online demo page at [https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php](https://projects.markkellogg.org/threejs/demo_gaussian_splats_3d.php), right? I noticed the issue occurring there, but did not experience it when running the demo page locally. I fixed the online demo (I think). Let me know if it works for you.

**Comment by fasteinke** [comment]
Yes, the online page. Haven't got enough GPU horsepower locally, so using Colab, Polycam, etc, to do the processing.

Now works fine ... thanks for sorting! Yours I find is the best viewer out there, to get a good handle of what's in a render, so good to have it back in gear ...

**Comment by mkkellogg** [comment]
Thanks for letting me know about this, and I'm glad you're finding the app useful!
