### ISSUE TITLE
hot reload with bun

### ISSUE THREAD

**Issue by Niko-La** [mkkellogg/GaussianSplats3D#94]
Hi is it possible to get hot-reload working with it?

i am using `bun run build` and `bun run demo`

but a hot reload will be awesome to have

https://bun.sh/guides/http/hot

**Comment by mkkellogg** [comment]
Are you doing your own development with the code? I haven't tried `bun` before, but I did add a mode that will re-build when source files change that might work with `bun`:
```
npm run watch
```
This won't be as fast as a hot reload, but maybe it will work for your purposes?

**Comment by mkkellogg** [comment]
Going to close this for now, let me know if you have any additional questions.

**Comment by Bishadkoju** [comment]
Hi @mkkellogg , are you still using `npm run watch ` or are you using anything a bit faster?  I was wondering if there was any way to use it by simply importing the source js files without having to build it after each change,

**Comment by mkkellogg** [comment]
Currently I am still using `npm run watch`. There might be faster ways to do live reloads or rebuilds, I just haven't had time to test any.
