### ISSUE TITLE
The rotation is invalid

### ISSUE THREAD

**Issue by pkq111** [mkkellogg/GaussianSplats3D#98]
Here's my code, I set the rotation to the scene, but it didn't work.

     const threeScene = new THREE.Scene();
      const camera = new THREE.PerspectiveCamera(
        75,
        window.innerWidth / window.innerHeight,
        0.1,
        1000
      );
      const xColor = 0xff0000; // 红色
      const yColor = 0x00ff00; // 绿色
      const zColor = 0x0000ff; // 蓝色

      const lineWidth = 10; // 线条宽度

      const xMaterial = new THREE.LineBasicMaterial({
        color: xColor,
        linewidth: lineWidth,
      });
      const yMaterial = new THREE.LineBasicMaterial({
        color: yColor,
        linewidth: lineWidth,
      });
      const zMaterial = new THREE.LineBasicMaterial({
        color: zColor,
        linewidth: lineWidth,
      });

      const xGeometry = new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(0, 0, 0),
        new THREE.Vector3(50, 0, 0),
      ]);
      const xAxis = new THREE.LineSegments(xGeometry, xMaterial);

      const yGeometry = new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(0, 0, 0),
        new THREE.Vector3(0, 50, 0),
      ]);
      const yAxis = new THREE.LineSegments(yGeometry, yMaterial);

      const zGeometry = new THREE.BufferGeometry().setFromPoints([
        new THREE.Vector3(0, 0, 0),
        new THREE.Vector3(0, 0, 50),
      ]);
      const zAxis = new THREE.LineSegments(zGeometry, zMaterial);

      const axesGroup = new THREE.Object3D();
      axesGroup.add(xAxis, yAxis, zAxis);
      threeScene.add(axesGroup);
      // 设置y轴向下
      camera.up = new THREE.Vector3().fromArray([0, -1, 0]);

      camera.position.set(0, 0, 6);

      const viewer = new GaussianSplats3D.Viewer({
        initialCameraLookAt: [0, 0, 0],
        threeScene: threeScene,
        camera: camera,
      });
      let sleepStep = 0;
      viewer.addSplatScene("./assets/data/16.ply",{
        'rotation': [1, 0, 0, 0]
      }).then(() => {
        viewer.start();
      });

**Comment by pkq111** [comment]
[Uploading 16.compressed (1).zip…]()

**Comment by mkkellogg** [comment]
There was a bug that I fixed in the latest release [v0.2.1](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.2.1) that caused scene transforms to be improperly applied. Could you try that version and see if it fixes your problem?

**Comment by pkq111** [comment]
Ok, I'll try

**Comment by mkkellogg** [comment]
Just following up, did you have any luck with the latest version?

**Comment by pkq111** [comment]
I found in version 0.2.1 that I still couldn't rotate the scene

**Comment by pkq111** [comment]
https://gitee.com/fan_yan_fang/guassian-demo

**Comment by mkkellogg** [comment]
For what it's worth, when I use your code above and change the `rotation` parameter of the `addSplatScene()` function, it does change the orientation of the scene. Can you post a link to the scene you're trying to view?

**Comment by pkq111** [comment]
I think I made a mistake, rotation is valid in 0.2.1.

**Comment by mkkellogg** [comment]
Glad to hear it, I'll go ahead and close this one.
